---
title: Introduction to Psychological Research
subtitle: "Course coordinator: Margriet Groen"
email-obfuscation: javascript
order: 1

#listing:
#  id: links
#  template: ../links.ejs
#  contents: guide.yml
---

# Welcome

Welcome to the PSYC4141 material for the academic year 2026-2027!

How do we determine what is a true finding in psychological science? How do we know which theories are well supported by evidence? This module introduces you to rigorous and transparent scientific practices. You will develop systematic ways of thinking about and approaching real-world issues. Using modern techniques, you will learn how to collect, present and analyse data. We will introduce key concepts and practices of research design and data analysis through lectures. Practical laboratory classes will teach you how to design studies, handle data, perform statistical analyses and report your findings. The laboratory classes will be hands-on, giving you direct experience of all stages of a research project, including the use of specialised software. Topics covered will include questionnaire design, collecting and working with observational data, and looking at relationships between variables using correlation and regression analysis.

# Working at your own pace and seeking help

We have carefully prepared and refined the lab materials in this course over several years, and we feel that the pace of the materials is just about right for our students. Some students will complete them more quickly, and others more slowly - both of these scenarios are absolutely fine. You should work at the pace that suits **you** best, making sure **you** understand the materials before you move forward.

It is fairly inevitable that you will get stuck on the lab materials in this module at some point. This might be in Week 1, Week 2, or later. When you do, it's important you reach out for help:

-   **Ask your friends on your table**. We've designed this teaching space to help collaborative work. You are encouraged to work with other students. Make sure you ask others to explain how they've solved an exercise. Make sure you help out others where you can. Always make sure you understand the code and the exercise; don't simply be satisfied that you've got the right answer.
-   **Ask a GTA or Lecturer**. Our Graduate Teaching Assistants are there to help you. There are no "stupid questions" in statistics, so just ask the GTAs any question about what you're doing. Likewise, ask the Lecturer.
-   **Ask on the Q&A Forum on Moodle**. On the PSYC4141 moodle page you will find a [Q&A Forum](https://modules.lancaster.ac.uk/mod/forum/view.php?id=2918081). This is a great way to ask a question outside of the lab sessions. It might seem scary to ask a question in the forum, but please don't be afraid to do this. If you have a question, you can bet 30+ other students also have the same question! So by asking the question on the forum, you help out many more people on the module. A friendly GTA or Lecturer will be along to answer the question as soon as possible (we aim for within 48 hours during the working week).
-   **Ask during live online Q & A session**. Each week we hold an online "Q&A" session where we will try and resolve any general queries and problems. It's an ideal time to discuss things that students are struggling with or confused about, and can share ideas and answers. You can ask on the discussion forum above and then we might be able to pick up the issues and discuss them, but also you can ask in the session itself.

**Asking good questions** - It's really important that you give us as much information as you can when you ask your questions (in class and especially on the forum). It's so much harder to help respond to "I can't do Exercise 5 in Week 7" (because we don't know why it is that you can't do it) than for example "In Exercise 5 of Week 7, I've managed to read in the data, but the graph looks quite odd. Here is the code I'm using..."

# Course Contacts

If you have something that needs to be private, then please feel free to email the coordinator at the email addresses below:

|   | Email Address |
|----|----|
| Margriet Groen (coordinator) | [m.groen\@lancaster.ac.uk](mailto:m.groen@lancaster.ac.uk) |
|  |  |
