---
title: 1. Week 1 - Being a scientist, doing a science
subtitle: Written by Rob Davies and Margriet Groen
order: 2 # ensure this is one more than the previous script
---

:::{.callout-note title="Overview"}
This week we focus on two strands of learning:

1. Rob introduces you to what it means to do psychological science.
2. Margriet talks you through how to get started in RStudio.

The materials we have prepared to support your learning are arranged in four parts:

- Lectures
- Reading
- Pre-lab activities
- Lab activities

You can navigate to each in the side bar on the right
:::

<!-- Note: I think it is helpful to have a list of the different sections in a week for cross-referencing. I don't think it helps readability it this is visible to the students (hence I've commented them out) as the outline in the sidebar on the right already provides this info. -->
<!-- - @sec-4141-w1-lectures: Lectures: watch these before the lab session -->
<!-- - @sec-4141-w1-lectures-intro-what-module: What the module is about -->
<!-- - @sec-4141-w1-lectures-lecture: The lecture: Being a scientist, doing a science -->
<!-- - @sec-4141-w1-lectures-intro-how-r: How to get started with RStudio -->
<!-- - @sec-4141-w1-reading: Recommended readings -->
<!-- - @sec-4141-w1-prelab-activities: Activities to do before you attend your lab session -->
<!-- - @sec-4141-w1-lab-activities: Activities you do during your lab session -->

## Lectures {#sec-4141-w1-lectures}

### What this module is about: begin here {#sec-4141-w1-lectures-intro-what-module}

**Introduction to the module** (~18 minutes)

Watch this part first. It gives an overview of what the module is about, how the module is organised, how you'll be assessed and how you can ask for help. The video has captions, in case you find that helpful. You can download the slides and a transcript from the links below the video.

```{r}
#| label: Do not remove. It prevents Quarto from thinking it needs to involve Python.
```

```{=html}
<div style="position: relative; width: 100%; height: 0; padding-bottom: 56.25%">
	<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=e32a54eb-f436-4a2e-9beb-b4d200e6920c&autoplay=true&offerviewer=true&showtitle=false&showbrand=false&captions=true&interactivity=all" style="border: 1px solid #464646; position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-sizing: border-box;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="4141_intro"></iframe>
</div>
```

\newline

- [Intro slides](files/week1/4141_intro_slides.pdf)
- [Intro transcript](files/week1/4141_intro_transcript.txt)

### Interactive lecture -- Being a scientist, doing a science: watch this to get started on learning and thinking about what we are going to be doing in Psychology {#sec-4141-w1-lectures-lecture} 

You can watch the lecture for the video using the video playback windows shown next. The lecture is broken into five parts, each about 15 minutes long (some a bit longer).

1. **Big ideas, difficult questions**
2. **The hardest science**
3. **The logic, the challenges**
4. **Science is a thing that is done by people**
5. **Science is a social activity: fads, inequities and biases**

::: callout-tip
During the lecture, we suggest some questions you can think about. Responding to these questions will help you to learn.

It would be great if you cared to enter your questions to me (Rob) about the lecture. You can do that anonymously by clicking on this link and typing in your thoughts:

<https://app.sli.do/event/gChjffSSfLvkAJSr9GNuCA>
:::

This is a quick (~4 minutes) walk through of how you can watch the video lecture, with tips on how to make playback accessible and convenient.

```{=html}
<div style="position: relative; width: 100%; height: 0; padding-bottom: 56.25%">
	<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=0f42ac15-3d1c-4f3f-8c3a-b4d50115be65&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=true&start=0&interactivity=all" style="border: 1px solid #464646; position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-sizing: border-box;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="video-lecture-how-to"></iframe>
</div>
```

\newline

You can download the lecture slides as a .html file you can open in any browser.

The slides end with a references list but don't worry about reading what's in the references list, we give you recommended readings in @sec-4141-w1-reading.

::: callout-tip
The slides presented in the next videos can be downloaded as a web page: `doing-being-science.html.` 

- [Lecture slides](files/week1/doing-being-science.html)

When you download the file, double click on it to open it in your usual web browser for viewing. In some browsers, clicking on the link will just open the slides as a webpage in your browser.
:::

Next, you can see the lecture elements. We recommend that you watch them in sequence.

1. **Big ideas, difficult questions** (~17 minutes). What is science, how do we do it?

\newline

```{=html}
<div style="position: relative; width: 100%; height: 0; padding-bottom: 56.25%">
	<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=d6a2642d-4374-47e4-9b74-b4d500b1d9fb&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=true&start=0&interactivity=all" style="border: 1px solid #464646; position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-sizing: border-box;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="critical-thinking-one"></iframe>
</div>
```

\newline

2. **The hardest science** (~15 minutes). Why learning about people is hard, and why revolutionary new ways of doing psychological science are our response to the challenges.

```{=html}
<div style="position: relative; width: 100%; height: 0; padding-bottom: 56.25%">
	<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=70c5bbb0-e2b4-4126-8d6c-b4d500b9f6fc&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=true&interactivity=all" style="border: 1px solid #464646; position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-sizing: border-box;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="critical-thinking-two"></iframe>
</div>
```

\newline

3. **The logic, the challenges** (~25 minutes). The logic of the scientific method, and the challengesin doing science when it  involves trying to understand people.

```{=html}
<div style="position: relative; width: 100%; height: 0; padding-bottom: 56.25%">
	<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=2ce3cb67-f8c9-4fb2-bd76-b4d500bf7147&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=true&interactivity=all" style="border: 1px solid #464646; position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-sizing: border-box;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="critical-thinking-three"></iframe>
</div> 
```

\newline

4. **Science is a thing that is done by people** (~18 minutes). How is it that groups of people who may not know or like or trust each other can produce this thing: science?

```{=html}
 <div style="position: relative; width: 100%; height: 0; padding-bottom: 56.25%">
	<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=74066340-0d62-4c7d-a48c-b4d500c982d8&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=true&interactivity=all" style="border: 1px solid #464646; position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-sizing: border-box;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="critical-thinking-four"></iframe>
</div>
```

\newline

5. **Science is a social activity: fads, inequities and biases** (15 minutes). What do we study? Who does the studying? Fads, inequities and biases, and taking responsibility.

```{=html}
<div style="position: relative; width: 100%; height: 0; padding-bottom: 56.25%">
	<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=352d6ea9-7a1f-4ef0-a369-b4d500cf03f3&autoplay=false&offerviewer=true&showtitle=true&showbrand=true&captions=true&interactivity=all" style="border: 1px solid #464646; position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-sizing: border-box;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="critical-thinking-five"></iframe>
</div>
```

\newline

### Getting started with your practical work: you need this for the labs {#sec-4141-w1-lectures-intro-how-r}

1. **How to work with R-Studio**(~15 minutes) 

```{=html}
<div style="position: relative; width: 100%; height: 0; padding-bottom: 56.25%">
	<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=752af8d3-9b08-4184-91a9-b4d8010ce4d0&autoplay=false&offerviewer=true&showtitle=false&showbrand=false&captions=false&interactivity=all" style="border: 1px solid #464646; position: absolute; top: 0; left: 0; width: 100%; height: 100%; box-sizing: border-box;" allowfullscreen allow="autoplay" aria-label="Panopto Embedded Video Player" aria-description="4141_rstudio"></iframe>
</div>
```

\newline

- [RStudio walkthrough transcript](files/week1/4141_rstudio_transcript.txt)

2. **How to create a plot**(~ minutes)

Video will follow soon.

```{html}
```

\newline

- [How to create a plot walkthrough transcript](files/week1/4141_how_to_plot_transcript.txt)

## Reading {#sec-4141-w1-reading}

::: {.callout-tip title="Easy access to readings"}
All reading is accessible via the library. You can go to Moodle -> Library Resources -> Resource List or you can follow [**this link**](https://lancaster.alma.exlibrisgroup.com/leganto/nui/lists/93496942590001221). Readings have one of the following tags:

- **Essential**: We expect you to be familiar with these reading. You will be assessed on this.
- **Recommended**: We highly recommend these readings. They often provide a different perspective, or explain things in a different way.
- **Optional**: Further readings for those interested.

The reading list is divided into multiple sections:

- **Reading associated with statistics**: this contains links to readings useful for the development of statistical concepts and skills. The main textbook  *Fundamental statistics for the behavioral sciences* by Howell (Essential) lives here.
- **Reading associated with psychological research principles and design**: this contains links to readings that provide a good basis for foundational knowledge around research design.
- **Reading associated with Open Science principles and practices**: this contains links to key literature on the Open Science movement.
- **Week by week**: these contain links to key reading for that week that are not listed on any of the more general lists above.
:::

For **week 1**, the reading is:

- McMillan, B. T. M., Baumgartner, H.A., Bergmann, C. et al. (2026). What 5000 babies can tell us about developing minds and how to study them. *Communications Psychology, 4*, 1-5. **Essential**
- Peterson, D. (2016). The baby factory: Difficult research objects, disciplinary standards, and the production of statistical significance. *Socius, 2*, 1-10. **Recommended**
- Wright, D. B., Barnett, J., & Breakwell, G. M. (2020). Psychology as a science: What is science? In G. M. Breakwell, D. B. Wright, & J. Barnett (Eds.), *Research methods in psychology* (5th ed., pp. 119–138). SAGE Publications. **Recommended**


## Pre-lab activities {#sec-4141-w1-prelab-activities}

We often ask you to do a few things in RStudio before you attend your lab session. Not this week though, so you are ready for the in-person lab session. Well done!

## Lab activities {#sec-4141-w1-lab-activities}

Information about what you will be doing in the lab activities will follow shortly.

<!-- ### Lab activity 1: -->

<!-- ### Lab activity 2: Logging into the R-server -->


<!-- ### Lab activity 3: Reading in data and creating a plot -->

<!-- #### Background -->

<!-- We've all been there: you may be trying to focus on a lecture, but a thought on what you would like to have for lunch pops into your mind. Mind wandering describes the common experience of one's thoughts drifting away from the task at hand towards self-generated thoughts and feelings (Smallwood & Schooler, 2006). Today, we'll work with some publicly available data from a research project on mind wandering. Anna Schubert and colleagues (Schubert et al., 2024) conducted a study in which they created a 12-item questionnaire that measures how often your mind wanders without meaning to, how often you let it wander on purpose, and how aware you are when it happens. You can have a look at the questionnaire [here](files/week1/BMW-3_eng.pdf). -->

<!-- #### Aims of the activity -->

<!-- We are going to: -->

<!-- 1.  Download the files -->
<!-- 2.  Setup the appropriate bits and pieces in RStudio -->
<!-- 3.  Read in the data -->
<!-- 4.  Create a plot -->

<!-- :::{.callout-tip title="Watch the 'How to' lecture"} -->
<!-- If you haven't done so already, this is a good time to watch the 'How to' video (here @sec-4141-w1-lectures-intro-how-r) on 'How to create a plot'. -->
<!-- ::: -->

<!-- #### Step 1: Download the files -->

<!-- To complete this lab activity you will need two files: -->

<!-- 1. We'll work with an example script called [`4141_wk1_lab_act1.qmd`](files/week1/4141_wk1_lab_act1.qmd){download="4141_wk1_lab_act1.qmd"}. This is a Quarto document. -->
<!-- 2. We need a data file called [`data_bmw3.csv`](files/week1/data_bmw3.csv){download="data_bmw3.csv"}. This is a file that contains the responses of the participants in one of the studies reported on in the paper by Schubert et al. (2024). It is a file of the type `.csv`. This  means that individual bits of data are separated by comma's. We'll often use `.csv` files. -->

<!-- You can download the files by clicking on each of them. Usually they will be saved in your 'Downloads' folder. -->

<!-- Next, upload both files to your Files space on the R-server (bottom right quadrant). You could put them in the 'week1' folder you created in the previous lab activity. -->

<!-- Finally, open the example script by clicking on the file called `4141_wk1_lab_act1.qmd` in the Files space on the R-server. -->

<!-- #### Steps 2, 3 and 4 -->
<!-- For **steps 2, 3 and 4**, you'll be working in RStudio.  -->

<!-- **References** -->