metadata-files:
  - _core/metadata.yml
  
website:
  sidebar:
    style: "floating"
    search: true
    collapse-level: 1
    contents:
      - section: "PSYC4141"
        contents: PSYC4141/*
      - section: "PSYC4242"
        contents: PSYC4242/*

format:
  html: 
    include-in-header:
      - text: |
          <script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 1";};</script>
