project:
  type: website
  output-dir: docs

language:
  search-box-placeholder: "Search Year One"

website:
  title: "Statistics for Psychologists"
  favicon: "Images/favicon.png"
  page-navigation: true
  back-to-top-navigation: true
  search: 
    type: textbox
  
  repo-url: https://github.com/M1V0/Statistics_for_PSYC
  #repo-actions: [edit, issue]
  
  navbar:
    #logo: "Images/icon.png"
    left:
      - text: Home
        href: https://m1v0.github.io/Statistics_for_PSYC/
        file: index.qmd
      - text: Year 1
        file: PSYC121/index.qmd
      - text: Year 2
        file: PSYC122/index.qmd
      - text: MSc
        file: PSYC121/index.qmd
      - text: And More...
        file: PSYC122/index.qmd

  page-footer:
    left: "Website developed by Matthew Ivory"
    right:       
      - icon: github
        href: https://github.com/M1V0/Statistics_for_PSYC


format:
  html:
    theme: 
      - default
      - custom.scss
    #css: styles.css
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    toc: true
    include-in-header:
      - text: |
          <script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
          <script language="JavaScript" type="text/javascript" src="/function.js"></script>
          <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  
  
editor: source

validate-yaml: false