<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistics for Psychologists - 8. Week 19 – Linear models – critical perspectives</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../PSYC122/Week18.html" rel="prev">
<link href="../Images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 1";};</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<link rel="stylesheet" href="https://lu-psy-r.github.io/essentials/index.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="https://lu-psy-r.github.io/">
    <span class="navbar-title">Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year1/index.html" rel="" target="">
 <span class="menu-text">Year 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year2/index.html" rel="" target="">
 <span class="menu-text">Year 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year3/index.html" rel="" target="">
 <span class="menu-text">Year 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/MSc/index.html" rel="" target="">
 <span class="menu-text">MSc</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/more/index.html" rel="" target="">
 <span class="menu-text">And More…</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../PSYC122/index.html">PSYC122</a></li><li class="breadcrumb-item"><a href="../PSYC122/Week19.html">8. Week 19 – Linear models – critical perspectives</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC121/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC121</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction to PSYC121</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Descriptive statistics in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. DVs and IVs in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Customisation of graphs, and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Class test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Sampling, probability and binomial tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Filtering data and testing means (one-sample t-test)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Related-samples t-tests, plotting means and SE bars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC121/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Unrelated-samples t-test and Power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../PSYC122/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC122</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Week 11 - Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Week 12 - Correlation Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Week 13 - The Linear Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Week 14 - Chi-Square</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Week 16 – Hypotheses, associations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Week 17 – Better understanding the linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Week 18 – Developing the linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../PSYC122/Week19.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">8. Week 19 – Linear models – critical perspectives</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-wk19-introduction" id="toc-sec-wk19-introduction" class="nav-link active" data-scroll-target="#sec-wk19-introduction">Week 19: Introduction</a>
  <ul class="collapse">
  <li><a href="#our-learning-goals" id="toc-our-learning-goals" class="nav-link" data-scroll-target="#our-learning-goals">Our learning goals</a></li>
  </ul></li>
  <li><a href="#sec-wk19-lectures" id="toc-sec-wk19-lectures" class="nav-link" data-scroll-target="#sec-wk19-lectures">Lectures</a>
  <ul class="collapse">
  <li><a href="#sec-wk19-lectures-focus" id="toc-sec-wk19-lectures-focus" class="nav-link" data-scroll-target="#sec-wk19-lectures-focus">The lectures have four main areas of focus</a></li>
  </ul></li>
  <li><a href="#reading-links-to-other-classes" id="toc-reading-links-to-other-classes" class="nav-link" data-scroll-target="#reading-links-to-other-classes">Reading: Links to other classes</a></li>
  <li><a href="#sec-wk19-prelab-activities" id="toc-sec-wk19-prelab-activities" class="nav-link" data-scroll-target="#sec-wk19-prelab-activities">Pre-lab activities</a>
  <ul class="collapse">
  <li><a href="#sec-wk19-prelab-activities-1" id="toc-sec-wk19-prelab-activities-1" class="nav-link" data-scroll-target="#sec-wk19-prelab-activities-1">Pre-lab activity 1</a></li>
  </ul></li>
  <li><a href="#sec-wk19-lab-activities" id="toc-sec-wk19-lab-activities" class="nav-link" data-scroll-target="#sec-wk19-lab-activities">Lab activities</a>
  <ul class="collapse">
  <li><a href="#sec-wk19-lab-activities-1-introduction" id="toc-sec-wk19-lab-activities-1-introduction" class="nav-link" data-scroll-target="#sec-wk19-lab-activities-1-introduction">Introduction</a></li>
  <li><a href="#sec-wk19-prelab-activities-ready" id="toc-sec-wk19-prelab-activities-ready" class="nav-link" data-scroll-target="#sec-wk19-prelab-activities-ready">Get ready</a></li>
  <li><a href="#sec-wk19-lab-activities-1" id="toc-sec-wk19-lab-activities-1" class="nav-link" data-scroll-target="#sec-wk19-lab-activities-1">Lab activity 1: Work with the <code>How-to</code> guide</a></li>
  <li><a href="#sec-wk19-lab-activities-2" id="toc-sec-wk19-lab-activities-2" class="nav-link" data-scroll-target="#sec-wk19-lab-activities-2">Lab activity 2</a></li>
  <li><a href="#ok-now-lets-do-it" id="toc-ok-now-lets-do-it" class="nav-link" data-scroll-target="#ok-now-lets-do-it">OK: now let’s do it!</a></li>
  <li><a href="#task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data" id="toc-task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data" class="nav-link" data-scroll-target="#task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data">Task 13 – Examine the predictors of mean accuracy (<code>mean.acc</code>), now, for the <code>study.122</code> data</a></li>
  </ul></li>
  <li><a href="#sec-wk19-lab-activities-answers" id="toc-sec-wk19-lab-activities-answers" class="nav-link" data-scroll-target="#sec-wk19-lab-activities-answers">Answers</a>
  <ul class="collapse">
  <li><a href="#sec-wk19-lab-activities-answers-information" id="toc-sec-wk19-lab-activities-answers-information" class="nav-link" data-scroll-target="#sec-wk19-lab-activities-answers-information">Answers</a></li>
  </ul></li>
  <li><a href="#sec-wk19-lab-Q-and-A" id="toc-sec-wk19-lab-Q-and-A" class="nav-link" data-scroll-target="#sec-wk19-lab-Q-and-A">Online Q&amp;A</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">8. Week 19 – Linear models – critical perspectives</h1>
<p class="subtitle lead">Written by Rob Davies</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>This page is now live for you to use: <strong>Welcome!</strong></p>
<ul>
<li>Here is a link to the sign-in page for <a href="https://psy-rstudio.lancaster.ac.uk/auth-sign-in?appUri=%2F">R-Studio Server</a></li>
</ul>
</div>
</div>
<section id="sec-wk19-introduction" class="level2">
<h2 class="anchored" data-anchor-id="sec-wk19-introduction">Week 19: Introduction</h2>
<p>Welcome to your overview of our work together in <strong>PSYC122 Week 19</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Putting it all together</em></p>
<ul>
<li>We have completed four classes in <strong>weeks 16-19</strong>.</li>
<li>These classes are designed to enable you to revise and put into practice some of the key ideas and skills you have been developing in the first year research methods modules <em>PSYC121, PSYC123 and PSYC124</em>.</li>
<li>We have been doing this in the context of a live research project with potential real world impacts: the <strong>Clearly Understood</strong> project.</li>
</ul>
</div>
</div>
<p>In the week 19 class, we <strong>will aim to answer</strong> two research questions:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
<li>Can people accurately evaluate whether they correctly understand written information?</li>
</ol>
<p>We will be revisiting some of the ideas and techniques you have seen introduced in previous classes. And we will be extending your development with some new ideas, to strengthen your skills.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>I have said that our aim in these classes is to contribute new findings from the data we collect together.</p>
<ul>
<li><strong>That time is now.</strong></li>
</ul>
</div>
</div>
<p>The PSYC122 health comprehension survey is now closed, and we will focus our practical work in week 19 on analyzing the data we have collected.</p>
<section id="our-learning-goals" class="level3">
<h3 class="anchored" data-anchor-id="our-learning-goals">Our learning goals</h3>
<p>In Week 19, we aim to further develop skills in <em>analyzing</em> and in <em>visualizing</em> psychological data.</p>
<p>We will use linear models to estimate the association between predictors and outcomes in order to answer our research questions.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>What is new</strong> here is that we will compare the results from different studies to critically examine questions relating to <strong>reproducibility</strong>:</p>
<ul>
<li>Do we see similar results when similar methods are used to collect data to address the same questions?</li>
</ul>
</div>
</div>
<p>We shall be focusing our analysis work on response data <em>contributed by PSYC122 students</em>.</p>
<ul>
<li>But we will critically examine whether the results of our analyses of PSYC122 data are or are not similar to the results of the analyses of data collected in other studies.</li>
</ul>
<p>When we do linear models, as you have seen, we usually need to report:</p>
<ul>
<li>information about <strong>the model we specify</strong>, identifying <em>all</em> predictors;</li>
<li>our evaluation of <strong>whether the effects</strong> of one or more predictors <strong>are significant</strong>;</li>
<li>model <strong>fit statistics</strong> (<code>F, R-squared</code>) as well as coefficient estimates;</li>
<li>and <strong>descriptions of the impact</strong> of predictors.</li>
</ul>
<p>Usually, in describing the impacts of predictors, we are required to communicate:</p>
<ul>
<li>the <strong>direction</strong> of the effect – do values of the outcome variable <em>increase</em> or <em>decrease</em> given increasing values of the predictor?</li>
<li>the <strong>size</strong> of the effect – <em>how much</em> do values of the outcome variable <em>increase</em> or <em>decrease</em> given increasing values of the predictor?</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>In assessing <strong>reproducibility</strong>, therefore, we may focus here on:</p>
<ol type="1">
<li>Whether an effect is or is not significant in the datasets we are comparing;</li>
<li>Whether the estimate of the coefficient for the slope of an effect of interest has similar sign (positive or negative) or size (the value of the coefficient) in the datasets we are comparing.</li>
</ol>
</div>
</div>
</section>
</section>
<section id="sec-wk19-lectures" class="level2">
<h2 class="anchored" data-anchor-id="sec-wk19-lectures">Lectures</h2>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before you go on to the activities in <a href="#sec-wk19-lab-activities">Section&nbsp;5</a>, <strong>watch</strong> the lectures:</p>
</div>
</div>
<p>The lecture for this week is presented in four short parts. You can view video recordings of the lectures using Panopto, by clicking on the video images shown following.</p>
<ul>
<li>Anybody who has the link should be able to view the video.</li>
</ul>
<ol type="1">
<li><strong>Overview</strong> (17 minutes): Critical perspectives – The real challenge in psychological science (people vary, results vary) – variation, replication and evaluating evidence across multiple studies.</li>
</ol>
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=0e35b8e9-dd4f-4fb7-a88e-afbe010b250a&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=true&amp;captions=false&amp;interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" aria-label="Panopto Embedded Video Player"></iframe>
<ol start="2" type="1">
<li><strong>The Clearly Understood project – questions and analyses</strong> (13 minutes): Critical thinking – candidate answers, our assumptions, the sources of uncertainty, and working with samples.</li>
</ol>
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=6d20197c-6559-463b-8672-afbe011e2371&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=true&amp;captions=false&amp;interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" aria-label="Panopto Embedded Video Player"></iframe>
<ol start="3" type="1">
<li><strong>Evaluating evidence across studies</strong> (18 minutes): People vary, results vary – evaluating, thinking about, critically reflecting on analysis results</li>
</ol>
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=22d3bf7c-1710-4a75-9a73-b12b00b502b1&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=true&amp;captions=false&amp;interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" aria-label="Panopto Embedded Video Player"></iframe>
<ol start="4" type="1">
<li><strong>Becoming a power learner</strong> (24 minutes): Reproducibility, sharing, and learning to exploit the R knowledge ecosystem – every question you ever have has an answer somewhere online; find out how to locate and use this knowledge for yourself.</li>
</ol>
<iframe src="https://lancaster.cloud.panopto.eu/Panopto/Pages/Embed.aspx?id=3633c4c0-e364-4d8f-beba-b12b00bb18f7&amp;autoplay=false&amp;offerviewer=true&amp;showtitle=true&amp;showbrand=true&amp;captions=false&amp;interactivity=all" height="405" width="720" style="border: 1px solid #464646;" allowfullscreen="" allow="autoplay" aria-label="Panopto Embedded Video Player"></iframe>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The slides presented in the videos can be downloaded either as a web page or as a Word document.</p>
</div>
</div>
<ul>
<li><a href="data/week19/122-linear-model-perspectives.html">The slides</a> exactly as presented (21 MB).</li>
<li><a href="data/week19/122-linear-model-perspectives-printable-edit.docx">The slides</a> converted to a Word .docx (11 MB).</li>
</ul>
<p>You can download the web page <code>.html</code> file and click on it to open it in any browser (e.g., Chrome, Edge or Safari). The slide images are high quality and there are a lot of them, so the file is quite big; it may take a few seconds to download.</p>
<p>You can download the <code>.docx</code> file and click on it to open it as a Word document that you can then edit. Converting the slides to a .docx distorts some images but the benefit of the conversion is that it makes it easier for you to add your notes.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>To work with our lecture recordings:</p>
<ul>
<li>Watch the video parts right through.</li>
<li>Use the printable versions of the slides to make notes.</li>
<li>Try out the coding exercises in the how-to guide and the activity tasks or questions (<a href="#sec-wk19-lab-activities">Section&nbsp;5</a>) to learn how to construct visualizations and do analyses.</li>
</ul>
</div>
</div>
<section id="sec-wk19-lectures-focus" class="level3">
<h3 class="anchored" data-anchor-id="sec-wk19-lectures-focus">The lectures have four main areas of focus</h3>
<p><strong>1. The real challenges in psychological science</strong></p>
<p>We step back to get a broader perspective on what we are doing when we are doing psychological science. We look at some of the <em>real</em> challenges that professional psychologists work with, as we attempt to build a scientific understanding of what people think and do, and why they do it.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>What makes psychological science challenging:</p>
<ol type="1">
<li>People vary</li>
<li>Results vary</li>
</ol>
</div>
</div>
<p><strong>2. Critical thinking</strong></p>
<p>The power and flexibility of the linear model presents challenges. We must decide which candidate predictor variables we specify in our model. This means <em>we must</em> think critically.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can develop our critical thinking skills by considering:</p>
<ol type="1">
<li>Our assumptions about:</li>
</ol>
<ul>
<li>validity;</li>
<li>measurement;</li>
<li>generalizability.</li>
</ul>
<ol start="2" type="1">
<li>Sources of uncertainty about:</li>
</ol>
<ul>
<li>predicted change in outcomes, given our predictors;</li>
<li>ways that expected changes vary between people or groups;</li>
<li>random ways that specific responses can be produced.</li>
</ul>
</div>
</div>
<p><strong>3. Evaluating evidence across multiple studies</strong></p>
<p>All important questions in the psychological scientific literature are addressed in <em>multiple studies</em>: how do we evaluate the evidence, comparing the results from different studies?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>How do we <em>build</em> knowledge in psychological science?</p>
<p>We consider:</p>
<ul>
<li>replication</li>
<li>reproducibility</li>
</ul>
<p>And how to assess results across multiple studies.</p>
</div>
</div>
<p>These are complex concerns and you will learn more about them, in other modules, this year and next year, when you develop an understanding of systematic reviews, meta-analysis, and the critical evaluation of scientific evidence.</p>
<p><strong>4. How to become a power user</strong></p>
<p>You have been learning about data analysis using R. We have been providing rich learning materials but in Week 19 we start to explore the wider world of knowledge about data analysis and R.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>R is <em>free</em> and <em>open</em>. This means that:</p>
<ul>
<li>there is a vast knowledge ecosystem you can use for your own purposes;</li>
<li>learning to be a powerful data analyst involves learning how to locate and to use the resources that are out there.</li>
</ul>
</div>
</div>
<p>We hope that these lessons are just the start for many of you.</p>
<p><em>Every</em> problem you ever have:</p>
<ul>
<li>someone has had it before;</li>
<li>solved it;</li>
<li>and written a blog or social media post or recorded a YouTube or TikTok about it.</li>
</ul>
</section>
</section>
<section id="reading-links-to-other-classes" class="level2">
<h2 class="anchored" data-anchor-id="reading-links-to-other-classes">Reading: Links to other classes</h2>
<p>We do not provide further reading for this class but you will find it helpful to revise some of the key ideas you have been learning about PSYC122 and in other modules.</p>
<ul>
<li>The lectures in <em>PSYC123</em> on: the scientific method; reliability and validity; experimental design, especially between-subjects studies; hypothesis testing; and precise hypotheses.</li>
<li>The lecture in <em>PSYC122</em> on linear models.</li>
</ul>
</section>
<section id="sec-wk19-prelab-activities" class="level2">
<h2 class="anchored" data-anchor-id="sec-wk19-prelab-activities">Pre-lab activities</h2>
<section id="sec-wk19-prelab-activities-1" class="level3">
<h3 class="anchored" data-anchor-id="sec-wk19-prelab-activities-1">Pre-lab activity 1</h3>
<p>The survey is now closed.</p>
<p>If you want more information about the project, we invite you to read the pre-registered research plan for the <em>PSYC122 health advice</em> research project.</p>
<p><a href="https://osf.io/p6fsc/">Read the project pre-registration</a></p>
</section>
</section>
<section id="sec-wk19-lab-activities" class="level2">
<h2 class="anchored" data-anchor-id="sec-wk19-lab-activities">Lab activities</h2>
<section id="sec-wk19-lab-activities-1-introduction" class="level3">
<h3 class="anchored" data-anchor-id="sec-wk19-lab-activities-1-introduction">Introduction</h3>
<p>We will do our practical lab work to develop your skills in the context of the <strong>Clearly Understood</strong> project.</p>
<ul>
<li>Our focus is on what makes it easy or difficult for people to understand written health information.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>In Week 19, we aim to answer the research questions:</p>
<ol type="1">
<li>What person attributes predict success in understanding health information?</li>
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
</div>
</div>
<p>PSYC122 students contributed their responses to a survey we have been using to collect data to find answers to these questions.</p>
<p>In our practical work, we will be examining the PSYC122 data but, as we do so, we should understand that no one study in psychological science will give us definitive answers to any interesting question about people and what they do.</p>
<p>In the practical work, you will be asked to reflect on how data from different studies – using the same methods, with the same aims – may nevertheless vary:</p>
<ul>
<li>vary in the data distributions;</li>
<li>and vary in the results that analyses indicate.</li>
</ul>
<p>Critically evaluating results across a series of studies, or replication attempts, is part of the process of accumulating evidence to build insight in psychological science, given measurement under uncertainty and limits in samples.</p>
</section>
<section id="sec-wk19-prelab-activities-ready" class="level3">
<h3 class="anchored" data-anchor-id="sec-wk19-prelab-activities-ready">Get ready</h3>
<section id="download-the-data" class="level4">
<h4 class="anchored" data-anchor-id="download-the-data">Download the data</h4>
<p>Click on the link: <a href="data/week19/122-week19_for_students.zip">122-week19_for_students.zip</a> to download the data files folder. Then upload the contents to the new folder you created in RStudio Server.</p>
<p>The downloadable .zip folder includes the data files:</p>
<ul>
<li><code>study-one-general-participants.csv</code></li>
<li><code>study-two-general-participants.csv</code></li>
<li><code>2023-24_PSYC122-participants.csv</code></li>
</ul>
<p>and the R Markdown <code>.Rmd</code>:</p>
<ul>
<li><code>2023-24-PSYC122-w19-how-to.Rmd</code></li>
</ul>
<p>If you can’t upload these files to the server – this affects some students – you can use some code to get R to do it for you: uncover the code box below to reveal the code to do this.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>You can use the code below to directly download the file you need in this lab activity to the server.</li>
<li>Remember that you can copy the code to your clipboard by clicking on the ‘clipboard’ in the top right corner.</li>
</ul>
<ol type="1">
<li>Get the <code>study-one-general-participants.csv</code> data</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">"https://github.com/lu-psy-r/statistics_for_psychologists/blob/main/PSYC122/data/week19/study-one-general-participants.csv?raw=true"</span>, <span class="at">destfile =</span> <span class="st">"study-one-general-participants.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Get the <code>study-two-general-participants.csv</code> data</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">"https://github.com/lu-psy-r/statistics_for_psychologists/blob/main/PSYC122/data/week19/study-two-general-participants.csv?raw=true"</span>, <span class="at">destfile =</span> <span class="st">"study-two-general-participants.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Get the 2023-24 PSYC122 <code>2023-24_PSYC122-participants.csv</code> data</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">"https://github.com/lu-psy-r/statistics_for_psychologists/blob/main/PSYC122/data/week19/2023-24_PSYC122-participants.csv?raw=true"</span>, <span class="at">destfile =</span> <span class="st">"2023-24_PSYC122-participants.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="1">
<li>Get the <code>2023-24-PSYC122-w19-how-to.Rmd</code> how-to guide</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">"https://github.com/lu-psy-r/statistics_for_psychologists/blob/main/PSYC122/data/week19/2023-24-PSYC122-w19-how-to.Rmd?raw=true"</span>, <span class="at">destfile =</span> <span class="st">"2023-24-PSYC122-w19-how-to.Rmd"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
<section id="sec-wk19-data-summary" class="level4">
<h4 class="anchored" data-anchor-id="sec-wk19-data-summary">Check: What is in the data files?</h4>
<p>Each of the data files we will work with has a similar structure, as you can see in this extract.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">participant_ID</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean.acc</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mean.self</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">study</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">AGE</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SHIPLEY</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">HLVA</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">FACTOR3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">QRITOTAL</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">GENDER</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">EDUCATION</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">ETHNICITY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">studytwo.1</td>
<td style="text-align: right;">0.4107143</td>
<td style="text-align: right;">6.071429</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Higher</td>
<td style="text-align: left;">Asian</td>
</tr>
<tr class="even">
<td style="text-align: left;">studytwo.10</td>
<td style="text-align: right;">0.6071429</td>
<td style="text-align: right;">8.500000</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Secondary</td>
<td style="text-align: left;">White</td>
</tr>
<tr class="odd">
<td style="text-align: left;">studytwo.100</td>
<td style="text-align: right;">0.8750000</td>
<td style="text-align: right;">8.928571</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">66</td>
<td style="text-align: right;">40</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Higher</td>
<td style="text-align: left;">White</td>
</tr>
<tr class="even">
<td style="text-align: left;">studytwo.101</td>
<td style="text-align: right;">0.9642857</td>
<td style="text-align: right;">8.500000</td>
<td style="text-align: left;">studytwo</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">Female</td>
<td style="text-align: left;">Higher</td>
<td style="text-align: left;">White</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>You can use the <em>scroll bar</em> at the bottom of the data window to view different columns.</p>
<p>You can see the columns:</p>
<ul>
<li><code>participant_ID</code> participant code;</li>
<li><code>mean.acc</code> average accuracy of response to questions testing understanding of health guidance (varies between 0-1);</li>
<li><code>mean.self</code> average self-rated accuracy of understanding of health guidance (varies between 1-9);</li>
<li><code>study</code> variable coding for what study the data were collected in</li>
<li><code>AGE</code> age in years;</li>
<li><code>HLVA</code> health literacy test score (varies between 1-16);</li>
<li><code>SHIPLEY</code> vocabulary knowledge test score (varies between 0-40);</li>
<li><code>FACTOR3</code> reading strategy survey score (varies between 0-80);</li>
<li><code>GENDER</code> gender code;</li>
<li><code>EDUCATION</code> education level code;</li>
<li><code>ETHNICITY</code> ethnicity (Office National Statistics categories) code.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is always a good idea to view the dataset – click on the name of the dataset in the R-Studio <code>Environment</code> window, and check out the columns, scroll through the rows – to get a sense of what you are working with.</p>
</div>
</div>
</section>
</section>
<section id="sec-wk19-lab-activities-1" class="level3">
<h3 class="anchored" data-anchor-id="sec-wk19-lab-activities-1">Lab activity 1: Work with the <code>How-to</code> guide</h3>
<p>The <code>how-to</code> guide comprises an .Rmd file:</p>
<ul>
<li><code>2023-24-PSYC122-w19-how-to.Rmd</code></li>
</ul>
<p>It is full of advice and example code.</p>
<p>The code in the <code>how-to</code> guide was written to work with <strong>two data files</strong>:</p>
<ul>
<li><code>study-one-general-participants.csv</code></li>
<li><code>study-two-general-participants.csv</code></li>
</ul>
<p>We will be working with <em>your</em> (PSYC122) response data in <a href="#sec-wk19-lab-activities-2">Section&nbsp;5.4</a>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>We show you how to do everything you need to do in the lab activity (<a href="#sec-wk19-lab-activities-2">Section&nbsp;5.4</a>, shown following) in the <code>how-to</code> guide.</p>
<ul>
<li>Start by looking at the <code>how-to</code> guide to understand what steps you need to follow in the lab activity.</li>
</ul>
</div>
</div>
<p>We will take things <em>step-by-step</em>.</p>
<p>We split .Rmd scripts by steps, tasks and questions:</p>
<ul>
<li>different steps for different phases of the analysis workflow;</li>
<li>different tasks for different things you need to do;</li>
<li>different questions to examine different ideas or coding challenges</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Make sure you start at the top of the <code>.Rmd</code> file and work your way, in order, through each task.</li>
<li>Complete each task before you move on to the next task.</li>
</ul>
</div>
</div>
<p>In the activity <a href="#sec-wk19-lab-activities-2">Section&nbsp;5.4</a>, we are going to work through a sequence of steps and tasks that mirrors the sequence you find in the <code>how-to</code> guide.</p>
<ul>
<li>There is a little bit of variation, comparing the later steps in the <code>how-to</code> guide and the steps in <a href="#sec-wk19-lab-activities-2">Section&nbsp;5.4</a>, but that variation is designed to help you with your learning.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Notice that we are gradually building up our skills: consolidating what we know; revising important learning; and extending ourselves to acquire new skills.</li>
</ul>
</div>
</div>
<p><strong>Step 1: Set-up</strong></p>
<ol type="1">
<li>Empty the R environment – using <code>rm(list=ls())</code></li>
<li>Load relevant libraries – using <code>library()</code></li>
</ol>
<p><strong>Step 2: Load the data</strong></p>
<ol start="3" type="1">
<li>Read in the data files – using <code>read_csv()</code></li>
<li>Inspect both datasets – using <code>head()</code> and <code>summary()</code></li>
</ol>
<p><strong>Step 3: Compare the data from the different studies</strong></p>
<ol start="5" type="1">
<li>Compare the data distributions from the two studies – using <code>geom_histogram()</code> 6-7. and by constructing grids of plots</li>
</ol>
<p><strong>Step 4: Use scatterplots and correlation to examine associations between variables</strong></p>
<ol start="8" type="1">
<li>Draw scatterplots to compare the potential association between variables</li>
<li>Create grids of plots to make side-by-side comparisons of associations in different datasets</li>
<li>Estimate the associations between pairs of variables and compare the estimates</li>
</ol>
<p><strong>Step 5: Use a linear model to to answer the research questions – models with multiple predictors</strong></p>
<ol start="11" type="1">
<li>Examine the relation between one outcome and multiple predictors</li>
<li>Do this in comparable datasets, and compare summaries or plots</li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you are unsure about what you need to do, look at the advice in <code>2023-24-PSYC122-w19-how-to.Rmd</code> on how to do the tasks, with examples on how to write the code.</p>
</div>
</div>
<p>You will see that you can match a task in the activity <a href="#sec-wk19-lab-activities-2">Section&nbsp;5.4</a> to the same task in the <code>how-to</code> guide. The <code>how-to</code> shows you what function you need and how you should write the function code.</p>
<p>This process of adapting demonstration code is a process critical to data literacy and to effective problem solving in modern psychological science.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Don’t forget: You will need to change the names of the dataset or the variables to complete the tasks in <a href="#sec-wk19-lab-activities-2">Section&nbsp;5.4</a>.</p>
</div>
</div>
</section>
<section id="sec-wk19-lab-activities-2" class="level3">
<h3 class="anchored" data-anchor-id="sec-wk19-lab-activities-2">Lab activity 2</h3>
</section>
<section id="ok-now-lets-do-it" class="level3">
<h3 class="anchored" data-anchor-id="ok-now-lets-do-it">OK: now let’s do it!</h3>
<p>In the following, we will guide you through the tasks and questions step by step.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>We will not <em>at first</em> give you the answers to questions about the data or about the results of analyses.</li>
<li>An answers version of the workbook will be provided after the last lab session (check the answers then in <a href="#sec-wk19-lab-activities-answers">Section&nbsp;6</a>) so that you can check whether your independent work has been correct.</li>
</ol>
</div>
</div>
<section id="sec-wk19-lab-activities-2-questions" class="level4">
<h4 class="anchored" data-anchor-id="sec-wk19-lab-activities-2-questions">Questions</h4>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Students have told us</strong> that it would be helpful to your learning if we reduce the information in the hints we provide you. <strong>We have done this</strong> in Week 19.</p>
<p>The motivation for doing this is:</p>
<ol type="1">
<li>It will require you to do more <em>active</em> thinking to complete tasks or answer questions;</li>
<li>Thus, you can check to see how your learning is developing – can you do the tasks, given what you know now?</li>
<li>Plus, psychological research shows that <em>active</em> thinking is better for understanding and for learning.</li>
</ol>
<p>Where we do give you hints, we will sometimes replace the correct bit of code with a place-holder: <code>...</code></p>
<ul>
<li>Your task will therefore be to replace the place-holder <code>...</code> with the correct bit of code or the correct dataset or variable name.</li>
</ul>
</div>
</div>
</section>
<section id="step-1-set-up" class="level4">
<h4 class="anchored" data-anchor-id="step-1-set-up">Step 1: Set-up</h4>
<p>To begin, we set up our environment in R.</p>
<section id="task-1-run-code-to-empty-the-r-environment" class="level5">
<h5 class="anchored" data-anchor-id="task-1-run-code-to-empty-the-r-environment">Task 1 – Run code to empty the R environment</h5>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- #| eval: false -->
<!-- rm(list=ls()) -->
<!-- ``` -->
<!-- ::: -->
</section>
<section id="task-2-run-code-to-load-relevant-libraries" class="level5">
<h5 class="anchored" data-anchor-id="task-2-run-code-to-load-relevant-libraries">Task 2 – Run code to load relevant libraries</h5>
<p>Notice that in Week 19, we need to work with the libraries <code>ggeffects</code>, <code>patchwork</code> and <code>tidyverse</code>. Use the <code>library()</code> function to make these libraries available to you.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- library("ggeffects") -->
<!-- library("patchwork") -->
<!-- library("tidyverse") -->
<!-- ``` -->
<!-- ::: -->
</section>
</section>
<section id="step-2-load-the-data" class="level4">
<h4 class="anchored" data-anchor-id="step-2-load-the-data">Step 2: Load the data</h4>
<section id="task-3-read-in-the-data-files-we-will-be-using" class="level5">
<h5 class="anchored" data-anchor-id="task-3-read-in-the-data-files-we-will-be-using">Task 3 – Read in the data files we will be using</h5>
<p>The data files are called:</p>
<ul>
<li><code>study-two-general-participants.csv</code></li>
<li><code>2023-24_PSYC122-participants.csv</code></li>
</ul>
<p>Use the <code>read_csv()</code> function to read the data files into R:</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- study.two.gen <- read_csv("study-two-general-participants.csv")   -->
<!-- study.122 <- read_csv("2023-24_PSYC122-participants.csv")   -->
<!-- ``` -->
<!-- ::: -->
<p>When you read the data files in, give the data objects you create distinct name e.g.&nbsp;<code>study.two.gen</code> versus <code>study.122</code>.</p>
</section>
<section id="task-4-inspect-the-data-file" class="level5">
<h5 class="anchored" data-anchor-id="task-4-inspect-the-data-file">Task 4 – Inspect the data file</h5>
<p>Use the <code>summary()</code> or <code>head()</code> functions to take a look at both datasets.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- summary(study.two.gen) -->
<!-- summary(study.122) -->
<!-- ``` -->
<!-- ::: -->
</section>
</section>
<section id="step-3-compare-the-data-from-the-different-studies" class="level4">
<h4 class="anchored" data-anchor-id="step-3-compare-the-data-from-the-different-studies">Step 3: Compare the data from the different studies</h4>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Revise: practice to strengthen skills
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<section id="task-5-compare-the-data-distributions-from-the-two-studies" class="level5">
<h5 class="anchored" data-anchor-id="task-5-compare-the-data-distributions-from-the-two-studies">Task 5 – Compare the data distributions from the two studies</h5>
</section>
<section id="questions-task-5" class="level5">
<h5 class="anchored" data-anchor-id="questions-task-5">Questions: Task 5</h5>
<blockquote class="blockquote">
<p><strong>Q.1.</strong> What is the mean of the <code>mean.acc</code> and <code>SHIPLEY</code> variables in the two studies?</p>
</blockquote>
<!-- - A.1. The means are: -->
<!-- - study two -- `mean.acc`: mean = 0.7596 -->
<!-- - study two -- `SHIPLEY`: mean = 35.13 -->
<!-- - study PSYC122 -- `mean.acc`: mean = 0.8231 -->
<!-- - study PSYC122 -- `SHIPLEY`: mean = 32.31 -->
<blockquote class="blockquote">
<p><strong>Q.2.</strong> Draw histograms of both mean.acc and mean.self for both studies.</p>
</blockquote>
<!-- - A.2. You can write the code using the same code structure you have been shown e.g. in `2023-24-PSYC122-w19-how-to.Rmd` but changing dataset and variable names to get the right plots: -->
<!-- ```{r} -->
<!-- ggplot(data = study.two.gen, aes(x = mean.acc)) +  -->
<!--   geom_histogram(binwidth = .1) + -->
<!--   theme_bw() + -->
<!--   labs(x = "Mean accuracy (mean.acc)", y = "frequency count") + -->
<!--   xlim(0, 1) -->
<!-- ggplot(data = study.two.gen, aes(x = SHIPLEY)) +  -->
<!--   geom_histogram(binwidth = 2) + -->
<!--   theme_bw() + -->
<!--   labs(x = "Vocabulary (SHIPLEY)", y = "frequency count") + -->
<!--   xlim(0, 40) -->
<!-- ggplot(data = study.122, aes(x = mean.acc)) +  -->
<!--   geom_histogram(binwidth = .1) + -->
<!--   theme_bw() + -->
<!--   labs(x = "Mean accuracy (mean.acc)", y = "frequency count") + -->
<!--   xlim(0, 1) -->
<!-- ggplot(data = study.122, aes(x = SHIPLEY)) +  -->
<!--   geom_histogram(binwidth = 2) + -->
<!--   theme_bw() + -->
<!--   labs(x = "Vocabulary (SHIPLEY)", y = "frequency count") + -->
<!--   xlim(0, 40) -->
<!-- ``` -->
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Introduce: make some new moves
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
</section>
<section id="task-6-create-grids-of-plots-to-make-the-comparison-easier-to-do" class="level5">
<h5 class="anchored" data-anchor-id="task-6-create-grids-of-plots-to-make-the-comparison-easier-to-do">Task 6 – Create grids of plots to make the comparison easier to do</h5>
<blockquote class="blockquote">
<p>Hint: Task 6 – What we are going to do is to create two histograms of <code>mean.acc</code> (one plot for each study dataset) and then present the plots side by side to allow easy comparison of variable distributions</p>
</blockquote>
<p>We need to make two changes to the coding approach you have been using until now.</p>
<ul>
<li>Remember, you can find what you need to do in <code>2023-24-PSYC122-w19-how-to.Rmd</code>.</li>
</ul>
<p>First, create plot objects, assign the plot objects distinct names.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- plot.two <- ggplot(data = study.two.gen, aes(x = mean.acc)) +  -->
<!--   geom_histogram(binwidth = .1) + -->
<!--   theme_bw() + -->
<!--   labs(x = "Mean accuracy (mean.acc)", y = "frequency count", title = "Study Two") + -->
<!--   xlim(0, 1) -->
<!-- plot.122 <- ggplot(data = study.122, aes(x = mean.acc)) +  -->
<!--   geom_histogram(binwidth = .1) + -->
<!--   theme_bw() + -->
<!--   labs(x = "Mean accuracy (mean.acc)", y = "frequency count", title = "Study PSYC122") + -->
<!--   xlim(0, 1) -->
<!-- ``` -->
<!-- ::: -->
<p>Second, name the plots to show them side-by-side.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- plot.two + plot.122 -->
<!-- ``` -->
<!-- ::: -->
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This is what you need to: check out the process, step-by-step.</p>
<ul>
<li>Notice that you repeat the process for each of two (or more) plots.</li>
</ul>
<ol type="1">
<li><code>ggplot(...)</code> tell R you want to make a plot using the <code>ggplot()</code> function;</li>
<li><code>plot.one &lt;-</code> tell R you want to give the plot a name; the name appears in the environment;</li>
<li><code>ggplot(data = study.two.gen ...)</code> tell R you want to make a plot with the <code>study.two</code> data;</li>
<li><code>ggplot(..., aes(x = mean.acc))</code> tell R that you want to make a plot with the variable <code>mean.acc</code>;</li>
</ol>
<ul>
<li>here, specify the aesthetic mapping, <code>x = mean.acc</code></li>
</ul>
<ol start="5" type="1">
<li><code>geom_histogram()</code> tell R you want to plot values of <code>mean.acc</code> as a histogram;</li>
<li><code>binwidth = .1</code> adjust the binwidth to show enough detail but not too much in the distribution;</li>
<li><code>theme_bw()</code> tell R what theme you want, adjusting the plot appearance;</li>
<li><code>labs(x = "Mean accuracy (mean.acc)", y = "frequency count", title = "Study Two")</code> fix the x-axis and y-axis labels;</li>
</ol>
<ul>
<li>here, add a title for the plot, so you can tell the two plots apart;</li>
</ul>
<ol start="9" type="1">
<li><code>xlim(0, 1)</code> adjust the x-axis limits to show the full range of possible score values on this variable.</li>
</ol>
<p>Do this process twice, once for each dataset, creating two plots so that you can compare the distribution of <code>mean.acc</code> scores between the studies.</p>
<p>Finally, having created the two plots, produce them for viewing:</p>
<ol start="10" type="1">
<li><code>plot.two + plot.122</code> having constructed – and named – both plots, you enter their names, separated by a +, to show them in a grid of two plots.</li>
</ol>
<p>Notice: until you get to step 10, <strong>nothing will appear</strong>. This will be <strong>surprising</strong> but it is perfectly normal when we increase the <em>level of complexity</em> of the plots we build.</p>
</div>
</div>
</div>
<!-- - You first build the plots.  -->
<!-- - You are creating plot objects and you give these objects names. -->
<!-- - The objects will appear in the `Environment` with the names you give them. -->
<!-- - You then *produce* the plots for viewing, by using their names. -->
<!-- Until you complete the last step, you will not see any changes until you use the object names to produce them for viewing. -->
<!-- This is how you construct complex arrays of plots.  -->
</section>
<section id="task-7-try-this-out-for-yourself-focusing-now-on-the-distribution-of-shipley-scores-in-the-two-studies" class="level5">
<h5 class="anchored" data-anchor-id="task-7-try-this-out-for-yourself-focusing-now-on-the-distribution-of-shipley-scores-in-the-two-studies">Task 7 – Try this out for yourself, focusing now on the distribution of <code>SHIPLEY</code> scores in the two studies</h5>
<p>First, create plot objects but do not show them.</p>
<ul>
<li>Give each plot a name. You will use the names next.</li>
</ul>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- plot.two <- ggplot(data = study.two.gen, aes(x = SHIPLEY)) +  -->
<!--   geom_histogram(binwidth = 2) + -->
<!--   theme_bw() + -->
<!--   labs(x = "Vocabulary (SHIPLEY)", y = "frequency count", title = "Study Two") + -->
<!--   xlim(0, 40) -->
<!-- plot.122 <- ggplot(data = study.122, aes(x = SHIPLEY)) +  -->
<!--   geom_histogram(binwidth = 2) + -->
<!--   theme_bw() + -->
<!--   labs(x = "Vocabulary (SHIPLEY)", y = "frequency count", title = "PSYC122") + -->
<!--   xlim(0, 40) -->
<!-- ``` -->
<!-- ::: -->
<p>Second produce the plots for viewing, side-by-side, by <em>naming</em> them: <code>plot.1.name + plot.2.name</code>.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- plot.two + plot.122 -->
<!-- ``` -->
<!-- ::: -->
<blockquote class="blockquote">
<p><strong>Q.3.</strong> Now use the plots to do some data analysis work: how do the <code>SHIPLEY</code> distributions compare, when you compare the <code>SHIPLEY</code> of <code>study.two.gen</code> versus <code>SHIPLEY</code> of <code>study.122</code>?</p>
</blockquote>
<!-- - A.3. When you compare the plots side-by-side you can see that the `SHIPLEY` distributions are *mostly* similar: most people have high `SHIPLEY` scores. -->
<!-- But you can also see striking differences:  -->
<!-- - The peak of the distribution -- where the tallest bar is -- is at a higher `SHIPLEY` score in `study.two.gen` (around `SHIPLEY` = 37-38) than in `study.122` (where is it around `SHIPLEY` = 30). -->
<!-- - There appear to be *fewer* participants with lower `SHIPLEY` scores in `study.122` than in `study.two`. -->
<blockquote class="blockquote">
<p><strong>Q.4.</strong> Is the visual impression you get from comparing the distributions consistent with the statistics you see in the summary?</p>
</blockquote>
<!-- - A.4. Yes: If you go back to the summary of `SHIPLEY`, comparing the two studies datasets, then you can see that the median and mean are higher in `study.122` than in `study.two.gen`. -->
</section>
</section>
<section id="step-4-now-use-scatterplots-and-correlation-to-examine-associations-between-variables" class="level4">
<h4 class="anchored" data-anchor-id="step-4-now-use-scatterplots-and-correlation-to-examine-associations-between-variables">Step 4: Now use scatterplots and correlation to examine associations between variables</h4>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Revise: practice to strengthen skills
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<section id="task-8-draw-scatterplots-to-compare-the-potential-association-between-mean.acc-and-mean.self-in-both-study.two.gen-and-study.122-datasets" class="level5">
<h5 class="anchored" data-anchor-id="task-8-draw-scatterplots-to-compare-the-potential-association-between-mean.acc-and-mean.self-in-both-study.two.gen-and-study.122-datasets">Task 8 – Draw scatterplots to compare the potential association between <code>mean.acc</code> and <code>mean.self</code> in both <code>study.two.gen</code> and <code>study.122</code> datasets</h5>
<blockquote class="blockquote">
<p>Hint: Task 8 – The plotting steps are explained in some detail in <code>2023-24-PSYC122-w17-how-to.Rmd</code> and you can see example code in <code>2023-24-PSYC122-w19-how-to.Rmd</code></p>
</blockquote>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r}   -->
<!-- ggplot(data = study.two.gen, aes(x = mean.self, y = mean.acc)) + -->
<!--   geom_point(alpha = 0.75, size = 3, colour = "darkgrey") + -->
<!--   geom_smooth(method = "lm", size = 1.5, colour = "green") + -->
<!--   theme_bw() + -->
<!--   labs(x = "mean self-rated accuracy", y = "mean accuracy") + -->
<!--   xlim(0, 10) + ylim(0, 1) -->
<!-- ggplot(data = study.122, aes(x = mean.self, y = mean.acc)) + -->
<!--   geom_point(alpha = 0.75, size = 3, colour = "darkgrey") + -->
<!--   geom_smooth(method = "lm", size = 1.5, colour = "green") + -->
<!--   theme_bw() + -->
<!--   labs(x = "mean self-rated accuracy", y = "mean accuracy") + -->
<!--   xlim(0, 10) + ylim(0, 1) -->
<!-- ``` -->
<!-- ::: -->
</section>
<section id="task-9-create-a-grid-of-plots-to-make-the-comparison-easier-to-do" class="level5">
<h5 class="anchored" data-anchor-id="task-9-create-a-grid-of-plots-to-make-the-comparison-easier-to-do">Task 9 – Create a grid of plots to make the comparison easier to do</h5>
<blockquote class="blockquote">
<p>Hint: Task 9 – We follow the same steps as we used in tasks 6 and 7 to create the plots</p>
</blockquote>
<p>We again:</p>
<ol type="1">
<li>First construct the plot objects and give them names;</li>
<li>create and show a grid of named plots.</li>
</ol>
<p>Though this time we are producing a grid of <strong>scatterplots</strong>.</p>
<p>First, create plot objects, give them names, but do not show them.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- plot.two <- ggplot(data = study.two.gen, aes(x = mean.self, y = mean.acc)) + -->
<!--   geom_point(alpha = 0.75, size = 3, colour = "darkgrey") + -->
<!--   geom_smooth(method = "lm", size = 1.5, colour = "green") + -->
<!--   theme_bw() + -->
<!--   labs(x = "mean self-rated accuracy", y = "mean accuracy") + -->
<!--   xlim(0, 10) + ylim(0, 1) -->
<!-- plot.122 <- ggplot(data = study.122, aes(x = mean.self, y = mean.acc)) + -->
<!--   geom_point(alpha = 0.75, size = 3, colour = "darkgrey") + -->
<!--   geom_smooth(method = "lm", size = 1.5, colour = "green") + -->
<!--   theme_bw() + -->
<!--   labs(x = "mean self-rated accuracy", y = "mean accuracy") + -->
<!--   xlim(0, 10) + ylim(0, 1) -->
<!-- ``` -->
<!-- ::: -->
<p>Second name the plots to show them side-by-side in the plot window.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- plot.two + plot.122 -->
<!-- ``` -->
<!-- ::: -->
<p>Now use the plots to make comparison judgments.</p>
<blockquote class="blockquote">
<p><strong>Q.5.</strong> How does the association, shown in the plots, between <code>mean.self</code> and <code>mean.acc</code> compare when you look at the <code>study.two.gen</code> versus the <code>study.122</code> plot? <strong>hint: Q.5.</strong> When comparing evidence about associations in different studies, we are mostly going to focus on the slope – the angle – of the prediction lines, and the ways in which points do or do not cluster about the prediction lines.</p>
</blockquote>
<!-- - A.5. If you examine the `study.two.gen` versus the `study.122` plots then you can see that in both plots higher `mean.self` scores appear to be associated with higher `mean.acc` scores. But the trend maybe is a bit stronger -- the line is steeper -- in `study.two`. -->
<p>We are now in a position to answer one of our research questions:</p>
<ol start="2" type="1">
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<!-- If people *can* accurately evaluate whether they correctly understand written health information then `mean.self` (a score representing their evaluation) should be associated with `mean.acc` (a score representing their accuracy of understanding) for each person. -->
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Revise: practice to strengthen skills
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
</section>
<section id="task-10-can-you-estimate-the-association-between-mean.acc-and-mean.self-in-both-datasets" class="level5">
<h5 class="anchored" data-anchor-id="task-10-can-you-estimate-the-association-between-mean.acc-and-mean.self-in-both-datasets">Task 10 – Can you estimate the association between <code>mean.acc</code> and <code>mean.self</code> in both datasets?</h5>
<blockquote class="blockquote">
<p>Hint: Task 10 – We use <code>cor.test()</code> as you have been shown how to do e.g.&nbsp;in <code>2023-24-PSYC122-w16-how-to.Rmd</code></p>
</blockquote>
<p>Do the correlation for both datasets.</p>
<p>First calculate the correlation between <code>mean.acc</code> and <code>mean.self</code> in <code>study.two</code>.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- cor.test(study.two.gen$mean.acc, study.two.gen$mean.self, method = "pearson",  alternative = "two.sided") -->
<!-- ``` -->
<!-- ::: -->
<p>Then answer the following questions.</p>
<blockquote class="blockquote">
<p><strong>Q.6.</strong> What is r, the correlation coefficient?</p>
</blockquote>
<!-- - A.6. r = 0.5460792 -->
<blockquote class="blockquote">
<p><strong>Q.7.</strong> Is the correlation significant?</p>
</blockquote>
<!-- - A.7. r is significant -->
<blockquote class="blockquote">
<p><strong>Q.8.</strong> What are the values for t and p for the significance test for the correlation?</p>
</blockquote>
<!-- - A.8. t = 8.4991, p = 9.356e-15 -->
<p>Second, look at the correlation between <code>mean.acc</code> and <code>mean.self</code> in <code>study.122</code>.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- cor.test(study.122$mean.acc, study.122$mean.self, method = "pearson",  alternative = "two.sided") -->
<!-- ``` -->
<!-- ::: -->
<p>Then answer the following questions.</p>
<blockquote class="blockquote">
<p><strong>Q.9.</strong> What is r, the correlation coefficient?</p>
</blockquote>
<!-- - A.9. r = 0.4027438 -->
<blockquote class="blockquote">
<p><strong>Q.10.</strong> Is the correlation significant?</p>
</blockquote>
<!-- - A.10. r is significant -->
<blockquote class="blockquote">
<p><strong>Q.11.</strong> What are the values for t and p for the significance test for the correlation?</p>
</blockquote>
<!-- - A.11. t = 3.4924, p = 0.0008808 -->
<p>Now we can answer the research question:</p>
<ol start="2" type="1">
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<blockquote class="blockquote">
<p><strong>Q.12.</strong> What do the correlation estimates tell you is the answer to the research question?</p>
</blockquote>
<!-- - A.12.  -->
<!-- > The correlations are positive and significant, indicating that higher `mean.self` (evaluations) are associated with higher `mean.acc` (understanding), suggesting that people *can* judge their accuracy of understanding. -->
<blockquote class="blockquote">
<p><strong>Q.13.</strong> Can you compare the estimates, given the two datasets, to evaluate if the result in <code>study.two.gen</code> is <em>replicated</em> in <code>study.122</code>? <strong>hint: Q.13.</strong> We can judge if the result in a study is replicated in another study by examining if – here – the correlation coefficient is significant in both studies <em>and</em> if the coefficient has the same size and sign in both studies.</p>
</blockquote>
<!-- - A.13. If you compare the correlation estimates from both `study.two.gen` and `study.122` you can see: -->
<!-- - first, the correlation is significant in both `study.two.gen` and `study.122`; -->
<!-- - second, the correlation is positive in both studies. -->
<!-- But, if you compare the correlation estimates, you can see that the coefficient estimate is smaller in `study.122` (where r = .40) than in `study.two.gen` (where r = .55). -->
<!-- This may suggest that the association observed in `study.two.gen` is different from the association in `study.122`, for some reason. -->
</section>
<section id="task-11-in-working-with-r-to-do-data-analysis-we-often-work-with-libraries-of-function-like-tidyverse-that-enable-us-to-do-things-see-the-week-19-lecture-for-discussion." class="level5">
<h5 class="anchored" data-anchor-id="task-11-in-working-with-r-to-do-data-analysis-we-often-work-with-libraries-of-function-like-tidyverse-that-enable-us-to-do-things-see-the-week-19-lecture-for-discussion.">Task 11 – In working with R to do data analysis, we often work with libraries of function like <code>{tidyverse}</code> that enable us to do things (see the week 19 lecture for discussion).</h5>
<p>In this way, we are using the <code>{patchwork}</code> library so that we can create plots and then present them in a grid.</p>
<p>Can you find the online information about <code>{patchwork}</code> and use it to adjust the layout of the grids of plots you are using?</p>
<blockquote class="blockquote">
<p>Hint: Task 11 – To find out more information about a function or a library in R, do a search for the keywords</p>
</blockquote>
<p>You can do a search, using any search engine (e.g., Bing, Chrome, Google), by entering:</p>
<blockquote class="blockquote">
<p><code>in r ...</code></p>
</blockquote>
<p>And pasting the words you want to know about to replace the <code>...</code> e.g.&nbsp;“in r patchwork”.</p>
<p>You will then see a list of results including the link to the <code>{patchwork}</code> information:</p>
<p><a href="https://patchwork.data-imaginist.com" class="uri">https://patchwork.data-imaginist.com</a></p>
</section>
</section>
<section id="step-5-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" class="level4">
<h4 class="anchored" data-anchor-id="step-5-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors">Step 5: Use a linear model to to answer the research questions – multiple predictors</h4>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Revise: practice to strengthen skills
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<section id="task-12-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors" class="level5">
<h5 class="anchored" data-anchor-id="task-12-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors">Task 12 – Examine the relation between outcome mean accuracy (<code>mean.acc</code>) and multiple predictors</h5>
<blockquote class="blockquote">
<p>Hint: Task 12 – We use <code>lm()</code>, as we have been doing before, see e.g.&nbsp;<code>2023-24-PSYC122-w18-how-to.R</code></p>
</blockquote>
<blockquote class="blockquote">
<p>Examine the predictors of mean accuracy (<code>mean.acc</code>), first, for the <code>study.two.gen</code> data.</p>
</blockquote>
<p>We specify a linear model of the <code>study.two.gen</code> data, including as the outcome:</p>
<ul>
<li>mean accuracy (<code>mean.acc</code>)</li>
</ul>
<p>and including as the predictors the variables:</p>
<ul>
<li>health literacy (<code>HLVA</code>);</li>
<li>vocabulary (<code>SHIPLEY</code>);</li>
<li>reading strategy (<code>FACTOR3</code>).</li>
</ul>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- model <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.two.gen) -->
<!-- summary(model) -->
<!-- ``` -->
<!-- ::: -->
<p>Using the model estimates, we can answer the research question:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<p>Inspect the model summary to then answer the following questions:</p>
<blockquote class="blockquote">
<p><strong>Q.14.</strong> What is the estimate for the coefficient of the effect of the predictor <code>SHIPLEY</code> in <em>this</em> model?</p>
</blockquote>
<!-- - A.14. 0.008397  -->
<blockquote class="blockquote">
<p><strong>Q.15.</strong> Is the effect significant?</p>
</blockquote>
<!-- - A.15. It is significant, p < .05 -->
<blockquote class="blockquote">
<p><strong>Q.16.</strong> What are the values for t and p for the significance test for the coefficient?</p>
</blockquote>
<!-- - A.16. t = 4.533, p = 1.1e-05 -->
<blockquote class="blockquote">
<p><strong>Q.17.</strong> Now consider the estimates for all the variables, what do you conclude is the answer to the research question – given the <code>study.two.gen</code> data:</p>
</blockquote>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<blockquote class="blockquote">
<p><strong>hint: Q.17.</strong> Can you report the model and the model fit statistics using the language you have been shown in the week 18 lecture?</p>
</blockquote>
<!-- - A.17.  -->
<!-- > We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (`HLVA`),  reading strategy (`FACTOR3`), and vocabulary (`SHIPLEY`) as predictors. The model is significant overall, with F(3, 168) = 31.99, p< .001, and explains 35% of variance (adjusted R2 = 0.35). Mean accuracy was predicted to be higher given higher scores in health literacy (`HLVA` estimate = .018, t = 4.90, p < .001), vocabulary knowledge (`SHIPLEY` estimate = .008, t = 4.53, p < .001), and reading strategy (`FACTOR3` estimate = .003, t = 2.68, p = .008). -->
</section>
</section>
</section>
<section id="task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data" class="level3">
<h3 class="anchored" data-anchor-id="task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data">Task 13 – Examine the predictors of mean accuracy (<code>mean.acc</code>), now, for the <code>study.122</code> data</h3>
<blockquote class="blockquote">
<p>Examine the predictors of mean accuracy (<code>mean.acc</code>), second, for the <code>study.122</code> data.</p>
</blockquote>
<p>We specify a linear model of the <code>study.122</code> data, including as the outcome:</p>
<ul>
<li>mean accuracy (<code>mean.acc</code>)</li>
</ul>
<p>and including as the predictors the variables:</p>
<ul>
<li>health literacy (<code>HLVA</code>);</li>
<li>vocabulary (<code>SHIPLEY</code>);</li>
<li>reading strategy (<code>FACTOR3</code>).</li>
</ul>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- model <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.122) -->
<!-- summary(model) -->
<!-- ``` -->
<!-- ::: -->
<p>Using the model estimates, we can answer the research question:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<p>Inspect the model summary, then answer the following questions:</p>
<blockquote class="blockquote">
<p><strong>Q.18.</strong> What is the estimate for the coefficient of the effect of the predictor, <code>HLVA</code>, in <em>this</em> model?</p>
</blockquote>
<!-- - A.18. 0.0335342  -->
<blockquote class="blockquote">
<p><strong>Q.19.</strong> Is the effect significant?</p>
</blockquote>
<!-- - A.19. It is significant, p > .05 because p = 1.52e-05 -->
<blockquote class="blockquote">
<p><strong>Q.20.</strong> What are the values for t and p for the significance test for the coefficient?</p>
</blockquote>
<!-- - A.20. t = 4.701, p < .001 -->
<blockquote class="blockquote">
<p><strong>Q.21.</strong> Now consider the estimates for all the variables, what do you conclude is the answer to the research question – given the <code>study.122</code> data:</p>
</blockquote>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<blockquote class="blockquote">
<p><strong>hint: Q.21.</strong> Can you report the model and the model fit statistics using the language you have been shown in the week 18 lecture?</p>
</blockquote>
<!-- - A.21.  -->
<!-- > We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (`HLVA`),  reading strategy (`FACTOR3`), and vocabulary (`SHIPLEY)` as predictors. The model is significant overall, with F(3, 61) = 14.47, p < .001, and explains 39% of variance (adjusted R2 = .387). Mean accuracy was predicted to be higher given higher scores in health literacy (`HLVA` estimate = .034, t = 4.70, p < .001). There were non-significant effects of individual differences in vocabulary knowledge (`SHIPLEY` estimate = .006, t = 1.80, p = .077) and reading strategy (`FACTOR3` estimate = .001, t = .25, p = .800).  -->
<p>At this point, we can evaluate the evidence from the PSYC122 sample – based on your responses – to assess if the patterns, the estimates, we saw previously are repeated in analyses of PSYC122 responses.</p>
<blockquote class="blockquote">
<p><strong>Q.22.</strong> Are the findings from <code>study.two.gen</code> replicated in <code>study.122</code>?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>hint: Q.22.</strong> We can judge if the results in an earlier study are replicated in another study by examining if – here – the linear model estimates are significant in both studies <em>and</em> if the coefficient estimates have the same size and sign in both studies.</p>
</blockquote>
<!-- - A.22. If you compare the linear model coefficient estimates from both the `study.two.gen` and `study.122` models, you can see: -->
<!-- - first, that the `HLVA` effect estimate is significant in both `study.two.gen` and `study.122`; -->
<!-- - second, that the estimates of the `HLVA` effect have the same sign -- positive -- in both studies while the estimated coefficient is a bit bigger in the `study.122` data (implying a stronger effect); -->
<!-- - but, third that the estimates of the effects of variation in vocabulary knowledge (`SHIPLEY`) and reading strategy (`FACTOR3`) are significant in `study.two.gen` but not in `study.122`.   -->
<!-- This suggests that the attributes -- the set of abilities -- that predict comprehension accuracy are similar but not the same in the `study.two.gen` participants compared to `study.122` participants. -->
<blockquote class="blockquote">
<p><strong>Q.23.</strong> How would you describe the outstanding difference between the results of the two studies?</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>hint: Q.23.</strong> We can look at the estimates but we can also use model prediction plotting code to <em>visualize</em> the results. You can build on the code you used before, see:</p>
</blockquote>
<ul>
<li><code>2022-23-PSYC122-w18-how-to.R</code></li>
<li><code>2022-23-PSYC122-w19-how-to.R</code></li>
</ul>
<blockquote class="blockquote">
<p><strong>hint: Q.23.</strong> Let’s focus on comparing the <code>study.two.gen</code> and <code>study.122</code> estimates for the effect of <code>HLVA</code> in both models: we can plot model predictions, for comparison:</p>
</blockquote>
<p>First: fit the models – using different names for the different models.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- model.two <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.two.gen) -->
<!-- summary(model.two) -->
<!-- model.122 <- lm(mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.122) -->
<!-- summary(model.122) -->
<!-- ``` -->
<!-- ::: -->
<p>Second, create prediction plots for the <code>HLVA</code> effect for each model.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- dat.two <- ggpredict(model.two, "HLVA") -->
<!-- plot.two <- plot(dat.two) + labs(title = "Study Two") -->
<!-- dat.122 <- ggpredict(model.122, "HLVA") -->
<!-- plot.122 <- plot(dat.122) + labs(title = "Study PSYC122") -->
<!-- ``` -->
<!-- ::: -->
<p>Third, show the plots side-by-side:</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- plot.two + plot.122 -->
<!-- ``` -->
<!-- ::: -->
<p>Then use your <em>visualization</em> of the model results to describe the outstanding difference between the results of the two studies – focusing on the effect of <code>HLVA</code> in both models.</p>
<!-- - A.23. If we compare the estimates for the coefficient of the `HLVA` effect in the `study.two.gen` and `study.122` models we can see that: -->
<!-- 1. The health literacy `HLVA` effect is significant in both `study.two.gen` and `study.122`. -->
<!-- 2. The effect trends positive in both studies. -->
<!-- 3. The coefficient estimate is bigger in `study.122` than in `study.two.gen`. -->
<!-- 4. The prediction plots suggest the prediction line slope is steeper in `study.122`. -->
<!-- 5. The grey shaded area around the trend line (indicating our uncertainty about the estimated trend) is wider for `study.two.gen` than for `study.122`, suggesting we are more uncertain about the association for the `study.two.gen` data.  -->
<!-- - The breadth of the grey shaded area around the trend line is hard to compare between the two plots. You have to look carefully at the y-axis scale information to make a judgment about the relative width of these uncertainty ellipses. -->
<!-- The visualizations plus the model summaries suggests that the estimates of the effect of health literacy are different in the `study.122` compared to the `study.two.gen` data. Why is that? -->
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>We can redraw the prediction plots – next – to add in more information about our samples. This change, see following, will help us to interpret the results of the analyses we have done.</li>
<li>And <em>that</em> will help you to see why data visualization and data analysis work well together.</li>
</ul>
</div>
</div>
<section id="task-14-in-producing-prediction-plots-we-are-using-functions-from-the-ggefects-library.-can-you-locate-online-information-about-working-with-the-library-functions" class="level5">
<h5 class="anchored" data-anchor-id="task-14-in-producing-prediction-plots-we-are-using-functions-from-the-ggefects-library.-can-you-locate-online-information-about-working-with-the-library-functions">Task 14 – In producing prediction plots, we are using functions from the <code>{ggefects}</code> library. Can you locate online information about working with the library functions?</h5>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hint
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Try doing a search with the key words: <code>in r ggeffects</code>.</p>
<p>If you do that, you will see links to the website:</p>
<p><a href="https://strengejacke.github.io/ggeffects/" class="uri">https://strengejacke.github.io/ggeffects/</a></p>
</div>
</div>
</div>
</section>
<section id="task-15-in-the-ggeffects-online-information-you-can-see-links-to-practical-examples.-can-you-use-the-information-under-practical-examples-to-adjust-the-appearance-of-the-prediction-plots-to-make-them-black-and-white-to-add-points" class="level4">
<h4 class="anchored" data-anchor-id="task-15-in-the-ggeffects-online-information-you-can-see-links-to-practical-examples.-can-you-use-the-information-under-practical-examples-to-adjust-the-appearance-of-the-prediction-plots-to-make-them-black-and-white-to-add-points">Task 15 – In the <code>{ggeffects}</code> online information, you can see links to practical examples. Can you use the information under <code>Practical examples</code> to adjust the appearance of the prediction plots: to make them black and white; to add points?</h4>
<p>First create the plots.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- dat.two <- ggpredict(model.two, "HLVA") -->
<!-- plot.two <- plot(dat.two, colors = "bw", add.data = TRUE) + labs(title = "Study Two") -->
<!-- dat.122 <- ggpredict(model.122, "HLVA") -->
<!-- plot.122 <- plot(dat.122, colors = "bw", add.data = TRUE) + labs(title = "Study PSYC122") -->
<!-- ``` -->
<!-- ::: -->
<p>Then show the plots in a grid, to allow comparison of the effect of <code>HLVA</code> between studies in a <em>professional</em> presentation.</p>
<!-- :::{.callout-tip collapse="true"} -->
<!-- ## Code -->
<!-- ```{r} -->
<!-- plot.two + plot.122 -->
<!-- ``` -->
<!-- ::: -->
<div class="calloutbox-tip">
<p>It is often useful to compare model estimates – here, the slopes – with the raw data observations.</p>
<ul>
<li>No model will be perfect.</li>
<li>Visualizing the difference between what we observe and what we predict helps to make sense of how our prediction model could be improved.</li>
</ul>
</div>
<blockquote class="blockquote">
<p><strong>Q.24.</strong> Given the information in the adjusted plots, can you explain why we appear to be more uncertain about the <code>HLVA</code> effect given the <code>study.122</code> data?</p>
</blockquote>
<!-- - A.24. Adding points allow us to see: -->
<!-- 1. There are far fewer observations in the `study.122` dataset than in the `study.two.gen` data: this means that our estimate of the effect will be *more uncertain* because we have *less information* when we look at the `study.122` data. -->
<!-- 2. But it is also clear that the effect of `HLVA` appears to be stronger in the  `study.122` data because observed scores are *closer* to model predictions: the `HLVA` effect *explains more variation* in the `study.122` data than in the `study.two.gen` data. -->
</section>
<section id="you-have-now-completed-the-week-19-questions." class="level4">
<h4 class="anchored" data-anchor-id="you-have-now-completed-the-week-19-questions.">You have now completed the Week 19 questions.</h4>
<p>You have now extended your capacity to <em>think critically</em> about our data and our capacity to predict people and their behaviour.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>We have used PSYC122 students’ responses to examine the robustness of evidence for potential answers to our research questions.</li>
<li>Examining evidence across multiple different studies is a key element part of the process of <em>building</em> insights in psychological science.</li>
</ul>
</div>
</div>
</section>
</section>
</section>
<section id="sec-wk19-lab-activities-answers" class="level2">
<h2 class="anchored" data-anchor-id="sec-wk19-lab-activities-answers">Answers</h2>
<p>When you have completed all of the lab content, you may want to check your answers with our completed version of the script for this week.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>.Rmd</code> script containing all code and all answers for each task and each question will be made available after the final lab session has taken place.</p>
<ul>
<li><p>You can download the script by clicking on the link: <a href="../PSYC122/data/week19/2023-24-PSYC122-w19-workbook-answers.html">2023-24-PSYC122-w19-workbook-answers.Rmd</a>.</p></li>
<li><p>Or by copying the code into the R <code>Console</code> window and running it to get the <code>2023-24-PSYC122-w19-workbook-answers.Rmd</code> loaded directly into R:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">"https://github.com/lu-psy-r/statistics_for_psychologists/blob/main/PSYC122/data/week19/2023-24-PSYC122-w19-workbook-answers.Rmd?raw=true"</span>, <span class="at">destfile =</span> <span class="st">"2023-24-PSYC122-w19-workbook-answers.Rmd"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>We set out answers information the Week 19 <strong>Critical perspectives</strong> questions, below.</p>
<ul>
<li>We focus on the <strong>Lab activity 2</strong> questions where we ask you to interpret something or say something.</li>
<li>We do not show questions where we have given example or target code in the foregoing lab activity <a href="#sec-wk19-lab-activities-2">Section&nbsp;5.4</a>.</li>
</ul>
<p>You can see all the code and all the answers in <code>2023-24-PSYC122-w19-workbook-answers.Rmd</code>.</p>
<section id="sec-wk19-lab-activities-answers-information" class="level3">
<h3 class="anchored" data-anchor-id="sec-wk19-lab-activities-answers-information">Answers</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Click on a box to reveal the answer.</p>
</div>
</div>
<section id="sec-wk19-lab-activities-2-questions-answers" class="level4">
<h4 class="anchored" data-anchor-id="sec-wk19-lab-activities-2-questions-answers">Questions</h4>
<blockquote class="blockquote">
<p><strong>Q.1.</strong> What is the mean of the <code>mean.acc</code> and <code>SHIPLEY</code> variables in the two studies?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>A.1. The means are:</p></li>
<li><p>study two – <code>mean.acc</code>: mean = 0.7596</p></li>
<li><p>study two – <code>SHIPLEY</code>: mean = 35.13</p></li>
<li><p>study PSYC122 – <code>mean.acc</code>: mean = 0.8231</p></li>
<li><p>study PSYC122 – <code>SHIPLEY</code>: mean = 32.31</p></li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.2.</strong> Draw histograms of both mean.acc and mean.self for both studies.</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.2. You can write the code using the same code structure you have been shown e.g.&nbsp;in <code>2023-24-PSYC122-w19-how-to.Rmd</code> but changing dataset and variable names to get the right plots:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study.two.gen, <span class="fu">aes</span>(<span class="at">x =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mean accuracy (mean.acc)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Week19_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study.two.gen, <span class="fu">aes</span>(<span class="at">x =</span> SHIPLEY)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vocabulary (SHIPLEY)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Week19_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study<span class="fl">.122</span>, <span class="fu">aes</span>(<span class="at">x =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mean accuracy (mean.acc)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Week19_files/figure-html/unnamed-chunk-9-3.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study<span class="fl">.122</span>, <span class="fu">aes</span>(<span class="at">x =</span> SHIPLEY)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vocabulary (SHIPLEY)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values (`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Week19_files/figure-html/unnamed-chunk-9-4.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<p>Create histograms to enable you to compare the distribution of <code>SHIPLEY</code> scores in the <code>study.two.gen</code> and the <code>study.122</code> studies</p>
<ul>
<li>First, create plot objects but do not show them.</li>
<li>Second produce the plots for viewing, side-by-side, by <em>naming</em> them: <code>plot.1.name + plot.2.name</code>.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Q.3.</strong> Now use the plots to do some data analysis work: how do the <code>SHIPLEY</code> distributions compare, when you compare the <code>SHIPLEY</code> of <code>study.two.gen</code> versus <code>SHIPLEY</code> of <code>study.122</code>?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.3. When you compare the plots side-by-side you can see that the <code>SHIPLEY</code> distributions are <em>mostly</em> similar: most people have high <code>SHIPLEY</code> scores.</li>
</ul>
<p>But you can also see striking differences:</p>
<ul>
<li>The peak of the distribution – where the tallest bar is – is at a higher <code>SHIPLEY</code> score in <code>study.two.gen</code> (around <code>SHIPLEY</code> = 37-38) than in <code>study.122</code> (where is it around <code>SHIPLEY</code> = 30).</li>
<li>There appear to be <em>fewer</em> participants with lower <code>SHIPLEY</code> scores in <code>study.122</code> than in <code>study.two</code>.</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.4.</strong> Is the visual impression you get from comparing the distributions consistent with the statistics you see in the summary?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.4. Yes: If you go back to the summary of <code>SHIPLEY</code>, comparing the two studies datasets, then you can see that the median and mean are higher in <code>study.122</code> than in <code>study.two.gen</code>.</li>
</ul>
</div>
</div>
</div>
<p>Draw scatterplots to compare the potential association between <code>mean.acc</code> and <code>mean.self</code> in both the <code>study.two.gen</code> and the <code>study.122</code> datasets.</p>
<p>We again:</p>
<ol type="1">
<li>First construct the plot objects and give them names;</li>
<li>create and show a grid of named plots.</li>
</ol>
<p>Though this time we are producing a grid of <strong>scatterplots</strong>.</p>
<p>Now use the plots to make comparison judgments.</p>
<blockquote class="blockquote">
<p><strong>Q.5.</strong> How does the association, shown in the plots, between <code>mean.self</code> and <code>mean.acc</code> compare when you look at the <code>study.two.gen</code> versus the <code>study.122</code> plot? <strong>hint: Q.5.</strong> When comparing evidence about associations in different studies, we are mostly going to focus on the slope – the angle – of the prediction lines, and the ways in which points do or do not cluster about the prediction lines.</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.5. If you examine the <code>study.two.gen</code> versus the <code>study.122</code> plots then you can see that in both plots higher <code>mean.self</code> scores appear to be associated with higher <code>mean.acc</code> scores. But the trend maybe is a bit stronger – the line is steeper – in <code>study.two</code>.</li>
</ul>
<p>We are now in a position to answer one of our research questions:</p>
<ol start="2" type="1">
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<p>If people <em>can</em> accurately evaluate whether they correctly understand written health information then <code>mean.self</code> (a score representing their evaluation) should be associated with <code>mean.acc</code> (a score representing their accuracy of understanding) for each person.</p>
</div>
</div>
</div>
<p>Can you estimate the association between <code>mean.acc</code> and <code>mean.self</code> in both datasets?</p>
<ul>
<li>We use <code>cor.test()</code> as you have been shown how to do e.g.&nbsp;in <code>2023-24-PSYC122-w16-how-to.Rmd</code>.</li>
<li>Do the correlation for both datasets.</li>
</ul>
<p>First calculate the correlation between <code>mean.acc</code> and <code>mean.self</code> in <code>study.two</code>. Then answer the following questions.</p>
<blockquote class="blockquote">
<p><strong>Q.6.</strong> What is r, the correlation coefficient?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.6. r = 0.5460792</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.7.</strong> Is the correlation significant?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-40-contents" aria-controls="callout-40" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-40" class="callout-40-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.7. r is significant</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.8.</strong> What are the values for t and p for the significance test for the correlation?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-41-contents" aria-controls="callout-41" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-41" class="callout-41-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.8. t = 8.4991, p = 9.356e-15</li>
</ul>
</div>
</div>
</div>
<p>Second, use the same method to calculate the correlation between <code>mean.acc</code> and <code>mean.self</code> in <code>study.122</code>. Then answer the following questions.</p>
<blockquote class="blockquote">
<p><strong>Q.9.</strong> What is r, the correlation coefficient?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-42-contents" aria-controls="callout-42" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-42" class="callout-42-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.9. r = 0.4027438</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.10.</strong> Is the correlation significant?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.10. r is significant</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.11.</strong> What are the values for t and p for the significance test for the correlation?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-44-contents" aria-controls="callout-44" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-44" class="callout-44-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.11. t = 3.4924, p = 0.0008808</li>
</ul>
</div>
</div>
</div>
<p>Now we can answer the research question:</p>
<ol start="2" type="1">
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<blockquote class="blockquote">
<p><strong>Q.12.</strong> What do the correlation estimates tell you is the answer to the research question?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-45-contents" aria-controls="callout-45" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-45" class="callout-45-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.12.</li>
</ul>
<blockquote class="blockquote">
<p>The correlations are positive and significant, indicating that higher <code>mean.self</code> (evaluations) are associated with higher <code>mean.acc</code> (understanding), suggesting that people <em>can</em> judge their accuracy of understanding.</p>
</blockquote>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.13.</strong> Can you compare the estimates, given the two datasets, to evaluate if the result in <code>study.two.gen</code> is <em>replicated</em> in <code>study.122</code>? <strong>hint: Q.13.</strong> We can judge if the result in a study is replicated in another study by examining if – here – the correlation coefficient is significant in both studies <em>and</em> if the coefficient has the same size and sign in both studies.</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-46-contents" aria-controls="callout-46" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-46" class="callout-46-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>A.13. If you compare the correlation estimates from both <code>study.two.gen</code> and <code>study.122</code> you can see:</p></li>
<li><p>first, the correlation is significant in both <code>study.two.gen</code> and <code>study.122</code>;</p></li>
<li><p>second, the correlation is positive in both studies.</p></li>
</ul>
<p>But, if you compare the correlation estimates, you can see that the coefficient estimate is smaller in <code>study.122</code> (where r = .40) than in <code>study.two.gen</code> (where r = .55).</p>
<p>This may suggest that the association observed in <code>study.two.gen</code> is different from the association in <code>study.122</code>, for some reason.</p>
</div>
</div>
</div>
<p>Examine the relation between outcome mean accuracy (<code>mean.acc</code>) and multiple predictors.</p>
<p>We use <code>lm()</code>, as we have been doing before, see e.g.&nbsp;<code>2023-24-PSYC122-w18-how-to.R</code></p>
<p>Examine the predictors of mean accuracy (<code>mean.acc</code>), first, for the <code>study.two.gen</code> data.</p>
<p>We specify a linear model of the <code>study.two.gen</code> data, including as the outcome:</p>
<ul>
<li>mean accuracy (<code>mean.acc</code>)</li>
</ul>
<p>and including as the predictors the variables:</p>
<ul>
<li>health literacy (<code>HLVA</code>);</li>
<li>vocabulary (<code>SHIPLEY</code>);</li>
<li>reading strategy (<code>FACTOR3</code>).</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-47-contents" aria-controls="callout-47" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-47" class="callout-47-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study.two.gen)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.two.gen)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.242746 -0.074188  0.003173  0.075361  0.211357 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.146896   0.076325   1.925  0.05597 .  
HLVA        0.017598   0.003589   4.904  2.2e-06 ***
SHIPLEY     0.008397   0.001853   4.533  1.1e-05 ***
FACTOR3     0.003087   0.001154   2.675  0.00822 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.097 on 168 degrees of freedom
Multiple R-squared:  0.3636,    Adjusted R-squared:  0.3522 
F-statistic: 31.99 on 3 and 168 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Using the model estimates, we can answer the research question:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<p>Inspect the model summary to then answer the following questions:</p>
<blockquote class="blockquote">
<p><strong>Q.14.</strong> What is the estimate for the coefficient of the effect of the predictor <code>SHIPLEY</code> in <em>this</em> model?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-48-contents" aria-controls="callout-48" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-48" class="callout-48-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.14. 0.008397</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.15.</strong> Is the effect significant?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-49-contents" aria-controls="callout-49" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-49" class="callout-49-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.15. It is significant, p &lt; .05</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.16.</strong> What are the values for t and p for the significance test for the coefficient?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-50-contents" aria-controls="callout-50" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-50" class="callout-50-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.16. t = 4.533, p = 1.1e-05</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.17.</strong> Now consider the estimates for all the variables, what do you conclude is the answer to the research question – given the <code>study.two.gen</code> data:</p>
</blockquote>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<blockquote class="blockquote">
<p><strong>hint: Q.17.</strong> Can you report the model and the model fit statistics using the language you have been shown in the week 18 lecture?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-51-contents" aria-controls="callout-51" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-51" class="callout-51-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.17.</li>
</ul>
<blockquote class="blockquote">
<p>We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (<code>HLVA</code>), reading strategy (<code>FACTOR3</code>), and vocabulary (<code>SHIPLEY</code>) as predictors. The model is significant overall, with F(3, 168) = 31.99, p&lt; .001, and explains 35% of variance (adjusted R2 = 0.35). Mean accuracy was predicted to be higher given higher scores in health literacy (<code>HLVA</code> estimate = .018, t = 4.90, p &lt; .001), vocabulary knowledge (<code>SHIPLEY</code> estimate = .008, t = 4.53, p &lt; .001), and reading strategy (<code>FACTOR3</code> estimate = .003, t = 2.68, p = .008).</p>
</blockquote>
</div>
</div>
</div>
<p>Examine the predictors of mean accuracy (<code>mean.acc</code>), now, for the <code>study.122</code> data.</p>
<p>We specify a linear model <em>now</em> of the <code>study.122</code> data, including as the outcome:</p>
<ul>
<li>mean accuracy (<code>mean.acc</code>)</li>
</ul>
<p>and including as the predictors the variables:</p>
<ul>
<li>health literacy (<code>HLVA</code>);</li>
<li>vocabulary (<code>SHIPLEY</code>);</li>
<li>reading strategy (<code>FACTOR3</code>).</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-52-contents" aria-controls="callout-52" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-52" class="callout-52-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study<span class="fl">.122</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.122)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.37214 -0.07143 -0.01102  0.07411  0.25329 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.3066150  0.1447265   2.119   0.0382 *  
HLVA        0.0335342  0.0071332   4.701 1.52e-05 ***
SHIPLEY     0.0062524  0.0034741   1.800   0.0768 .  
FACTOR3     0.0006217  0.0024450   0.254   0.8001    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1162 on 61 degrees of freedom
Multiple R-squared:  0.4158,    Adjusted R-squared:  0.3871 
F-statistic: 14.47 on 3 and 61 DF,  p-value: 3.156e-07</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Using the model estimates, we can answer the research question:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<p>Inspect the model summary, then answer the following questions:</p>
<blockquote class="blockquote">
<p><strong>Q.18.</strong> What is the estimate for the coefficient of the effect of the predictor, <code>HLVA</code>, in <em>this</em> model?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-53-contents" aria-controls="callout-53" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-53" class="callout-53-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.18. 0.0335342</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.19.</strong> Is the effect significant?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-54-contents" aria-controls="callout-54" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-54" class="callout-54-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.19. It is significant, p &gt; .05 because p = 1.52e-05</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.20.</strong> What are the values for t and p for the significance test for the coefficient?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-55-contents" aria-controls="callout-55" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-55" class="callout-55-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.20. t = 4.701, p &lt; .001</li>
</ul>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.21.</strong> Now consider the estimates for all the variables, what do you conclude is the answer to the research question – given the <code>study.122</code> data:</p>
</blockquote>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<blockquote class="blockquote">
<p><strong>hint: Q.21.</strong> Can you report the model and the model fit statistics using the language you have been shown in the week 18 lecture?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-56-contents" aria-controls="callout-56" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-56" class="callout-56-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.21.</li>
</ul>
<blockquote class="blockquote">
<p>We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (<code>HLVA</code>), reading strategy (<code>FACTOR3</code>), and vocabulary (<code>SHIPLEY)</code> as predictors. The model is significant overall, with F(3, 61) = 14.47, p &lt; .001, and explains 39% of variance (adjusted R2 = .387). Mean accuracy was predicted to be higher given higher scores in health literacy (<code>HLVA</code> estimate = .034, t = 4.70, p &lt; .001). There were non-significant effects of individual differences in vocabulary knowledge (<code>SHIPLEY</code> estimate = .006, t = 1.80, p = .077) and reading strategy (<code>FACTOR3</code> estimate = .001, t = .25, p = .800).</p>
</blockquote>
</div>
</div>
</div>
<p>At this point, we can evaluate the evidence from the PSYC122 sample – based on your responses – to assess if the patterns, the estimates, we saw previously are repeated in analyses of PSYC122 responses.</p>
<blockquote class="blockquote">
<p><strong>Q.22.</strong> Are the findings from <code>study.two.gen</code> replicated in <code>study.122</code>? - hint: Q.22. We can judge if the results in an earlier study are replicated in another study by examining if – here – the linear model estimates are significant in both studies <em>and</em> if the coefficient estimates have the same size and sign in both studies.</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-57-contents" aria-controls="callout-57" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-57" class="callout-57-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><p>A.22. If you compare the linear model coefficient estimates from both the <code>study.two.gen</code> and <code>study.122</code> models, you can see:</p></li>
<li><p>first, that the <code>HLVA</code> effect estimate is significant in both <code>study.two.gen</code> and <code>study.122</code>;</p></li>
<li><p>second, that the estimates of the <code>HLVA</code> effect have the same sign – positive – in both studies while the estimated coefficient is a bit bigger in the <code>study.122</code> data (implying a stronger effect);</p></li>
<li><p>but, third that the estimates of the effects of variation in vocabulary knowledge (<code>SHIPLEY</code>) and reading strategy (<code>FACTOR3</code>) are significant in <code>study.two.gen</code> but not in <code>study.122</code>.</p></li>
</ul>
<p>This suggests that the attributes – the set of abilities – that predict comprehension accuracy are similar but not the same in the <code>study.two.gen</code> participants compared to <code>study.122</code> participants.</p>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Q.23.</strong> How would you describe the outstanding difference between the results of the two studies? <strong>hint: Q.23.</strong> We can look at the estimates but we can also use model prediction plotting code to <em>visualize</em> the results. You can build on the code you used before, see:</p>
</blockquote>
<ul>
<li><code>2022-23-PSYC122-w18-how-to.R</code></li>
<li><code>2022-23-PSYC122-w19-how-to.R</code></li>
</ul>
<blockquote class="blockquote">
<p><strong>hint: Q.23.</strong> Let’s focus on comparing the <code>study.two.gen</code> and <code>study.122</code> estimates for the effect of <code>HLVA</code> in both models: we can plot model predictions, for comparison:</p>
</blockquote>
<p>First: fit the models – using different names for the different models.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-58-contents" aria-controls="callout-58" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-58" class="callout-58-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>model.two <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study.two.gen)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.two)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.two.gen)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.242746 -0.074188  0.003173  0.075361  0.211357 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.146896   0.076325   1.925  0.05597 .  
HLVA        0.017598   0.003589   4.904  2.2e-06 ***
SHIPLEY     0.008397   0.001853   4.533  1.1e-05 ***
FACTOR3     0.003087   0.001154   2.675  0.00822 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.097 on 168 degrees of freedom
Multiple R-squared:  0.3636,    Adjusted R-squared:  0.3522 
F-statistic: 31.99 on 3 and 168 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study<span class="fl">.122</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.122</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.122)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.37214 -0.07143 -0.01102  0.07411  0.25329 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.3066150  0.1447265   2.119   0.0382 *  
HLVA        0.0335342  0.0071332   4.701 1.52e-05 ***
SHIPLEY     0.0062524  0.0034741   1.800   0.0768 .  
FACTOR3     0.0006217  0.0024450   0.254   0.8001    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1162 on 61 degrees of freedom
Multiple R-squared:  0.4158,    Adjusted R-squared:  0.3871 
F-statistic: 14.47 on 3 and 61 DF,  p-value: 3.156e-07</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Second, create prediction plots for the <code>HLVA</code> effect for each model.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-59-contents" aria-controls="callout-59" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-59" class="callout-59-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>dat.two <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model.two, <span class="st">"HLVA"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>plot.two <span class="ot">&lt;-</span> <span class="fu">plot</span>(dat.two) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Study Two"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model<span class="fl">.122</span>, <span class="st">"HLVA"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>plot<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">plot</span>(dat<span class="fl">.122</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Study PSYC122"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Third, show the plots side-by-side:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-60-contents" aria-controls="callout-60" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-60" class="callout-60-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="sc">+</span> plot<span class="fl">.122</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week19_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<p>Then use your <em>visualization</em> of the model results to describe the outstanding difference between the results of the two studies – focusing on the effect of <code>HLVA</code> in both models.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-61-contents" aria-controls="callout-61" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-61" class="callout-61-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.23. If we compare the estimates for the coefficient of the <code>HLVA</code> effect in the <code>study.two.gen</code> and <code>study.122</code> models we can see that:</li>
</ul>
<ol type="1">
<li>The health literacy <code>HLVA</code> effect is significant in both <code>study.two.gen</code> and <code>study.122</code>.</li>
<li>The effect trends positive in both studies.</li>
<li>The coefficient estimate is bigger in <code>study.122</code> than in <code>study.two.gen</code>.</li>
<li>The prediction plots suggest the prediction line slope is steeper in <code>study.122</code>.</li>
<li>The grey shaded area around the trend line (indicating our uncertainty about the estimated trend) is wider for <code>study.two.gen</code> than for <code>study.122</code>, suggesting we are more uncertain about the association for the <code>study.two.gen</code> data.</li>
</ol>
<ul>
<li>The breadth of the grey shaded area around the trend line is hard to compare between the two plots. You have to look carefully at the y-axis scale information to make a judgment about the relative width of these uncertainty ellipses.</li>
</ul>
<p>The visualizations plus the model summaries suggests that the estimates of the effect of health literacy are different in the <code>study.122</code> compared to the <code>study.two.gen</code> data. Why is that?</p>
</div>
</div>
</div>
<p>We can redraw the prediction plots to add in more information about our samples. This change, see following, will help us to interpret the results of the analyses we have done. And <em>that</em> will help you to see why data visualization and data analysis work well together.</p>
<p>In the <code>{ggeffects}</code> online information, you can see links to practical examples. Can you use the information under <code>Practical examples</code> to adjust the appearance of the prediction plots: to make them black and white; to add points?</p>
<p>First create the plots.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-62-contents" aria-controls="callout-62" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-62" class="callout-62-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>dat.two <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model.two, <span class="st">"HLVA"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>plot.two <span class="ot">&lt;-</span> <span class="fu">plot</span>(dat.two, <span class="at">colors =</span> <span class="st">"bw"</span>, <span class="at">add.data =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Study Two"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Argument `add.data` is deprecated and will be removed in the future.
  Please use `show_data` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model<span class="fl">.122</span>, <span class="st">"HLVA"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>plot<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">plot</span>(dat<span class="fl">.122</span>, <span class="at">colors =</span> <span class="st">"bw"</span>, <span class="at">add.data =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Study PSYC122"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Argument `add.data` is deprecated and will be removed in the future.
  Please use `show_data` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Then show the plots in a grid, to allow comparison of the effect of <code>HLVA</code> between studies in a <em>professional</em> presentation.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-63-contents" aria-controls="callout-63" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Code
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-63" class="callout-63-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="sc">+</span> plot<span class="fl">.122</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Week19_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
</div>
<div class="calloutbox-tip">
<p>It is often useful to compare model estimates – here, the slopes – with the raw data observations.</p>
<ul>
<li>No model will be perfect.</li>
<li>Visualizing the difference between what we observe and what we predict helps to make sense of how our prediction model could be improved.</li>
</ul>
</div>
<blockquote class="blockquote">
<p><strong>Q.24.</strong> Given the information in the adjusted plots, can you explain why we appear to be more uncertain about the <code>HLVA</code> effect given the <code>study.122</code> data?</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-64-contents" aria-controls="callout-64" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-64" class="callout-64-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>A.24. Adding points allow us to see:</li>
</ul>
<ol type="1">
<li>There are far fewer observations in the <code>study.122</code> dataset than in the <code>study.two.gen</code> data: this means that our estimate of the effect will be <em>more uncertain</em> because we have <em>less information</em> when we look at the <code>study.122</code> data.</li>
<li>But it is also clear that the effect of <code>HLVA</code> appears to be stronger in the <code>study.122</code> data because observed scores are <em>closer</em> to model predictions: the <code>HLVA</code> effect <em>explains more variation</em> in the <code>study.122</code> data than in the <code>study.two.gen</code> data.</li>
</ol>
</div>
</div>
</div>
</section>
</section>
</section>
<section id="sec-wk19-lab-Q-and-A" class="level2">
<h2 class="anchored" data-anchor-id="sec-wk19-lab-Q-and-A">Online Q&amp;A</h2>
<p>You will find, below, a link to the video recording of the Week 19 online Q&amp;A after it has been completed.</p>
<iframe src="https://livelancsac-my.sharepoint.com/personal/daviesra_lancaster_ac_uk/_layouts/15/embed.aspx?UniqueId=b83dbb36-f1b8-406c-b8a4-b9cd4ce285db&amp;embed=%7B%22ust%22%3Atrue%2C%22hv%22%3A%22CopyEmbedCode%22%7D&amp;referrer=StreamWebApp&amp;referrerScenario=EmbedDialog.Create" width="640" height="360" frameborder="0" scrolling="no" allowfullscreen="" title="PSYC122 Online Seminar Fridays 9am wks 11-14 &amp; 16-19-20240315_090607-Meeting Recording.mp4"></iframe>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../PSYC122/Week18.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">7. Week 18 – Developing the linear model</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Website developed by Matthew Ivory</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../previous-content/index.html">Previous Content</a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>