---
title: Foundations of Psychological Research
subtitle: "Course coordinator: John Towse"
email-obfuscation: javascript

#listing:
#  id: links
#  template: ../links.ejs
#  contents: guide.yml
---

# Welcome

Welcome to PSYC4242!

How do we decide whether two groups differ in a psychological process or behaviour? This module builds on the knowledge and skills acquired in Introduction to Psychological Research (PSYC4141). You will continue to build your understanding of rigorous and transparent scientific practices and develop your thinking of real-world issues. Using modern techniques, learn more about how to collect, present and analyse data. You will be introduced to key concepts and practices of research design and data analysis through lectures. Practical laboratory classes will teach you how to design studies, handle data, perform statistical analyses and report your findings. The laboratory classes will be hands-on, giving you direct experience with all stages of a research project, including the use of specialised software. Topics covered will include experimental design, how to decide on your study participants, comparing groups for behaviours of psychological interest and hypothesis testing.

# Asking for help

We have carefully prepared and refined the lab materials in this course over several years, and we feel that the pace of the materials is just right for our students. Some students will complete them more quickly, and others more slowly - both of these scenarios are absolutely fine. You should work at the pace that suits you best, making sure you understand the materials before you move forward. 

It is fairly inevitable that you will get stuck on the lab materials in this module at some point. This might be in Week 11, Week 12, or later. When you do, it's important you reach out for help:

  - **Ask your peers on your table**. We've designed this teaching space to help collaborative work. You are encouraged to work with other students. Make sure you ask others to explain how they've solved an exercise. Make sure you help out others where you can. Always make sure you understand the code and the exercise; don't simply be satisfied that you've got the right answer.
  - **Ask a Lecturer**. We are here to help you. There are no "stupid questions" in statistics, so just ask the Lecturer any question about what you're doing. 
  - **Ask on the Q&A Forum on Moodle**. On the PSYC4242 moodle page you will find a [Q&A Forum](ADD LINK TO 4242 Moodle Q&A). This is a great way to ask a question outside of the lab sessions. It might seem scary to ask a question in the forum, but please don't be afraid to do this. If you have a question, you can bet 30+ other students also have the same question! So by asking the question on the forum, you help out many more people on the module. A friendly GTA or Lecturer will be along to answer the question as soon as possible (we aim for within 48 hours during the working week).
  - **Ask during live online Q & A session**. Each week we hold an online "Q&A" session where we will try and resolve any general queries and problems. It's an ideal time to discuss things that students are struggling with or confused about. You can ask on the discussion forum above and then we might be able to pick up the issues and discuss them, but you can also ask in the session itself.

# Course Contacts

If you have something that needs to be private, then please feel free to email the coordinator at the email addresses below:

|   | Email Address |
|----|----|
| John Towse (coordinator) | [j.towse\@lancaster.ac.uk](mailto:j.towse@lancaster.ac.uk) |
|  |  |
