<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rob Davies">
<meta name="dcterms.date" content="2024-03-04">

<title>2023-24-PSYC122-w18-how-to – Statistics for Psychologists</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../Images/favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 1";};</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="https://lu-psy-r.github.io/">
    <span class="navbar-title">Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year1/index.html"> 
<span class="menu-text">Year 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year2/index.html"> 
<span class="menu-text">Year 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year3/index.html"> 
<span class="menu-text">Year 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/MSc/index.html"> 
<span class="menu-text">MSc</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/more/index.html"> 
<span class="menu-text">And More…</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">2023-24-PSYC122-w18-how-to</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../PSYC121/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC121</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistics for Psychologists</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Descriptive statistics in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. DVs and IVs in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Customisation of graphs, and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Class test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Sampling, probability and binomial tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Filtering data and testing means (one-sample t-test)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Related-samples t-tests, plotting means and SE bars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Unrelated-samples t-test and Power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../PSYC122/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC122</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Week 11 - Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Week 12 - Correlation Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Week 13 - The Linear Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Week 14 - Chi-Square</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Week 16 – Hypotheses, associations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Week 17 – Better understanding the linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Week 18 – Developing the linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Week 19 – Linear models – critical perspectives</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#naming-things" id="toc-naming-things" class="nav-link" data-scroll-target="#naming-things">Naming things</a></li>
  <li><a href="#the-data-we-will-be-using" id="toc-the-data-we-will-be-using" class="nav-link" data-scroll-target="#the-data-we-will-be-using">The data we will be using</a></li>
  </ul></li>
  <li><a href="#answers" id="toc-answers" class="nav-link" data-scroll-target="#answers">Answers</a>
  <ul class="collapse">
  <li><a href="#step-1-set-up" id="toc-step-1-set-up" class="nav-link" data-scroll-target="#step-1-set-up">Step 1: Set-up</a>
  <ul class="collapse">
  <li><a href="#task-1-run-code-to-empty-the-r-environment" id="toc-task-1-run-code-to-empty-the-r-environment" class="nav-link" data-scroll-target="#task-1-run-code-to-empty-the-r-environment">Task 1 – Run code to empty the R environment</a></li>
  <li><a href="#task-2-run-code-to-load-relevant-libraries" id="toc-task-2-run-code-to-load-relevant-libraries" class="nav-link" data-scroll-target="#task-2-run-code-to-load-relevant-libraries">Task 2 – Run code to load relevant libraries</a></li>
  </ul></li>
  <li><a href="#step-2-load-the-data" id="toc-step-2-load-the-data" class="nav-link" data-scroll-target="#step-2-load-the-data">Step 2: Load the data</a>
  <ul class="collapse">
  <li><a href="#task-3-read-in-the-data-file-we-will-be-using" id="toc-task-3-read-in-the-data-file-we-will-be-using" class="nav-link" data-scroll-target="#task-3-read-in-the-data-file-we-will-be-using">Task 3 – Read in the data file we will be using</a></li>
  <li><a href="#task-4-inspect-the-data-file" id="toc-task-4-inspect-the-data-file" class="nav-link" data-scroll-target="#task-4-inspect-the-data-file">Task 4 – Inspect the data file</a></li>
  </ul></li>
  <li><a href="#step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor" id="toc-step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor" class="nav-link" data-scroll-target="#step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor">Step 3: Use a linear model to to answer the research questions – one predictor</a>
  <ul class="collapse">
  <li><a href="#revise-practice-to-strengthen-skills" id="toc-revise-practice-to-strengthen-skills" class="nav-link" data-scroll-target="#revise-practice-to-strengthen-skills">Revise: Practice to strengthen skills</a></li>
  <li><a href="#task-5-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-health-literacy-hlva" id="toc-task-5-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-health-literacy-hlva" class="nav-link" data-scroll-target="#task-5-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-health-literacy-hlva">Task 5 – Examine the relation between outcome mean accuracy (<code>mean.acc</code>) and health literacy (<code>HLVA</code>)</a></li>
  <li><a href="#hint-task-5" id="toc-hint-task-5" class="nav-link" data-scroll-target="#hint-task-5">Hint: Task 5</a></li>
  </ul></li>
  <li><a href="#step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" id="toc-step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" class="nav-link" data-scroll-target="#step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors">Step 4: Use a linear model to to answer the research questions – multiple predictors</a>
  <ul class="collapse">
  <li><a href="#introduce-make-some-new-moves" id="toc-introduce-make-some-new-moves" class="nav-link" data-scroll-target="#introduce-make-some-new-moves">Introduce: make some new moves</a></li>
  <li><a href="#task-6-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors" id="toc-task-6-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors" class="nav-link" data-scroll-target="#task-6-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors">Task 6 – Examine the relation between outcome mean accuracy (<code>mean.acc</code>) and <em>multiple</em> predictors</a></li>
  </ul></li>
  <li><a href="#step-5-plot-predictions-from-linear-models-with-multiple-predictors" id="toc-step-5-plot-predictions-from-linear-models-with-multiple-predictors" class="nav-link" data-scroll-target="#step-5-plot-predictions-from-linear-models-with-multiple-predictors">Step 5: Plot predictions from linear models with multiple predictors</a>
  <ul class="collapse">
  <li><a href="#introduce-make-some-new-moves-1" id="toc-introduce-make-some-new-moves-1" class="nav-link" data-scroll-target="#introduce-make-some-new-moves-1">Introduce: make some new moves</a></li>
  <li><a href="#task-7-plot-linear-model-predictions-for-one-of-the-predictors" id="toc-task-7-plot-linear-model-predictions-for-one-of-the-predictors" class="nav-link" data-scroll-target="#task-7-plot-linear-model-predictions-for-one-of-the-predictors">Task 7 – Plot linear model predictions for one of the predictors</a></li>
  <li><a href="#task-8-now-produce-plots-that-show-the-predictions-for-all-the-predictor-variables-in-the-model" id="toc-task-8-now-produce-plots-that-show-the-predictions-for-all-the-predictor-variables-in-the-model" class="nav-link" data-scroll-target="#task-8-now-produce-plots-that-show-the-predictions-for-all-the-predictor-variables-in-the-model">Task 8 – Now produce plots that show the predictions for all the predictor variables in the model</a></li>
  </ul></li>
  <li><a href="#step-6-now-draw-boxplots-to-examine-associations-between-variables" id="toc-step-6-now-draw-boxplots-to-examine-associations-between-variables" class="nav-link" data-scroll-target="#step-6-now-draw-boxplots-to-examine-associations-between-variables">Step 6: Now draw boxplots to examine associations between variables</a>
  <ul class="collapse">
  <li><a href="#consolidation-practice-to-strengthen-skills" id="toc-consolidation-practice-to-strengthen-skills" class="nav-link" data-scroll-target="#consolidation-practice-to-strengthen-skills">Consolidation: practice to strengthen skills</a></li>
  <li><a href="#task-9-create-boxplots-to-examine-the-association-between-a-continuous-numeric-outcome-variable-like-mean.acc-and-a-categorical-variable-like-ethnicity" id="toc-task-9-create-boxplots-to-examine-the-association-between-a-continuous-numeric-outcome-variable-like-mean.acc-and-a-categorical-variable-like-ethnicity" class="nav-link" data-scroll-target="#task-9-create-boxplots-to-examine-the-association-between-a-continuous-numeric-outcome-variable-like-mean.acc-and-a-categorical-variable-like-ethnicity">Task 9 – Create boxplots to examine the association between a continuous numeric outcome variable like <code>mean.acc</code> and a categorical variable like <code>ETHNICITY</code></a></li>
  </ul></li>
  <li><a href="#step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables" id="toc-step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables" class="nav-link" data-scroll-target="#step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables">Step 6: Estimate the effects of factors as well as numeric variables</a>
  <ul class="collapse">
  <li><a href="#introduce-make-some-new-moves-2" id="toc-introduce-make-some-new-moves-2" class="nav-link" data-scroll-target="#introduce-make-some-new-moves-2">Introduce: make some new moves</a></li>
  <li><a href="#task-10-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors" id="toc-task-10-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors" class="nav-link" data-scroll-target="#task-10-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors">Task 10 – Fit a linear model including both numeric variables and categorical variables as predictors</a></li>
  <li><a href="#task-13-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors-and-then-plot-the-predicted-effect-of-the-factor-the-categorical-variable" id="toc-task-13-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors-and-then-plot-the-predicted-effect-of-the-factor-the-categorical-variable" class="nav-link" data-scroll-target="#task-13-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors-and-then-plot-the-predicted-effect-of-the-factor-the-categorical-variable">Task 13 – Fit a linear model including both numeric variables and categorical variables as predictors, and then plot the predicted effect of the factor (the categorical variable)</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2023-24-PSYC122-w18-how-to</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rob Davies </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 4, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In Week 18, we aim to <em>further develop</em> skills in working with the linear model.</p>
<p>We do this to learn how to answer research questions like:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<p>These kinds of research questions can be answered using methods like the <strong>linear model</strong>.</p>
<p>When we do these analyses, we need to think about how we report the results:</p>
<ul>
<li>we usually need to report information about the kind of model we specify;</li>
<li>and we will need to report the nature of the association estimated in our model.</li>
</ul>
<p>We usually need to decide:</p>
<ul>
<li>is the association significant?</li>
<li>does the association reflect a positive or negative relationship between outcome and predictor?</li>
<li>and is the association we see in our sample data relatively strong or weak?</li>
</ul>
<p>We will consolidate and extend learning on data visualization:</p>
<ul>
<li>focusing on how we edit ggplot() code to produce professional looking plots.</li>
</ul>
<section id="naming-things" class="level2">
<h2 class="anchored" data-anchor-id="naming-things">Naming things</h2>
<p>I will format dataset names like this:</p>
<ul>
<li><code>study-one-general-participants.csv</code></li>
</ul>
<p>I will also format variable (data column) names like this: <code>variable</code></p>
<p>I will also format value or other data object (e.g.&nbsp;cell value) names like this: <code>studyone</code></p>
<p>I will format functions and library names like this: e.g.&nbsp;function <code>ggplot()</code> or e.g.&nbsp;library <code>{tidyverse}</code>.</p>
</section>
<section id="the-data-we-will-be-using" class="level2">
<h2 class="anchored" data-anchor-id="the-data-we-will-be-using">The data we will be using</h2>
<p>In this how-to guide, we use data from a 2020 study of the response of adults from a UK national sample to written health information:</p>
<ul>
<li><code>study-one-general-participants.csv</code></li>
</ul>
</section>
</section>
<section id="answers" class="level1">
<h1>Answers</h1>
<section id="step-1-set-up" class="level2">
<h2 class="anchored" data-anchor-id="step-1-set-up">Step 1: Set-up</h2>
<p>To begin, we set up our environment in R.</p>
<section id="task-1-run-code-to-empty-the-r-environment" class="level3">
<h3 class="anchored" data-anchor-id="task-1-run-code-to-empty-the-r-environment">Task 1 – Run code to empty the R environment</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())                            </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-2-run-code-to-load-relevant-libraries" class="level3">
<h3 class="anchored" data-anchor-id="task-2-run-code-to-load-relevant-libraries">Task 2 – Run code to load relevant libraries</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggeffects"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggeffects' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.5.1     ✔ purrr   1.0.2
✔ tibble  3.2.1     ✔ dplyr   1.1.2
✔ tidyr   1.3.0     ✔ stringr 1.5.0
✔ readr   2.1.3     ✔ forcats 0.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
</div>
</section>
</section>
<section id="step-2-load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="step-2-load-the-data">Step 2: Load the data</h2>
<section id="task-3-read-in-the-data-file-we-will-be-using" class="level3">
<h3 class="anchored" data-anchor-id="task-3-read-in-the-data-file-we-will-be-using">Task 3 – Read in the data file we will be using</h3>
<p>The data file is called:</p>
<ul>
<li><code>study-one-general-participants.csv</code></li>
</ul>
<p>Use the <code>read_csv()</code> function to read the data file into R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>study.one.gen <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"study-one-general-participants.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 169 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY
dbl (7): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3, QRITOTAL

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>When you read the data file in, give the data object you create a distinct name e.g.&nbsp;<code>study.one.gen</code>.</p>
</section>
<section id="task-4-inspect-the-data-file" class="level3">
<h3 class="anchored" data-anchor-id="task-4-inspect-the-data-file">Task 4 – Inspect the data file</h3>
<p>Use the <code>summary()</code> or <code>head()</code> functions to take a look.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(study.one.gen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  participant_ID mean.acc mean.self study     AGE SHIPLEY  HLVA FACTOR3 QRITOTAL
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
1 studyone.1         0.49      7.96 studyo…    34      33     7      53       11
2 studyone.10        0.85      7.28 studyo…    25      33     7      60       11
3 studyone.100       0.82      7.36 studyo…    43      40     8      46       12
4 studyone.101       0.94      7.88 studyo…    46      33    11      51       15
5 studyone.102       0.58      6.96 studyo…    18      32     3      51       12
6 studyone.103       0.84      7.88 studyo…    19      37    13      45       19
# ℹ 3 more variables: GENDER &lt;chr&gt;, EDUCATION &lt;chr&gt;, ETHNICITY &lt;chr&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(study.one.gen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> participant_ID        mean.acc        mean.self        study          
 Length:169         Min.   :0.3600   Min.   :3.440   Length:169        
 Class :character   1st Qu.:0.7600   1st Qu.:6.080   Class :character  
 Mode  :character   Median :0.8400   Median :7.080   Mode  :character  
                    Mean   :0.8163   Mean   :6.906                     
                    3rd Qu.:0.9000   3rd Qu.:7.920                     
                    Max.   :0.9900   Max.   :9.000                     
      AGE           SHIPLEY           HLVA           FACTOR3     
 Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :34.00  
 1st Qu.:24.00   1st Qu.:33.00   1st Qu.: 7.000   1st Qu.:46.00  
 Median :32.00   Median :35.00   Median : 9.000   Median :51.00  
 Mean   :34.87   Mean   :34.96   Mean   : 8.905   Mean   :50.33  
 3rd Qu.:42.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  
 Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  
    QRITOTAL        GENDER           EDUCATION          ETHNICITY        
 Min.   : 6.00   Length:169         Length:169         Length:169        
 1st Qu.:12.00   Class :character   Class :character   Class :character  
 Median :13.00   Mode  :character   Mode  :character   Mode  :character  
 Mean   :13.36                                                           
 3rd Qu.:15.00                                                           
 Max.   :19.00                                                           </code></pre>
</div>
</div>
<p>Even though you have done this before, you will want to do it again, here, and pay particular attention to:</p>
<ul>
<li>summary information about the numeric variables;</li>
<li>summary information about variables of class: <code>character</code>.</li>
</ul>
</section>
</section>
<section id="step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor" class="level2">
<h2 class="anchored" data-anchor-id="step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor">Step 3: Use a linear model to to answer the research questions – one predictor</h2>
<section id="revise-practice-to-strengthen-skills" class="level3">
<h3 class="anchored" data-anchor-id="revise-practice-to-strengthen-skills">Revise: Practice to strengthen skills</h3>
<p>We start by revising how to use lm() with one predictor.</p>
<p>One of our research questions is:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
</section>
<section id="task-5-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-health-literacy-hlva" class="level3">
<h3 class="anchored" data-anchor-id="task-5-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-health-literacy-hlva">Task 5 – Examine the relation between outcome mean accuracy (<code>mean.acc</code>) and health literacy (<code>HLVA</code>)</h3>
</section>
<section id="hint-task-5" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-5">Hint: Task 5</h3>
<p>We can use <code>lm()</code> to estimate whether variation in health literacy (<code>HLVA</code>) predicts outcome mean accuracy (<code>mean.acc</code>) of understanding.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA, <span class="at">data =</span> study.one.gen)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA, data = study.one.gen)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.40848 -0.05304  0.01880  0.07608  0.19968 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.61399    0.03387  18.128  &lt; 2e-16 ***
HLVA         0.02272    0.00369   6.158 5.31e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1068 on 167 degrees of freedom
Multiple R-squared:  0.1851,    Adjusted R-squared:  0.1802 
F-statistic: 37.92 on 1 and 167 DF,  p-value: 5.307e-09</code></pre>
</div>
</div>
<p>In R analysis code, we write <code>method(outcome ~ predictor)</code> so:</p>
<pre><code>lm(mean.acc ~ HLVA, data = study.one.gen)</code></pre>
<ul>
<li>gets us an analysis of whether or how <code>HLVA</code> predicts variation in outcome <code>mean.acc</code>.</li>
</ul>
<p>If you look at the model <code>summary</code> you can answer the following questions.</p>
<section id="questions-task-5" class="level4">
<h4 class="anchored" data-anchor-id="questions-task-5">Questions: Task 5</h4>
<ul>
<li><p>Q.1. What is the estimate for the coefficient of the effect of the predictor, <code>HLVA</code>?</p></li>
<li><p>A.1. 0.02272</p></li>
<li><p>Q.2. Is the effect significant?</p></li>
<li><p>A.2. It is significant, p &lt; .05</p></li>
<li><p>Q.3. What are the values for t and p for the significance test for the coefficient?</p></li>
<li><p>A.3. t = 6.158, p = 5.31e-09</p></li>
<li><p>Q.4. What do you conclude is the answer to the research question, given the linear model results?</p></li>
<li><p>A.4. The model slope estimate suggests that as HLVA scores increase so also do <code>mean.acc</code> scores</p></li>
<li><p>Q.5. What is the F-statistic for the regression? Report F, DF and the p-value.</p></li>
<li><p>A.5. F-statistic: 37.92 on 1 and 167 DF, p-value: 5.307e-09</p></li>
<li><p>Q.6. Is the regression significant?</p></li>
<li><p>A.6. Yes: the regression is significant.</p></li>
<li><p>Q.7. What is the Adjusted R-squared?</p></li>
<li><p>A.7. Adjusted R-squared: 0.1802</p></li>
<li><p>Q.8. Explain in words what this R-squared value indicates?</p></li>
<li><p>A.8. The R-squared suggests that 18% of outcome variance can be explained by the model</p></li>
</ul>
</section>
</section>
</section>
<section id="step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" class="level2">
<h2 class="anchored" data-anchor-id="step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors">Step 4: Use a linear model to to answer the research questions – multiple predictors</h2>
<section id="introduce-make-some-new-moves" class="level3">
<h3 class="anchored" data-anchor-id="introduce-make-some-new-moves">Introduce: make some new moves</h3>
</section>
<section id="task-6-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors" class="level3">
<h3 class="anchored" data-anchor-id="task-6-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors">Task 6 – Examine the relation between outcome mean accuracy (<code>mean.acc</code>) and <em>multiple</em> predictors</h3>
<p>Here, the predictors will include:</p>
<ul>
<li>health literacy (<code>HLVA</code>);</li>
<li>vocabulary (<code>SHIPLEY</code>);</li>
<li>reading strategy (<code>FACTOR3</code>).</li>
</ul>
<section id="hint-task-6" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-6">Hint: Task 6</h4>
<p>We use <code>lm()</code>, as before, but now specify each variable listed here by variable name</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study.one.gen)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.one.gen)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.40322 -0.05349  0.01152  0.07128  0.18434 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.302030   0.091257   3.310  0.00115 ** 
HLVA        0.017732   0.003923   4.521 1.17e-05 ***
SHIPLEY     0.005363   0.002336   2.296  0.02291 *  
FACTOR3     0.003355   0.001264   2.654  0.00872 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1033 on 165 degrees of freedom
Multiple R-squared:  0.2474,    Adjusted R-squared:  0.2337 
F-statistic: 18.08 on 3 and 165 DF,  p-value: 3.423e-10</code></pre>
</div>
</div>
<p>Notice that we do the linear model in the steps:</p>
<ol type="1">
<li><code>model &lt;- lm(...)</code> fit the model using <code>lm(...)</code>, giving the model a name; here, we call it <code>model</code>;</li>
<li><code>...lm(mean.acc ~ HLVA...)</code> tell R you want a model of the outcome <code>mean.acc</code> predicted (<code>~</code>) by the predictors listed, <code>HLVA</code>, <code>SHIPLEY</code>, and <code>FACTOR3</code>.</li>
<li><code>...data = study.one.gen)</code> tell R that the variables you name in the formula are in the <code>study.one.gen</code> dataset.</li>
<li><code>summary(model)</code> ask R for a summary of the model you called <code>model</code>.</li>
</ol>
<p>Notice: that we use the variable names as they appear in the dataset, and that each predictor variable is separated from the next by a plus (<code>+</code>) sign.</p>
<p>Notice: R has a general formula syntax: <code>outcome ~ predictor</code> <em>or</em> <code>y ~ x</code> and uses the same format across a number of different analysis functions.</p>
<ul>
<li>Each time, the left of the tilde symbol <code>~</code> is some output or outcome and the right of the tilde <code>~</code> is some input or predictor or set of predictors.</li>
</ul>
</section>
<section id="questions-task-6" class="level4">
<h4 class="anchored" data-anchor-id="questions-task-6">Questions: Task 6</h4>
<p>If you look at the model summary you can answer the following questions</p>
<p>Q.9. What is the estimate for the coefficient of the effect of the predictor <code>HLVA</code> in <em>this</em> model?</p>
<p>A.9. 0.017732</p>
<p>Q.10. Is the effect significant?</p>
<p>A.10. It is significant, p &lt; .05</p>
<p>Q.11. What are the values for t and p for the significance test for the coefficient?</p>
<p>A.11. t = 4.521, p = 1.17e-05</p>
<p>Q.12. What do you conclude is the answer to the research question, given the linear model results?</p>
<p>A.12. The model slope estimate 0.017732 suggests that as <code>HLVA</code> scores increase so also do <code>mean.acc</code> scores.</p>
<p>Q.13. How is the coefficient estimate for the <code>HLVA</code> slope similar or different, comparing this model with multiple predictors to the previous model with one predictor?</p>
<p>A.13. It can be seen that the <code>HLVA</code> estimate in the two models is different in that it is a bit smaller in the model with multiple predictors compared to the model with one predictor. The <code>HLVA</code> estimate is similar in that it remains positive, it is about the same size.</p>
<p>Notice that:-</p>
<ul>
<li>The estimate of the coefficient of any one predictor can be expected to vary depending on the presence of other predictors.</li>
<li>This is one reason why we need to be transparent about why we choose to use the predictors we include in our model.</li>
</ul>
<p>Q.14. Can you report the estimated effect of <code>SHIPLEY</code> (the measure of vocabulary) using the kind of language you are shown in lecture week 18?</p>
<p>A.14. The answer to the question can be written like this:</p>
<blockquote class="blockquote">
<p>The effect of vocabulary knowledge (<code>SHIPLEY</code>) on mean accuracy of understanding is significant (estimate = 0.005, t = 2.296, p &lt; .001) indicating that increasing vocabulary knowledge is associated with increasing accuracy of understanding.</p>
</blockquote>
<p>Q.15. Can you report the model and the model fit statistics?</p>
<p>A.15. The answer to the question can be written like this:</p>
<blockquote class="blockquote">
<p>We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (<code>HLVA</code>), reading strategy (<code>FACTOR3</code>), and vocabulary (<code>SHIPLEY</code>) as predictors. The model is significant overall, with F(3, 165) = 18.08, p&lt; .001, and explains 23% of variance (adjusted R2 = 0.23).</p>
</blockquote>
</section>
</section>
</section>
<section id="step-5-plot-predictions-from-linear-models-with-multiple-predictors" class="level2">
<h2 class="anchored" data-anchor-id="step-5-plot-predictions-from-linear-models-with-multiple-predictors">Step 5: Plot predictions from linear models with multiple predictors</h2>
<section id="introduce-make-some-new-moves-1" class="level3">
<h3 class="anchored" data-anchor-id="introduce-make-some-new-moves-1">Introduce: make some new moves</h3>
</section>
<section id="task-7-plot-linear-model-predictions-for-one-of-the-predictors" class="level3">
<h3 class="anchored" data-anchor-id="task-7-plot-linear-model-predictions-for-one-of-the-predictors">Task 7 – Plot linear model predictions for one of the predictors</h3>
<section id="hint-task-7" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-7">Hint: Task 7</h4>
<p>Previously, we used <code>geom_abline()</code>, specifying intercept and slope estimates, to draw model predictions.</p>
<p>Here, we use functions that are very helpful when we need to plot model predictions, for models where we have multiple predictors</p>
<p>We do this in four steps:</p>
<ol type="1">
<li>We first fit a linear model of the outcome, given our predictors.</li>
<li>We save information about the model.</li>
<li>We use the <code>ggpredict()</code> function from the <code>{ggeffects}</code> library to take the information about the model and create a set of predictions we can use for plotting.</li>
<li>We plot the model prediction plots.</li>
</ol>
<p>These steps proceed as follows:</p>
<ol type="1">
<li>We first fit a linear model of the outcome, given our predictors.</li>
</ol>
<p>Like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study.one.gen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code involves these key bits:</p>
<ul>
<li><code>model &lt;- lm(...)</code> we fit the model using <code>lm(...)</code>, giving the model a name; here, we call it <code>model</code>.</li>
<li><code>...lm(mean.acc ~ HLVA...)</code> we tell R we want a model of the outcome <code>mean.acc</code> predicted (<code>~</code>) by the predictors <code>HLVA</code>, <code>SHIPLEY</code>, and <code>FACTOR3</code>.</li>
</ul>
<p>Notice: when we use lm() to fit the model, R creates a set of information about the model, including estimates.</p>
<p>We give that set of information a name <code>model</code>, and we use that name, next, to access that information in the plotting step.</p>
<ol start="2" type="1">
<li>We use the <code>ggpredict()</code> function from the <code>{ggeffects}</code> library to take the information about the model and create a set of predictions we can use for plotting.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model, <span class="st">"HLVA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Notice:</p>
<ul>
<li><code>dat &lt;- ggpredict(...)</code> asks R to create a set of predictions, and we give that set of predictions a name <code>dat</code>.</li>
<li><code>... ggpredict(model, "HLVA")</code> tells R what model information it should use (from <code>model</code>) <em>and</em> which predictor variable we need predictions for <code>"HLVA"</code>.</li>
</ul>
<ol start="3" type="1">
<li>We plot the model predictions with:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w18-how-to_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="task-8-now-produce-plots-that-show-the-predictions-for-all-the-predictor-variables-in-the-model" class="level3">
<h3 class="anchored" data-anchor-id="task-8-now-produce-plots-that-show-the-predictions-for-all-the-predictor-variables-in-the-model">Task 8 – Now produce plots that show the predictions for all the predictor variables in the model</h3>
</section>
</section>
<section id="step-6-now-draw-boxplots-to-examine-associations-between-variables" class="level2">
<h2 class="anchored" data-anchor-id="step-6-now-draw-boxplots-to-examine-associations-between-variables">Step 6: Now draw boxplots to examine associations between variables</h2>
<section id="consolidation-practice-to-strengthen-skills" class="level3">
<h3 class="anchored" data-anchor-id="consolidation-practice-to-strengthen-skills">Consolidation: practice to strengthen skills</h3>
</section>
<section id="task-9-create-boxplots-to-examine-the-association-between-a-continuous-numeric-outcome-variable-like-mean.acc-and-a-categorical-variable-like-ethnicity" class="level3">
<h3 class="anchored" data-anchor-id="task-9-create-boxplots-to-examine-the-association-between-a-continuous-numeric-outcome-variable-like-mean.acc-and-a-categorical-variable-like-ethnicity">Task 9 – Create boxplots to examine the association between a continuous numeric outcome variable like <code>mean.acc</code> and a categorical variable like <code>ETHNICITY</code></h3>
<p>Here, we use <code>geom_boxplot()</code>.</p>
<section id="hint-task-9-we-can-see-where-variables-are-not-numeric-using-summary" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-9-we-can-see-where-variables-are-not-numeric-using-summary">Hint: Task 9 – We can see where variables are not numeric using <code>summary()</code></h4>
<p>The boxplot can be produced using code like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study.one.gen, <span class="fu">aes</span>(<span class="at">x =</span> ETHNICITY, <span class="at">y =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Ethnicity, ONS categories"</span>, </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mean accuracy of understanding ('mean.acc')"</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fl">1.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w18-how-to_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plotting code works bit-by-bit, as described following.</p>
<ol type="1">
<li><code>ggplot(data = study.one.gen, aes(x = ETHNICITY, y = mean.acc))</code> defines two aesthetic mappings:</li>
</ol>
<ul>
<li><code>x = ETHNICITY</code>, the x variable has to be categorical or nominal, a factor like <code>ETHNICITY</code> with different levels.</li>
<li><code>y = mean.acc</code>, the y variable has to be numeric, a set of numbers like <code>mean.acc</code> with different values.</li>
</ul>
<ol start="2" type="1">
<li><code>geom_boxplot()</code> then uses that information about category <code>(x = ...)</code> and outcome <code>(y = ...)</code> to draw a box to represent the distribution of outcome scores for each group.</li>
</ol>
<p>Notice that when you draw the plot:</p>
<ul>
<li>The middle line in each box represents the median outcome (here <code>mean.acc</code>) score for each group.</li>
<li>The shape of the box represents the distribution or spread of scores.</li>
<li>The top of the box represents the 75th percentile, what the score is for the people who are at the top 75% of the sample.</li>
<li>The bottom of the box represents the 25th percentile, what the score is for the people at the 25% level of outcomes for the sample.</li>
</ul>
<p>More information about boxplots can be found here:</p>
<p><a href="https://ggplot2.tidyverse.org/reference/geom_boxplot.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_boxplot.html</a></p>
<p>Here is an edit of the plot to make it a bit more effective:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study.one.gen, <span class="fu">aes</span>(<span class="at">x =</span> ETHNICITY, <span class="at">y =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>, <span class="at">colour =</span> <span class="st">"red"</span>, <span class="at">alpha =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Ethnicity, ONS categories"</span>, </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mean accuracy of understanding ('mean.acc')"</span>) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fl">1.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w18-how-to_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot shows:</p>
<ul>
<li>boxplots to indicate the average (median) and spread (percentiles) in <code>mean.acc</code> scores for each group;</li>
<li>plus, with points, individual <code>mean.acc</code> scores for the people in each group.</li>
</ul>
</section>
<section id="why-are-we-learning-how-to-do-this" class="level4">
<h4 class="anchored" data-anchor-id="why-are-we-learning-how-to-do-this">Why are we learning how to do this?</h4>
<p>Drawing plots which show <em>both</em> summaries (like boxplots) and raw data (scores as points) is a common (advanced) professional visualization technique.</p>
<ul>
<li>It is effective because these kinds of plots help you to see the pattern or trend <em>and</em> the nature of the underlying sample.</li>
</ul>
<p>Now you can use the plots to answer questions like the following</p>
</section>
<section id="questions-task-9" class="level4">
<h4 class="anchored" data-anchor-id="questions-task-9">Questions: Task 9</h4>
<p>Q.16. What do you notice about the distribution of scores in different groups?</p>
<p>A.16. The average accuracy of understanding appears to be similar between groups.</p>
<p>Q.17. Does anything in the plots give you reason to question the nature of the participant sample?</p>
<p>A.17. This is a leading question: there is <em>plenty</em> in the plots to cause concern.</p>
<ul>
<li>The scatter of points shows that we have many more <code>White</code> participants in the sample than participants from other ethnicities.</li>
<li>Because we have very few people in the study from ethnic minority (often classed as BAME) groups, we might be concerned about whether the results from our models are representative of what you would see in these groups, or whether the results are representative of the wider population in general.</li>
</ul>
<p>Q.18. Can you use the <code>ggplot()</code> reference information – see the webpage link – to see how and why I made the code edits I did?</p>
<p>A.18. You can see example code for each edit in the webpage.</p>
<p>Q.19. Do you understand what <code>geom_jitter()</code> is doing? – and why I would use it?</p>
<p>A.19. What the function does, and why I would use it can be found in the reference information webpage:</p>
<p><a href="https://ggplot2.tidyverse.org/reference/geom_jitter.html" class="uri">https://ggplot2.tidyverse.org/reference/geom_jitter.html</a></p>
</section>
</section>
</section>
<section id="step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables" class="level2">
<h2 class="anchored" data-anchor-id="step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables">Step 6: Estimate the effects of factors as well as numeric variables</h2>
<section id="introduce-make-some-new-moves-2" class="level3">
<h3 class="anchored" data-anchor-id="introduce-make-some-new-moves-2">Introduce: make some new moves</h3>
<p>We have not yet included any categorical or nominal variables as predictors but we can, and should:</p>
<ul>
<li><code>lm()</code> can cope with any kind of variable as a predictor.</li>
</ul>
</section>
<section id="task-10-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors" class="level3">
<h3 class="anchored" data-anchor-id="task-10-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors">Task 10 – Fit a linear model including both numeric variables and categorical variables as predictors</h3>
<section id="hint-task-12" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-12">Hint: Task 12</h4>
<p>We can inspect the data to check what variables are categorical or nominal variables – factors – using <code>summary()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(study.one.gen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> participant_ID        mean.acc        mean.self        study          
 Length:169         Min.   :0.3600   Min.   :3.440   Length:169        
 Class :character   1st Qu.:0.7600   1st Qu.:6.080   Class :character  
 Mode  :character   Median :0.8400   Median :7.080   Mode  :character  
                    Mean   :0.8163   Mean   :6.906                     
                    3rd Qu.:0.9000   3rd Qu.:7.920                     
                    Max.   :0.9900   Max.   :9.000                     
      AGE           SHIPLEY           HLVA           FACTOR3     
 Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :34.00  
 1st Qu.:24.00   1st Qu.:33.00   1st Qu.: 7.000   1st Qu.:46.00  
 Median :32.00   Median :35.00   Median : 9.000   Median :51.00  
 Mean   :34.87   Mean   :34.96   Mean   : 8.905   Mean   :50.33  
 3rd Qu.:42.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  
 Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  
    QRITOTAL        GENDER           EDUCATION          ETHNICITY        
 Min.   : 6.00   Length:169         Length:169         Length:169        
 1st Qu.:12.00   Class :character   Class :character   Class :character  
 Median :13.00   Mode  :character   Mode  :character   Mode  :character  
 Mean   :13.36                                                           
 3rd Qu.:15.00                                                           
 Max.   :19.00                                                           </code></pre>
</div>
</div>
<p>Notice that R shows categorical variables in the summary as having: <code>Class: character</code>.</p>
<ul>
<li><p>Q.20. Can you report the estimated effect of <code>ETHNICITY</code>: differences in outcome for people in different self-reported ethnicity groups?</p></li>
<li><p>Hint: Q.20. Include the factor <code>ETHNICITY</code> as a predictor:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3 <span class="sc">+</span> ETHNICITY, </span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> study.one.gen)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3 + ETHNICITY, 
    data = study.one.gen)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.40261 -0.05322  0.01168  0.07124  0.18391 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     0.302764   0.095806   3.160  0.00188 ** 
HLVA            0.017391   0.003980   4.370 2.22e-05 ***
SHIPLEY         0.005249   0.002380   2.206  0.02882 *  
FACTOR3         0.003495   0.001289   2.711  0.00744 ** 
ETHNICITYBlack  0.016600   0.065962   0.252  0.80163    
ETHNICITYMixed -0.016080   0.048371  -0.332  0.74000    
ETHNICITYOther  0.083201   0.108382   0.768  0.44381    
ETHNICITYWhite -0.001006   0.028308  -0.036  0.97168    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1043 on 161 degrees of freedom
Multiple R-squared:  0.2514,    Adjusted R-squared:  0.2188 
F-statistic: 7.723 on 7 and 161 DF,  p-value: 4.841e-08</code></pre>
</div>
</div>
<ul>
<li><p>A.20. The effect of ethnicity (<code>ETHNICITY</code>) on mean accuracy of understanding is not significant.</p></li>
<li><p>Q.21. Can you report the model and the model fit statistics?</p></li>
<li><p>A.21. You can report the model and model statistics like this.</p></li>
</ul>
<blockquote class="blockquote">
<p>We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (<code>HLVA</code>), vocabulary (<code>SHIPLEY</code>), reading strategy (<code>FACTOR3</code>), and ethnicity (<code>ETHNICITY</code>) as predictors. The model is significant overall, with F(7, 161) = 7.72, p&lt; .001, and explains 22% of variance (adjusted R2 = 0.22).</p>
</blockquote>
<ul>
<li><p>Q.22. What changes, when you compare the models with versus without <code>ETHNICITY</code>?</p></li>
<li><p>A.22. If you compare the summaries, for the last two models, you can see that the proportion of variance explained, <code>R-sq</code>, decreases slightly to 22% (Adjusted R-squared = 0.2188), suggesting that adding <code>ETHNICITY</code> as a predictor does <em>not</em> help to predict response accuracy in tests of comprehension of health advice.</p></li>
</ul>
</section>
<section id="why-are-we-learning-how-to-do-this-1" class="level4">
<h4 class="anchored" data-anchor-id="why-are-we-learning-how-to-do-this-1">Why are we learning how to do this?</h4>
<p>R handles factors, by default, by picking one level (here, <code>Asian</code>) as the reference level (or baseline) and comparing outcomes to that baseline, for each other factor level (here, <code>Other</code>).</p>
<ul>
<li>Thus, in this model, the effect of <code>ETHNICITY</code> is estimated as the difference in <code>mean.acc</code> outcome for <code>Asian</code> compared to participants coded as <code>Black, Mixed, Other, White</code> (BAME).</li>
</ul>
<p>There are different ways to code factors for analysis. You will learn about these in second year classes.</p>
</section>
</section>
<section id="task-13-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors-and-then-plot-the-predicted-effect-of-the-factor-the-categorical-variable" class="level3">
<h3 class="anchored" data-anchor-id="task-13-fit-a-linear-model-including-both-numeric-variables-and-categorical-variables-as-predictors-and-then-plot-the-predicted-effect-of-the-factor-the-categorical-variable">Task 13 – Fit a linear model including both numeric variables and categorical variables as predictors, and then plot the predicted effect of the factor (the categorical variable)</h3>
<section id="hint-task-12-we-first-fit-the-model-including-ethnicity-then-use-the-ggpredict-function-to-get-the-predictions" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-12-we-first-fit-the-model-including-ethnicity-then-use-the-ggpredict-function-to-get-the-predictions">Hint: Task 12 – We first fit the model, including <code>ETHNICITY</code>, then use the <code>ggpredict()</code> function to get the predictions</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3 <span class="sc">+</span> ETHNICITY, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> study.one.gen)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model, <span class="st">"ETHNICITY"</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w18-how-to_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Q.23. Compare the model summary and the prediction plot: what do they show you about the effect of <code>ETHNICITY</code>?</p></li>
<li><p>A.23. If you compare the summary and the plot you can see that:</p></li>
<li><p>there are some differences in accuracy between people coded as belonging to different ethnic groups;</p></li>
<li><p>but these differences are very small and are not significant.</p></li>
</ul>
<p>Notice that the points in the plot represent model predictions of the average <code>mean.acc</code> accuracy of response for each group.</p>
<ul>
<li>The vertical lines on the point represent uncertainty about those estimates and that uncertainty can be seen to be substantial.</li>
<li>Longer lines represent more uncertainty.</li>
</ul>


</section>
</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Website developed by Matthew Ivory</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../previous-content/index.html">
<p>Previous Content</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>