<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rob Davies">

<title>PSYC122-w18-workbook-answers – Statistics for Psychologists</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../Images/favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-ae99d8970fe14d16d849e9a6fc4cfcb4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 1";};</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<link rel="stylesheet" href="https://lu-psy-r.github.io/essentials/index_24.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="https://lu-psy-r.github.io/" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="https://lu-psy-r.github.io/">
    <span class="navbar-title">Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year1/index.html"> 
<span class="menu-text">Year 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year2/index.html"> 
<span class="menu-text">Year 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year3/index.html"> 
<span class="menu-text">Year 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/MSc/index.html"> 
<span class="menu-text">MSc</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/more/index.html"> 
<span class="menu-text">And More…</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">PSYC122-w18-workbook-answers</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../../index.html" class="sidebar-logo-link">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../PSYC121/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC121</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction to PSYC121</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Descriptive statistics in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. DVs and IVs in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Customisation of graphs, and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Class test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Sampling, probability and binomial tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Filtering data and testing means (one-sample t-test)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Related-samples t-tests, plotting means and SE bars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Unrelated-samples t-test and Power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../PSYC122/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC122</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Part 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Week 11 - Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Week 12 - Correlation Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Week 13 - The Linear Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Week 14 - Chi-Square</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Week 16 – Hypotheses, associations</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#naming-things" id="toc-naming-things" class="nav-link" data-scroll-target="#naming-things">Naming things</a></li>
  <li><a href="#the-data-we-will-be-using" id="toc-the-data-we-will-be-using" class="nav-link" data-scroll-target="#the-data-we-will-be-using">The data we will be using</a></li>
  </ul></li>
  <li><a href="#answers" id="toc-answers" class="nav-link" data-scroll-target="#answers">Answers</a>
  <ul class="collapse">
  <li><a href="#step-1-set-up" id="toc-step-1-set-up" class="nav-link" data-scroll-target="#step-1-set-up">Step 1: Set-up</a>
  <ul class="collapse">
  <li><a href="#task-1-run-code-to-empty-the-r-environment" id="toc-task-1-run-code-to-empty-the-r-environment" class="nav-link" data-scroll-target="#task-1-run-code-to-empty-the-r-environment">Task 1 – Run code to empty the R environment</a></li>
  <li><a href="#task-2-run-code-to-load-relevant-libraries" id="toc-task-2-run-code-to-load-relevant-libraries" class="nav-link" data-scroll-target="#task-2-run-code-to-load-relevant-libraries">Task 2 – Run code to load relevant libraries</a></li>
  </ul></li>
  <li><a href="#step-2-load-the-data" id="toc-step-2-load-the-data" class="nav-link" data-scroll-target="#step-2-load-the-data">Step 2: Load the data</a>
  <ul class="collapse">
  <li><a href="#task-3-read-in-the-data-file-we-will-be-using" id="toc-task-3-read-in-the-data-file-we-will-be-using" class="nav-link" data-scroll-target="#task-3-read-in-the-data-file-we-will-be-using">Task 3 – Read in the data file we will be using</a></li>
  <li><a href="#task-4-inspect-the-data-file" id="toc-task-4-inspect-the-data-file" class="nav-link" data-scroll-target="#task-4-inspect-the-data-file">Task 4 – Inspect the data file</a></li>
  </ul></li>
  <li><a href="#step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor" id="toc-step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor" class="nav-link" data-scroll-target="#step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor">Step 3: Use a linear model to to answer the research questions – one predictor</a>
  <ul class="collapse">
  <li><a href="#revise-practice-to-strengthen-skills" id="toc-revise-practice-to-strengthen-skills" class="nav-link" data-scroll-target="#revise-practice-to-strengthen-skills">Revise: practice to strengthen skills</a></li>
  <li><a href="#revise-we-start-by-revising-how-to-use-lm-with-one-predictor" id="toc-revise-we-start-by-revising-how-to-use-lm-with-one-predictor" class="nav-link" data-scroll-target="#revise-we-start-by-revising-how-to-use-lm-with-one-predictor">Revise: We start by revising how to use lm() with one predictor</a></li>
  <li><a href="#task-5-estimate-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-tested-accuracy-of-understanding-mean.acc" id="toc-task-5-estimate-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-tested-accuracy-of-understanding-mean.acc" class="nav-link" data-scroll-target="#task-5-estimate-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-tested-accuracy-of-understanding-mean.acc">Task 5 – Estimate the relation between outcome mean self-rated accuracy (<code>mean.self</code>) and tested accuracy of understanding (<code>mean.acc</code>)</a></li>
  <li><a href="#hint-task-5" id="toc-hint-task-5" class="nav-link" data-scroll-target="#hint-task-5">hint: Task 5</a></li>
  <li><a href="#hint-task-5-1" id="toc-hint-task-5-1" class="nav-link" data-scroll-target="#hint-task-5-1">hint: Task 5</a></li>
  </ul></li>
  <li><a href="#step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" id="toc-step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" class="nav-link" data-scroll-target="#step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors">Step 4: Use a linear model to to answer the research questions – multiple predictors</a>
  <ul class="collapse">
  <li><a href="#introduce-make-some-new-moves" id="toc-introduce-make-some-new-moves" class="nav-link" data-scroll-target="#introduce-make-some-new-moves">Introduce: make some new moves</a></li>
  <li><a href="#task-6-examine-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-multiple-predictors" id="toc-task-6-examine-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-multiple-predictors" class="nav-link" data-scroll-target="#task-6-examine-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-multiple-predictors">Task 6 – Examine the relation between outcome mean self-rated accuracy (<code>mean.self</code>) and multiple predictors</a></li>
  </ul></li>
  <li><a href="#step-5-understanding-linear-model-predictions-by-comparing-one-outcome-predictor-relation" id="toc-step-5-understanding-linear-model-predictions-by-comparing-one-outcome-predictor-relation" class="nav-link" data-scroll-target="#step-5-understanding-linear-model-predictions-by-comparing-one-outcome-predictor-relation">Step 5: Understanding linear model predictions by comparing one outcome-predictor relation</a></li>
  <li><a href="#step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables" id="toc-step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables" class="nav-link" data-scroll-target="#step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables">Step 6: Estimate the effects of factors as well as numeric variables</a>
  <ul class="collapse">
  <li><a href="#consolidation-build-your-skills" id="toc-consolidation-build-your-skills" class="nav-link" data-scroll-target="#consolidation-build-your-skills">Consolidation: build your skills</a></li>
  <li><a href="#task-7-fit-a-linear-model-to-examine-what-variables-predict-outcome-mean-self-rated-accuracy-of-mean.self" id="toc-task-7-fit-a-linear-model-to-examine-what-variables-predict-outcome-mean-self-rated-accuracy-of-mean.self" class="nav-link" data-scroll-target="#task-7-fit-a-linear-model-to-examine-what-variables-predict-outcome-mean-self-rated-accuracy-of-mean.self">Task 7 – Fit a linear model to examine what variables predict outcome mean self-rated accuracy of <code>mean.self</code></a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PSYC122-w18-workbook-answers</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rob Davies </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In Week 18, we aim to <em>further develop</em> skills in working with the linear model.</p>
<p>We do this to learn how to answer research questions like:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<p>These kinds of research questions can be answered using methods like the <strong>linear model</strong>.</p>
<p>When we do these analyses, we need to think about how we report the results:</p>
<ul>
<li>we usually need to report information about the kind of model we specify;</li>
<li>and we will need to report the nature of the association estimated in our model.</li>
</ul>
<p>We usually need to decide:</p>
<ul>
<li>is the association significant?</li>
<li>does the association reflect a positive or negative relationship between outcome and predictor?</li>
<li>and is the association we see in our sample data relatively strong or weak?</li>
</ul>
<p>We will consolidate and extend learning on data visualization:</p>
<ul>
<li>focusing on how we edit ggplot() code to produce professional looking plots.</li>
</ul>
<section id="naming-things" class="level2">
<h2 class="anchored" data-anchor-id="naming-things">Naming things</h2>
<p>I will format dataset names like this:</p>
<ul>
<li><code>study-two-general-participants.csv</code></li>
</ul>
<p>I will also format variable (data column) names like this: <code>variable</code></p>
<p>I will also format value or other data object (e.g.&nbsp;cell value) names like this: <code>studyone</code></p>
<p>I will format functions and library names like this: e.g.&nbsp;function <code>ggplot()</code> or e.g.&nbsp;library <code>{tidyverse}</code>.</p>
</section>
<section id="the-data-we-will-be-using" class="level2">
<h2 class="anchored" data-anchor-id="the-data-we-will-be-using">The data we will be using</h2>
<p>In this activity, we use data from <em>a second</em> 2020 study of the response of adults from a UK national sample to written health information:</p>
<ul>
<li><code>study-two-general-participants.csv</code></li>
</ul>
</section>
</section>
<section id="answers" class="level1">
<h1>Answers</h1>
<section id="step-1-set-up" class="level2">
<h2 class="anchored" data-anchor-id="step-1-set-up">Step 1: Set-up</h2>
<p>To begin, we set up our environment in R.</p>
<section id="task-1-run-code-to-empty-the-r-environment" class="level3">
<h3 class="anchored" data-anchor-id="task-1-run-code-to-empty-the-r-environment">Task 1 – Run code to empty the R environment</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())                            </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="task-2-run-code-to-load-relevant-libraries" class="level3">
<h3 class="anchored" data-anchor-id="task-2-run-code-to-load-relevant-libraries">Task 2 – Run code to load relevant libraries</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggeffects"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
</section>
</section>
<section id="step-2-load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="step-2-load-the-data">Step 2: Load the data</h2>
<section id="task-3-read-in-the-data-file-we-will-be-using" class="level3">
<h3 class="anchored" data-anchor-id="task-3-read-in-the-data-file-we-will-be-using">Task 3 – Read in the data file we will be using</h3>
<p>The data file is called:</p>
<ul>
<li><code>study-two-general-participants.csv</code></li>
</ul>
<p>Use the <code>read_csv()</code> function to read the data file into R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>study.two.gen <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"study-two-general-participants.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 172 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY
dbl (7): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3, QRITOTAL

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>When you read the data file in, give the data object you create a distinct name e.g.&nbsp;<code>study.two.gen</code>.</p>
</section>
<section id="task-4-inspect-the-data-file" class="level3">
<h3 class="anchored" data-anchor-id="task-4-inspect-the-data-file">Task 4 – Inspect the data file</h3>
<p>Use the <code>summary()</code> or <code>head()</code> functions to take a look.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(study.two.gen)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 12
  participant_ID mean.acc mean.self study     AGE SHIPLEY  HLVA FACTOR3 QRITOTAL
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
1 studytwo.1        0.411      6.07 studyt…    26      27     6      50        9
2 studytwo.10       0.607      8.5  studyt…    38      24     9      58       15
3 studytwo.100      0.875      8.93 studyt…    66      40    13      60       20
4 studytwo.101      0.964      8.5  studyt…    21      31    11      59       14
5 studytwo.102      0.714      7.07 studyt…    74      35     7      52       18
6 studytwo.103      0.768      5.07 studyt…    18      40    11      54       15
# ℹ 3 more variables: GENDER &lt;chr&gt;, EDUCATION &lt;chr&gt;, ETHNICITY &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(study.two.gen)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> participant_ID        mean.acc        mean.self        study          
 Length:172         Min.   :0.4107   Min.   :3.786   Length:172        
 Class :character   1st Qu.:0.6786   1st Qu.:6.411   Class :character  
 Mode  :character   Median :0.7679   Median :7.321   Mode  :character  
                    Mean   :0.7596   Mean   :7.101                     
                    3rd Qu.:0.8393   3rd Qu.:7.946                     
                    Max.   :0.9821   Max.   :9.000                     
      AGE           SHIPLEY           HLVA           FACTOR3     
 Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :29.00  
 1st Qu.:25.00   1st Qu.:32.75   1st Qu.: 7.750   1st Qu.:47.00  
 Median :32.50   Median :36.00   Median : 9.000   Median :51.00  
 Mean   :35.37   Mean   :35.13   Mean   : 9.064   Mean   :51.24  
 3rd Qu.:44.00   3rd Qu.:39.00   3rd Qu.:11.000   3rd Qu.:56.25  
 Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  
    QRITOTAL        GENDER           EDUCATION          ETHNICITY        
 Min.   : 6.00   Length:172         Length:172         Length:172        
 1st Qu.:12.00   Class :character   Class :character   Class :character  
 Median :14.00   Mode  :character   Mode  :character   Mode  :character  
 Mean   :13.88                                                           
 3rd Qu.:16.00                                                           
 Max.   :20.00                                                           </code></pre>
</div>
</div>
<p>Even though you have done this before, you will want to do it again, here, and pay particular attention to:</p>
<ul>
<li>summary information about the numeric variables;</li>
<li>summary information about variables of class: <code>character</code>.</li>
</ul>
</section>
</section>
<section id="step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor" class="level2">
<h2 class="anchored" data-anchor-id="step-3-use-a-linear-model-to-to-answer-the-research-questions-one-predictor">Step 3: Use a linear model to to answer the research questions – one predictor</h2>
<section id="revise-practice-to-strengthen-skills" class="level3">
<h3 class="anchored" data-anchor-id="revise-practice-to-strengthen-skills">Revise: practice to strengthen skills</h3>
</section>
<section id="revise-we-start-by-revising-how-to-use-lm-with-one-predictor" class="level3">
<h3 class="anchored" data-anchor-id="revise-we-start-by-revising-how-to-use-lm-with-one-predictor">Revise: We start by revising how to use lm() with one predictor</h3>
<p>One of our research questions is:</p>
<ol start="2" type="1">
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<p>We can address this question by examining whether someone’s rated evaluation of their own understanding matches their performance on a test of that understanding, and by investigating what variables predict variation in mean self-rated accuracy.</p>
<ul>
<li>Note that ratings of accuracy are ordinal data but that, here, we may choose to examine the average of participants’ ratings of their own understanding of health information to keep our analysis fairly simple.</li>
<li>For these data, participants were asked to respond to questions about health information to get <code>mean.acc</code> scores and then were asked to rate their own understanding of the same information.</li>
</ul>
<p>If you <em>can</em> evaluate your own understanding then ratings of understanding <em>should</em> be associated with performance on tests of understanding</p>
</section>
<section id="task-5-estimate-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-tested-accuracy-of-understanding-mean.acc" class="level3">
<h3 class="anchored" data-anchor-id="task-5-estimate-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-tested-accuracy-of-understanding-mean.acc">Task 5 – Estimate the relation between outcome mean self-rated accuracy (<code>mean.self</code>) and tested accuracy of understanding (<code>mean.acc</code>)</h3>
</section>
<section id="hint-task-5" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-5">hint: Task 5</h3>
<p>For these data, participants were asked to respond to questions about health information to get <code>mean.acc</code> scores and were asked to rate their own understanding of the same information.</p>
</section>
<section id="hint-task-5-1" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-5-1">hint: Task 5</h3>
<p>We can use <code>lm()</code> to estimate whether the ratings of accuracy actually predict the outcome tested accuracy levels.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.self <span class="sc">~</span> mean.acc, <span class="at">data =</span> study.two.gen)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.self ~ mean.acc, data = study.two.gen)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.47926 -0.62782  0.02038  0.65403  2.37788 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.8725     0.5037   5.703 5.12e-08 ***
mean.acc      5.5670     0.6550   8.499 9.36e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.032 on 170 degrees of freedom
Multiple R-squared:  0.2982,    Adjusted R-squared:  0.2941 
F-statistic: 72.24 on 1 and 170 DF,  p-value: 9.356e-15</code></pre>
</div>
</div>
<p>In R analysis code, we write <code>method(outcome ~ predictor)</code> so:</p>
<pre><code>lm(mean.self ~ mean.acc, data = study.two.gen)</code></pre>
<ul>
<li>gets us an analysis of whether or how <code>mean.self</code> predicts variation in outcome <code>mean.acc</code>.</li>
</ul>
<p>If you look at the model <code>summary</code> you can answer the following questions.</p>
<section id="questions-task-5" class="level4">
<h4 class="anchored" data-anchor-id="questions-task-5">Questions: Task 5</h4>
<ul>
<li><p>Q.1. What is the estimate for the coefficient of the effect of the predictor <code>mean.acc</code> on the outcome <code>mean.self</code> in this model?</p></li>
<li><p>A.1. 5.5670</p></li>
<li><p>Q.2. Is the effect significant?</p></li>
<li><p>A.2. It is significant, p &lt; .05</p></li>
<li><p>Q.3. What are the values for t and p for the significance test for the coefficient?</p></li>
<li><p>A.3. t = 8.499, p = 9.36e-15</p></li>
<li><p>Q.4. What do you conclude is the answer to the research question, given the linear model results?</p></li>
<li><p>A.4. The model slope estimate suggests that higher levels of tested understanding can predict higher levels of rated understanding so, yes: it does appear that people can evaluate their own understanding.</p></li>
<li><p>Q.5. What is the F-statistic for the regression? Report F, DF and the p-value.</p></li>
<li><p>A.5. F-statistic: 72.24 on 1 and 170 DF, p-value: 9.356e-15</p></li>
<li><p>Q.6. Is the regression significant?</p></li>
<li><p>A.6. Yes: the regression is significant.</p></li>
<li><p>Q.7. What is the Adjusted R-squared?</p></li>
<li><p>A.7. Adjusted R-squared: 0.2941</p></li>
<li><p>Q.8. Explain in words what this R-squared value indicates?</p></li>
<li><p>A.8. The R-squared suggests that about 30% of outcome variance can be explained by the model</p></li>
</ul>
</section>
</section>
</section>
<section id="step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" class="level2">
<h2 class="anchored" data-anchor-id="step-4-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors">Step 4: Use a linear model to to answer the research questions – multiple predictors</h2>
<section id="introduce-make-some-new-moves" class="level3">
<h3 class="anchored" data-anchor-id="introduce-make-some-new-moves">Introduce: make some new moves</h3>
<p>One of our research questions is:</p>
<ol start="2" type="1">
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<p>We have already looked at this question by asking whether ratings of understanding predict performance on tests of understanding.</p>
<p>But there is a problem with that analysis – it leaves open the question:</p>
<ul>
<li>What <em>actually</em> predicts ratings of understanding?</li>
</ul>
<p>We can look at this follow-up question, next.</p>
</section>
<section id="task-6-examine-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-multiple-predictors" class="level3">
<h3 class="anchored" data-anchor-id="task-6-examine-the-relation-between-outcome-mean-self-rated-accuracy-mean.self-and-multiple-predictors">Task 6 – Examine the relation between outcome mean self-rated accuracy (<code>mean.self</code>) and multiple predictors</h3>
<p>Here, the predictors will include:</p>
<ul>
<li>health literacy (<code>HLVA</code>);</li>
<li>vocabulary (<code>SHIPLEY</code>);</li>
<li>age in years (<code>AGE</code>);</li>
<li>reading strategy (<code>FACTOR3</code>);</li>
<li>as well as average accuracy of the tested understanding of health information (<code>mean.acc</code>).</li>
</ul>
<section id="hint-task-6-we-use-lm-as-before-but-now-specify-each-variable-listed-here-by-variable-name" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-6-we-use-lm-as-before-but-now-specify-each-variable-listed-here-by-variable-name">hint: Task 6 – We use <code>lm()</code>, as before, but now specify each variable listed here by variable name</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.self <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3 <span class="sc">+</span> AGE <span class="sc">+</span> mean.acc, </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> study.two.gen)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.self ~ HLVA + SHIPLEY + FACTOR3 + AGE + mean.acc, 
    data = study.two.gen)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.72027 -0.49118 -0.00177  0.55561  2.00134 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.561110   0.700632   0.801   0.4244    
HLVA         0.041272   0.034833   1.185   0.2378    
SHIPLEY     -0.046125   0.018701  -2.466   0.0147 *  
FACTOR3      0.063689   0.010747   5.926 1.74e-08 ***
AGE          0.025570   0.005472   4.673 6.12e-06 ***
mean.acc     4.763278   0.708166   6.726 2.69e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8805 on 166 degrees of freedom
Multiple R-squared:  0.5014,    Adjusted R-squared:  0.4864 
F-statistic: 33.39 on 5 and 166 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="questions-task-6" class="level4">
<h4 class="anchored" data-anchor-id="questions-task-6">Questions: Task 6</h4>
<p>If you look at the model summary you can answer the following questions.</p>
<ul>
<li><p>Q.9. What predictors are significant in this model?</p></li>
<li><p>A.9. Vocabulary (<code>SHIPLEY</code>), reading strategy (<code>FACTOR3</code>), <code>AGE</code>, and performance on tests of accuracy of understanding (<code>mean.acc</code>) all appear to significantly predict variation in mean ratings of understanding (<code>mean.self</code>).</p></li>
<li><p>Q.10. What is the estimate for the coefficient of the effect of the predictor <code>mean.acc</code> in this model?</p></li>
<li><p>A.10. 4.763278</p></li>
<li><p>Q.11. Is the effect significant?</p></li>
<li><p>A.11. It is significant, p &lt; .05</p></li>
<li><p>Q.12. What are the values for t and p for the significance test for the coefficient?</p></li>
<li><p>A.12. t = 6.726, p = 2.69e-10</p></li>
<li><p>Q.13. What do you conclude is the answer to the follow-up question, what actually predicts ratings of understanding?</p></li>
<li><p>A.13. Ratings of understanding appear to be predicted by performance on tests of accuracy of understanding, together with variation in age, vocabulary knowledge, health literacy and reading strategy</p></li>
</ul>
</section>
</section>
</section>
<section id="step-5-understanding-linear-model-predictions-by-comparing-one-outcome-predictor-relation" class="level2">
<h2 class="anchored" data-anchor-id="step-5-understanding-linear-model-predictions-by-comparing-one-outcome-predictor-relation">Step 5: Understanding linear model predictions by comparing one outcome-predictor relation</h2>
<p>Next, we focus in on whether <code>mean.self</code> predicts <code>mean.acc</code> or, in reverse, whether <code>mean.acc</code> predicts <code>mean.self</code>?</p>
<ul>
<li><p>Note that a comparison between these models teaches us something important about <em>what</em> it is that linear models predict.</p></li>
<li><p>Q.14. Why do you think it appears that the slope coefficient estimate is different if you compare :</p></li>
</ul>
<ol type="1">
<li>The model <code>mean.acc ~ mean.self</code> versus</li>
<li>The model <code>mean.self ~ mean.acc</code>?</li>
</ol>
<ul>
<li>hint: Q.14. You want to fit two simple models here, using the verbal description in the Q.14 wording.</li>
</ul>
<p><strong>1. The model <code>mean.acc ~ mean.self</code></strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> mean.self, <span class="at">data =</span> study.two.gen)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ mean.self, data = study.two.gen)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.293692 -0.069200  0.005422  0.080041  0.215240 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.379182   0.045415   8.349 2.31e-14 ***
mean.self   0.053566   0.006303   8.499 9.36e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1013 on 170 degrees of freedom
Multiple R-squared:  0.2982,    Adjusted R-squared:  0.2941 
F-statistic: 72.24 on 1 and 170 DF,  p-value: 9.356e-15</code></pre>
</div>
</div>
<p><strong>2. The model <code>mean.self ~ mean.acc</code></strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.self <span class="sc">~</span> mean.acc, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> study.two.gen)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.self ~ mean.acc, data = study.two.gen)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.47926 -0.62782  0.02038  0.65403  2.37788 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.8725     0.5037   5.703 5.12e-08 ***
mean.acc      5.5670     0.6550   8.499 9.36e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.032 on 170 degrees of freedom
Multiple R-squared:  0.2982,    Adjusted R-squared:  0.2941 
F-statistic: 72.24 on 1 and 170 DF,  p-value: 9.356e-15</code></pre>
</div>
</div>
<ul>
<li><p>hint: Q.14. You may benefit here by reflecting on the <code>lm-intro</code> lecture and practical materials, especially where they concern predictions.</p></li>
<li><p>A.14. Linear models are prediction models. We use them to predict variation in outcomes given some set of predictor variables. Predictions will necessarily be <em>scaled</em> in the same way as the outcome variable.</p></li>
</ul>
<p>So, to expand on that explanation a bit more, to help understanding – the answer is:</p>
<ol type="1">
<li>If we have the model, <code>mean.acc ~ mean.self</code> then this means that the outcome is <code>mean.acc</code>.</li>
</ol>
<ul>
<li>So if we are predicting change in outcome <code>mean.acc</code>, which is <strong>scaled 0-1</strong>, then we are looking at coefficients that will lie somewhere on the same scale (also 0-1).</li>
<li>Here: the model estimate suggests that each unit change in values of the variable <code>mean.self</code> predicts an increase of 0.053566 in <code>mean.acc</code>.</li>
</ul>
<ol start="2" type="1">
<li>Whereas if we have the model, <code>mean.self ~ mean.acc</code> then this means that the outcome is <code>mean.self</code>.</li>
</ol>
<ul>
<li>So if we are predicting change in outcome <code>mean.self</code>, which is <strong>scaled 1-9</strong> , then we are looking at coefficients that will lie somewhere on the same scale (also 1-9).</li>
<li>Here: the model estimate suggests that unit change in <code>mean.acc</code> predicts increase of 5.5670 in <code>mean.self</code>.</li>
</ul>
<p>Note that:</p>
<ul>
<li>Where we reference model estimates, here, we are looking at the values in the <code>Estimate</code> column of the <code>lm()</code> model summary.</li>
<li>These estimates give us the expected or predicted change in the outcome, given change in the predictor variable named on that row.</li>
</ul>
<p>Remember that:</p>
<ul>
<li><code>mean.acc</code> is scaled from 0 to 1 because it represents the average accuracy of the responses made by study participants to questions about health texts. This average <em>has</em> to have a minimum of 0 (no responses correct) and a maximum of 1 (all responses correct). The average is calculated by adding up all the correct answers and dividing by the number of questions answered by each participant.</li>
<li><code>mean.self</code> is scaled from 1 to 9 bcause it represents the average self-rated accuracy of understanding. Participants are asked to rate on a scale form 1 (not all) to 9 (very well) how well they think they understand a health information text. The average is calculated by adding up all the ratings and dividing by the number of texts responded to by each participant.</li>
</ul>
<p>The <strong>important lesson</strong>, here, is that estimates of predictor effects are scaled in terms of predicted change in the outcome, so whatever scale the outcome measurement is in determines how big or small the predictor coefficient estimates can be.</p>
<p>We can visualize this to see what it means in practice.</p>
<ul>
<li><p>Q.15. Can you plot the predictions from each model?</p></li>
<li><p>A.15. Here is the code to plot the predictions from both models.</p></li>
</ul>
<p><strong>First</strong> fit the models.</p>
<ul>
<li>Remember to give each model object distinct names.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> mean.self, <span class="at">data =</span> study.two.gen)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ mean.self, data = study.two.gen)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.293692 -0.069200  0.005422  0.080041  0.215240 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.379182   0.045415   8.349 2.31e-14 ***
mean.self   0.053566   0.006303   8.499 9.36e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1013 on 170 degrees of freedom
Multiple R-squared:  0.2982,    Adjusted R-squared:  0.2941 
F-statistic: 72.24 on 1 and 170 DF,  p-value: 9.356e-15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.self <span class="sc">~</span> mean.acc, </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> study.two.gen)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.self ~ mean.acc, data = study.two.gen)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.47926 -0.62782  0.02038  0.65403  2.37788 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.8725     0.5037   5.703 5.12e-08 ***
mean.acc      5.5670     0.6550   8.499 9.36e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.032 on 170 degrees of freedom
Multiple R-squared:  0.2982,    Adjusted R-squared:  0.2941 
F-statistic: 72.24 on 1 and 170 DF,  p-value: 9.356e-15</code></pre>
</div>
</div>
<p><strong>Second</strong> get the predictions:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model<span class="fl">.1</span>, <span class="st">"mean.self"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model<span class="fl">.2</span>, <span class="st">"mean.acc"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Third</strong> make the prediction plots:</p>
<ol type="1">
<li>Predictions from the model <code>mean.acc ~ mean.self</code></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PSYC122-w18-workbook-answers_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol type="1">
<li>Predictions from the model <code>mean.self ~ mean.acc</code></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="fl">.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PSYC122-w18-workbook-answers_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Q.16. Look at the two plots: what do you see?</p></li>
<li><p>hint: Q.16. Look at changes in height of the prediction line, given changes in x-axis position of the line</p></li>
<li><p>A.16. A side-by-side comparison shows that:</p></li>
</ul>
<ol type="1">
<li>For model <code>mean.acc ~ mean.self</code> increases in <code>mean.self</code> from about 4 to 9 are associated with a change in <code>mean.acc</code> from about .6 to about .85;</li>
<li>For model <code>mean.self ~ mean.acc</code> increases in <code>mean.acc</code> from about 0.4 to 1.0 are associated with a change in <code>mean.self</code> from about 5 to about 9.</li>
</ol>
</section>
<section id="step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables" class="level2">
<h2 class="anchored" data-anchor-id="step-6-estimate-the-effects-of-factors-as-well-as-numeric-variables">Step 6: Estimate the effects of factors as well as numeric variables</h2>
<section id="consolidation-build-your-skills" class="level3">
<h3 class="anchored" data-anchor-id="consolidation-build-your-skills">Consolidation: build your skills</h3>
<p>We have not yet included any categorical or nominal variables as predictors but we can, and should: <code>lm()</code> can cope with any kind of variable as a predictor.</p>
<p>There are different ways to do this, here we ask you to use the R default method.</p>
</section>
<section id="task-7-fit-a-linear-model-to-examine-what-variables-predict-outcome-mean-self-rated-accuracy-of-mean.self" class="level3">
<h3 class="anchored" data-anchor-id="task-7-fit-a-linear-model-to-examine-what-variables-predict-outcome-mean-self-rated-accuracy-of-mean.self">Task 7 – Fit a linear model to examine what variables predict outcome mean self-rated accuracy of <code>mean.self</code></h3>
<section id="hint-task-7-include-as-predictors-both-numeric-variables-and-categorical-variables" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-7-include-as-predictors-both-numeric-variables-and-categorical-variables">hint: Task 7 – Include as predictors both numeric variables and categorical variables</h4>
<p>Here, our model includes predictors that are both numeric like:</p>
<ul>
<li>health literacy (<code>HLVA</code>);</li>
<li>vocabulary (<code>SHIPLEY</code>);</li>
<li><code>AGE</code>;</li>
<li>reading strategy (<code>FACTOR3</code>);</li>
<li>accuracy <code>mean.acc</code></li>
</ul>
<p>As well as a categorical or nominal variable like</p>
<ul>
<li><code>EDUCATION</code>.</li>
</ul>
<p>Note: <code>EDUCATION</code> is different because participants are classified by what education category (<code>higher education, further education, secondary school</code>) they report themselves as having received.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.self <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3 <span class="sc">+</span> AGE <span class="sc">+</span> mean.acc <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>                        EDUCATION, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> study.two.gen)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.self ~ HLVA + SHIPLEY + FACTOR3 + AGE + mean.acc + 
    EDUCATION, data = study.two.gen)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.70987 -0.50037  0.01988  0.55965  2.01412 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         0.487753   0.702049   0.695   0.4882    
HLVA                0.047100   0.034915   1.349   0.1792    
SHIPLEY            -0.044132   0.018719  -2.358   0.0196 *  
FACTOR3             0.061918   0.010771   5.749 4.29e-08 ***
AGE                 0.023997   0.005595   4.289 3.06e-05 ***
mean.acc            4.912833   0.712381   6.896 1.10e-10 ***
EDUCATIONHigher    -0.082217   0.146390  -0.562   0.5751    
EDUCATIONSecondary  0.346161   0.266030   1.301   0.1950    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8783 on 164 degrees of freedom
Multiple R-squared:  0.5099,    Adjusted R-squared:  0.489 
F-statistic: 24.38 on 7 and 164 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>Q.17. Can you report the overall model and model fit statistics?</p></li>
<li><p>A.17.</p></li>
</ul>
<blockquote class="blockquote">
<p>We fitted a linear model with mean self-rated accuracy as the outcome and with the predictors: health literacy (<code>HLVA</code>), vocabulary (<code>SHIPLEY</code>), reading strategy (<code>FACTOR3</code>), <code>AGE</code>, as well as mean accuracy (<code>mean.acc</code>) and education level (<code>EDUCATION</code>). The model is significant overall, with F(7, 164) = 24.38, p &lt; .001, and explains 49% of variance (adjusted R2 = 0.489).</p>
</blockquote>
<ul>
<li><p>Q.18. Can you plot the predicted effect of <code>EDUCATION</code> given your model?</p></li>
<li><p>hint: Q.18. We first fit the model, including <code>EDUCATION</code>.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.self <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3 <span class="sc">+</span> AGE <span class="sc">+</span> mean.acc <span class="sc">+</span> EDUCATION, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> study.two.gen)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>hint: Q.18. We then use the <code>ggpredict()</code> function to get the prediction for the effect of <code>EDUCATION</code> differences on outcome <code>mean.self</code>.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model, <span class="st">"EDUCATION"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Some of the focal terms are of type `character`. This may lead to
  unexpected results. It is recommended to convert these variables to
  factors before fitting the model.
  The following variables are of type character: `EDUCATION`</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PSYC122-w18-workbook-answers_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Q.19. The plot should give you dot-and-whisker representations of the estimated <code>mean.self</code> outcome for different levels of <code>EDUCATION</code>. What is the difference in the estimated <code>mean.self</code> between the groups?</p></li>
<li><p>hint: Q.19. The effect or prediction plot will show you <strong>dot-and-whisker</strong> representations of predicted outcome <code>mean.self</code>. In these plots, the dots represent the estimated <code>mean.self</code> while the lines (whiskers) represent confidence intervals.</p></li>
<li><p>A.19. The difference in the estimated <code>mean.self</code> between these groups is small: the groups vary between ratings of about 7, 7.10 and 7.5.</p></li>
<li><p>Q.20. Compare the difference in the estimated <code>mean.self</code> between these groups, given the plot, with the coefficient estimate from the model summary: what do you see?</p></li>
<li><p>A.20. The effect of <code>EDUCATION</code> is presented in the summary as two estimates:</p></li>
<li><p><code>EDUCATIONHigher    -0.082217</code></p></li>
<li><p><code>EDUCATIONSecondary  0.346161</code></p></li>
</ul>
<p>The reference level for <code>EDUCATION</code> is <code>Further</code>.</p>
<p>The estimates therefore show that people with <code>Higher</code> education have <code>mean.self</code> scores about -.08 lower than <code>mean.self</code> for people with <code>Further</code> education.</p>
<p>People with <code>Secondary</code> education have <code>mean.self</code> scores about .35 higher than <code>mean.self</code> for people with <code>Further</code> education.</p>
<p>We are learning some new things here so it is useful to explain them:</p>
<ol type="1">
<li>Categorical variables or <strong>factors</strong> and reference levels.</li>
</ol>
<ul>
<li>If you have a categorical variable like <code>EDUCATION</code> then when you use it in an analysis, R will look at the different categories (called <code>levels) e.g., here,</code>higher education, further education, secondary school` and it will pick one level to be the <em>reference</em> or baseline level.</li>
<li>The <em>reference</em> is the the level against which other levels are compared.</li>
<li>Here, the reference level is <code>Further</code> (education) simply because, unless you tell R otherwise, it picks the level with a category name that begins earlier in the alphabet as the reference level.</li>
</ul>
<ol start="2" type="1">
<li>Dot and whisker plots show estimates with confidence intervals.</li>
</ol>
<ul>
<li>Dot and whisker plots are a nice way to present a concise visual summary about the estimates we get from prediction models.</li>
<li>Here, the plots show the coefficient estimates from our model (the dots) plus confidence intervals (the lines or “whiskers”).</li>
</ul>
<ol start="3" type="1">
<li>Confidence intervals are often misunderstood but they are helpful.</li>
</ol>
<ul>
<li>Essentially, a confidence interval tells us about we might expect to see using our analysis procedure (Hoekstra et al., 2014).</li>
</ul>
<blockquote class="blockquote">
<p>If we were to repeat the experiment over and over, then 95 % of the time the confidence intervals contain the true mean.</p>
</blockquote>
<ul>
<li>And you can read more about this here</li>
</ul>
<p>Hoekstra, R., Morey, R. D., Rouder, J. N., &amp; Wagenmakers, E. J. (2014). Robust misinterpretation of confidence intervals. <em>Psychonomic Bulletin &amp; Review</em>, 21, 1157-1164.</p>


</section>
</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Website developed by Matthew Ivory</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../previous-content/index.html">
<p>Previous Content</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>