<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rob Davies">
<meta name="dcterms.date" content="2024-03-12">

<title>2023-24-PSYC122-w19-workbook-answers – Statistics for Psychologists</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../Images/favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 1";};</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<link rel="stylesheet" href="https://lu-psy-r.github.io/essentials/index_24.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="https://lu-psy-r.github.io/">
    <span class="navbar-title">Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year1/index.html"> 
<span class="menu-text">Year 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year2/index.html"> 
<span class="menu-text">Year 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year3/index.html"> 
<span class="menu-text">Year 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/MSc/index.html"> 
<span class="menu-text">MSc</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/more/index.html"> 
<span class="menu-text">And More…</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">2023-24-PSYC122-w19-workbook-answers</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../PSYC121/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC121</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistics for Psychologists</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Descriptive statistics in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. DVs and IVs in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Customisation of graphs, and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Class test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Sampling, probability and binomial tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Filtering data and testing means (one-sample t-test)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Related-samples t-tests, plotting means and SE bars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Unrelated-samples t-test and Power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../PSYC122/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC122</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Week 11 - Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Week 12 - Correlation Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Week 13 - The Linear Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Week 14 - Chi-Square</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Week 16 – Hypotheses, associations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Week 17 – Better understanding the linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Week 18 – Developing the linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Week 19 – Linear models – critical perspectives</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#naming-things" id="toc-naming-things" class="nav-link" data-scroll-target="#naming-things">Naming things</a></li>
  <li><a href="#the-data-we-will-be-using" id="toc-the-data-we-will-be-using" class="nav-link" data-scroll-target="#the-data-we-will-be-using">The data we will be using</a></li>
  </ul></li>
  <li><a href="#answers" id="toc-answers" class="nav-link" data-scroll-target="#answers">Answers</a>
  <ul class="collapse">
  <li><a href="#step-1-set-up" id="toc-step-1-set-up" class="nav-link" data-scroll-target="#step-1-set-up">Step 1: Set-up</a>
  <ul class="collapse">
  <li><a href="#task-1-run-code-to-empty-the-r-environment" id="toc-task-1-run-code-to-empty-the-r-environment" class="nav-link" data-scroll-target="#task-1-run-code-to-empty-the-r-environment">Task 1 – Run code to empty the R environment</a></li>
  <li><a href="#task-2-run-code-to-load-relevant-libraries" id="toc-task-2-run-code-to-load-relevant-libraries" class="nav-link" data-scroll-target="#task-2-run-code-to-load-relevant-libraries">Task 2 – Run code to load relevant libraries</a></li>
  </ul></li>
  <li><a href="#step-2-load-the-data" id="toc-step-2-load-the-data" class="nav-link" data-scroll-target="#step-2-load-the-data">Step 2: Load the data</a>
  <ul class="collapse">
  <li><a href="#task-3-read-in-the-data-files-we-will-be-using" id="toc-task-3-read-in-the-data-files-we-will-be-using" class="nav-link" data-scroll-target="#task-3-read-in-the-data-files-we-will-be-using">Task 3 – Read in the data files we will be using</a></li>
  <li><a href="#task-4-inspect-the-data-file" id="toc-task-4-inspect-the-data-file" class="nav-link" data-scroll-target="#task-4-inspect-the-data-file">Task 4 – Inspect the data file</a></li>
  </ul></li>
  <li><a href="#step-3-compare-the-data-from-the-different-studies" id="toc-step-3-compare-the-data-from-the-different-studies" class="nav-link" data-scroll-target="#step-3-compare-the-data-from-the-different-studies">Step 3: Compare the data from the different studies</a>
  <ul class="collapse">
  <li><a href="#revise-practice-to-strengthen-skills" id="toc-revise-practice-to-strengthen-skills" class="nav-link" data-scroll-target="#revise-practice-to-strengthen-skills">Revise: practice to strengthen skills</a></li>
  <li><a href="#task-5-compare-the-data-distributions-from-the-two-studies" id="toc-task-5-compare-the-data-distributions-from-the-two-studies" class="nav-link" data-scroll-target="#task-5-compare-the-data-distributions-from-the-two-studies">Task 5 – Compare the data distributions from the two studies</a></li>
  <li><a href="#introduce-make-some-new-moves" id="toc-introduce-make-some-new-moves" class="nav-link" data-scroll-target="#introduce-make-some-new-moves">Introduce: make some new moves</a></li>
  <li><a href="#task-6-create-grids-of-plots-to-make-the-comparison-easier-to-do" id="toc-task-6-create-grids-of-plots-to-make-the-comparison-easier-to-do" class="nav-link" data-scroll-target="#task-6-create-grids-of-plots-to-make-the-comparison-easier-to-do">Task 6 – Create grids of plots to make the comparison easier to do</a></li>
  <li><a href="#hint-task-6-what-we-are-going-to-do-is-to-create-two-histograms-and-then-present-them-side-by-side-to-allow-easy-comparison-of-variable-distributions" id="toc-hint-task-6-what-we-are-going-to-do-is-to-create-two-histograms-and-then-present-them-side-by-side-to-allow-easy-comparison-of-variable-distributions" class="nav-link" data-scroll-target="#hint-task-6-what-we-are-going-to-do-is-to-create-two-histograms-and-then-present-them-side-by-side-to-allow-easy-comparison-of-variable-distributions">hint: Task 6 – What we are going to do is to create two histograms and then present them side by side to allow easy comparison of variable distributions</a></li>
  <li><a href="#task-7-try-this-out-for-yourself-focusing-now-on-the-distribution-of-shipley-scores-in-the-two-studies" id="toc-task-7-try-this-out-for-yourself-focusing-now-on-the-distribution-of-shipley-scores-in-the-two-studies" class="nav-link" data-scroll-target="#task-7-try-this-out-for-yourself-focusing-now-on-the-distribution-of-shipley-scores-in-the-two-studies">Task 7 – Try this out for yourself, focusing now on the distribution of <code>SHIPLEY</code> scores in the two studies</a></li>
  </ul></li>
  <li><a href="#step-4-now-use-scatterplots-and-correlation-to-examine-associations-between-variables" id="toc-step-4-now-use-scatterplots-and-correlation-to-examine-associations-between-variables" class="nav-link" data-scroll-target="#step-4-now-use-scatterplots-and-correlation-to-examine-associations-between-variables">Step 4: Now use scatterplots and correlation to examine associations between variables</a>
  <ul class="collapse">
  <li><a href="#revise-practice-to-strengthen-skills-1" id="toc-revise-practice-to-strengthen-skills-1" class="nav-link" data-scroll-target="#revise-practice-to-strengthen-skills-1">Revise: practice to strengthen skills</a></li>
  <li><a href="#task-8-draw-scatterplots-to-compare-the-potential-association-between-mean.acc-and-mean.self-in-both-study.two.gen-and-study.122-datasets" id="toc-task-8-draw-scatterplots-to-compare-the-potential-association-between-mean.acc-and-mean.self-in-both-study.two.gen-and-study.122-datasets" class="nav-link" data-scroll-target="#task-8-draw-scatterplots-to-compare-the-potential-association-between-mean.acc-and-mean.self-in-both-study.two.gen-and-study.122-datasets">Task 8 – Draw scatterplots to compare the potential association between <code>mean.acc</code> and <code>mean.self</code> in both <code>study.two.gen</code> and <code>study.122</code> datasets</a></li>
  <li><a href="#hint-task-8-the-plotting-steps-are-explained-in-some-detail-in-2023-24-psyc122-w17-how-to.rmd-and-you-can-see-example-code-in-2023-24-psyc122-w19-how-to.rmd" id="toc-hint-task-8-the-plotting-steps-are-explained-in-some-detail-in-2023-24-psyc122-w17-how-to.rmd-and-you-can-see-example-code-in-2023-24-psyc122-w19-how-to.rmd" class="nav-link" data-scroll-target="#hint-task-8-the-plotting-steps-are-explained-in-some-detail-in-2023-24-psyc122-w17-how-to.rmd-and-you-can-see-example-code-in-2023-24-psyc122-w19-how-to.rmd">hint: Task 8 – The plotting steps are explained in some detail in <code>2023-24-PSYC122-w17-how-to.Rmd</code> and you can see example code in <code>2023-24-PSYC122-w19-how-to.Rmd</code></a></li>
  <li><a href="#task-9-create-a-grid-of-plots-to-make-the-comparison-easier-to-do" id="toc-task-9-create-a-grid-of-plots-to-make-the-comparison-easier-to-do" class="nav-link" data-scroll-target="#task-9-create-a-grid-of-plots-to-make-the-comparison-easier-to-do">Task 9 – Create a grid of plots to make the comparison easier to do</a></li>
  <li><a href="#hint-task-9-we-follow-the-same-steps-as-we-used-in-tasks-6-and-7-to-create-the-plots" id="toc-hint-task-9-we-follow-the-same-steps-as-we-used-in-tasks-6-and-7-to-create-the-plots" class="nav-link" data-scroll-target="#hint-task-9-we-follow-the-same-steps-as-we-used-in-tasks-6-and-7-to-create-the-plots">hint: Task 9 – We follow the same steps as we used in tasks 6 and 7 to create the plots</a></li>
  <li><a href="#revise-practice-to-strengthen-skills-2" id="toc-revise-practice-to-strengthen-skills-2" class="nav-link" data-scroll-target="#revise-practice-to-strengthen-skills-2">Revise: practice to strengthen skills</a></li>
  <li><a href="#task-10-can-you-estimate-the-association-between-mean.acc-and-mean.self-in-both-datasets" id="toc-task-10-can-you-estimate-the-association-between-mean.acc-and-mean.self-in-both-datasets" class="nav-link" data-scroll-target="#task-10-can-you-estimate-the-association-between-mean.acc-and-mean.self-in-both-datasets">Task 10 – Can you estimate the association between <code>mean.acc</code> and <code>mean.self</code> in both datasets?</a></li>
  <li><a href="#hint-task-10-we-use-cor.test-as-you-have-been-shown-how-to-do-e.g.-in-2023-24-psyc122-w16-how-to.rmd" id="toc-hint-task-10-we-use-cor.test-as-you-have-been-shown-how-to-do-e.g.-in-2023-24-psyc122-w16-how-to.rmd" class="nav-link" data-scroll-target="#hint-task-10-we-use-cor.test-as-you-have-been-shown-how-to-do-e.g.-in-2023-24-psyc122-w16-how-to.rmd">hint: Task 10 – We use <code>cor.test()</code> as you have been shown how to do e.g.&nbsp;in <code>2023-24-PSYC122-w16-how-to.Rmd</code></a></li>
  <li><a href="#task-11-in-working-with-r-to-do-data-analysis-we-often-work-with-libraries-of-function-like-tidyverse-that-enable-us-to-do-things-see-the-week-19-lecture-for-discussion." id="toc-task-11-in-working-with-r-to-do-data-analysis-we-often-work-with-libraries-of-function-like-tidyverse-that-enable-us-to-do-things-see-the-week-19-lecture-for-discussion." class="nav-link" data-scroll-target="#task-11-in-working-with-r-to-do-data-analysis-we-often-work-with-libraries-of-function-like-tidyverse-that-enable-us-to-do-things-see-the-week-19-lecture-for-discussion.">Task 11 – In working with R to do data analysis, we often work with libraries of function like <code>{tidyverse}</code> that enable us to do things (see the week 19 lecture for discussion).</a></li>
  <li><a href="#hint-task-11-to-find-out-more-information-about-a-function-or-a-library-in-r-do-a-search-for-the-keywords" id="toc-hint-task-11-to-find-out-more-information-about-a-function-or-a-library-in-r-do-a-search-for-the-keywords" class="nav-link" data-scroll-target="#hint-task-11-to-find-out-more-information-about-a-function-or-a-library-in-r-do-a-search-for-the-keywords">hint: Task 11 – To find out more information about a function or a library in R, do a search for the keywords</a></li>
  </ul></li>
  <li><a href="#step-5-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" id="toc-step-5-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" class="nav-link" data-scroll-target="#step-5-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors">Step 5: Use a linear model to to answer the research questions – multiple predictors</a>
  <ul class="collapse">
  <li><a href="#revise-practice-to-strengthen-skills-3" id="toc-revise-practice-to-strengthen-skills-3" class="nav-link" data-scroll-target="#revise-practice-to-strengthen-skills-3">Revise: practice to strengthen skills</a></li>
  <li><a href="#task-12-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors" id="toc-task-12-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors" class="nav-link" data-scroll-target="#task-12-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors">Task 12 – Examine the relation between outcome mean accuracy (<code>mean.acc</code>) and multiple predictors</a></li>
  <li><a href="#hint-task-12-we-use-lm-as-we-have-been-doing-before-see-e.g.-2023-24-psyc122-w18-how-to.r" id="toc-hint-task-12-we-use-lm-as-we-have-been-doing-before-see-e.g.-2023-24-psyc122-w18-how-to.r" class="nav-link" data-scroll-target="#hint-task-12-we-use-lm-as-we-have-been-doing-before-see-e.g.-2023-24-psyc122-w18-how-to.r">hint: Task 12 – We use <code>lm()</code>, as we have been doing before, see e.g.&nbsp;<code>2023-24-PSYC122-w18-how-to.R</code></a></li>
  <li><a href="#task-12-examine-the-predictors-of-mean-accuracy-mean.acc-first-for-the-study.two.gen-data" id="toc-task-12-examine-the-predictors-of-mean-accuracy-mean.acc-first-for-the-study.two.gen-data" class="nav-link" data-scroll-target="#task-12-examine-the-predictors-of-mean-accuracy-mean.acc-first-for-the-study.two.gen-data">Task 12 – Examine the predictors of mean accuracy (<code>mean.acc</code>), first, for the <code>study.two.gen</code> data</a></li>
  <li><a href="#task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data" id="toc-task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data" class="nav-link" data-scroll-target="#task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data">Task 13 – Examine the predictors of mean accuracy (<code>mean.acc</code>), now, for the <code>study.122</code> data</a></li>
  <li><a href="#task-14-in-producing-prediction-plots-we-are-using-functions-from-the-ggefects-library.-can-you-locate-online-information-about-working-with-the-library-functions" id="toc-task-14-in-producing-prediction-plots-we-are-using-functions-from-the-ggefects-library.-can-you-locate-online-information-about-working-with-the-library-functions" class="nav-link" data-scroll-target="#task-14-in-producing-prediction-plots-we-are-using-functions-from-the-ggefects-library.-can-you-locate-online-information-about-working-with-the-library-functions">Task 14 – In producing prediction plots, we are using functions from the <code>{ggefects}</code> library. Can you locate online information about working with the library functions?</a></li>
  <li><a href="#task-15-in-the-ggeffects-online-information-you-can-see-links-to-practical-examples.-can-you-use-the-information-under-practical-examples-to-adjust-the-appearance-of-the-prediction-plots-to-make-them-black-and-white-to-add-points" id="toc-task-15-in-the-ggeffects-online-information-you-can-see-links-to-practical-examples.-can-you-use-the-information-under-practical-examples-to-adjust-the-appearance-of-the-prediction-plots-to-make-them-black-and-white-to-add-points" class="nav-link" data-scroll-target="#task-15-in-the-ggeffects-online-information-you-can-see-links-to-practical-examples.-can-you-use-the-information-under-practical-examples-to-adjust-the-appearance-of-the-prediction-plots-to-make-them-black-and-white-to-add-points">Task 15 – In the <code>{ggeffects}</code> online information, you can see links to practical examples. Can you use the information under “Practical examples” to adjust the appearance of the prediction plots: to make them black and white; to add points?</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">2023-24-PSYC122-w19-workbook-answers</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rob Davies </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 12, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In Week 19, we aim to <em>further develop</em> skills in working with the linear model.</p>
<p>We do this to learn how to answer research questions like:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<p>In Week 19, we use data contributed by PSYC122 students to figure out our answers to these questions.</p>
<p>We compare PSYC122 results to the results from a previous study so that we can assess the robustness of our findings.</p>
<p>In this class, what is new is our focus on critically evaluating – comparing, reflecting on – the evidence from more than one relevant study.</p>
<ul>
<li>This work simulates the kind of critical evaluation of evidence that psychologists must do in professional research.</li>
</ul>
<section id="naming-things" class="level2">
<h2 class="anchored" data-anchor-id="naming-things">Naming things</h2>
<p>I will format dataset names like this:</p>
<ul>
<li><code>study-two-general-participants.csv</code></li>
</ul>
<p>I will also format variable (data column) names like this: <code>variable</code></p>
<p>I will also format value or other data object (e.g.&nbsp;cell value) names like this: <code>studyone</code></p>
<p>I will format functions and library names like this: e.g.&nbsp;function <code>ggplot()</code> or e.g.&nbsp;library <code>{tidyverse}</code>.</p>
</section>
<section id="the-data-we-will-be-using" class="level2">
<h2 class="anchored" data-anchor-id="the-data-we-will-be-using">The data we will be using</h2>
<ol type="1">
<li>Data from a study we conducted on the response of adults from a UK national participant sample:</li>
</ol>
<ul>
<li><code>study-two-general-participants.csv</code></li>
</ul>
<ol start="2" type="1">
<li>Data comprising the responses of PSYC122 students:</li>
</ol>
<ul>
<li><code>2023-24_PSYC122-participants.csv</code></li>
</ul>
<p>Notice that study-two participants and the PSYC122 participants were given similar tests but different health information texts to read and respond to.</p>
</section>
</section>
<section id="answers" class="level1">
<h1>Answers</h1>
<section id="step-1-set-up" class="level2">
<h2 class="anchored" data-anchor-id="step-1-set-up">Step 1: Set-up</h2>
<p>To begin, we set up our environment in R.</p>
<section id="task-1-run-code-to-empty-the-r-environment" class="level3">
<h3 class="anchored" data-anchor-id="task-1-run-code-to-empty-the-r-environment">Task 1 – Run code to empty the R environment</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())                            </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="task-2-run-code-to-load-relevant-libraries" class="level3">
<h3 class="anchored" data-anchor-id="task-2-run-code-to-load-relevant-libraries">Task 2 – Run code to load relevant libraries</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggeffects"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggeffects' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"patchwork"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.5.1     ✔ purrr   1.0.2
✔ tibble  3.2.1     ✔ dplyr   1.1.2
✔ tidyr   1.3.0     ✔ stringr 1.5.0
✔ readr   2.1.3     ✔ forcats 0.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
</div>
</section>
</section>
<section id="step-2-load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="step-2-load-the-data">Step 2: Load the data</h2>
<section id="task-3-read-in-the-data-files-we-will-be-using" class="level3">
<h3 class="anchored" data-anchor-id="task-3-read-in-the-data-files-we-will-be-using">Task 3 – Read in the data files we will be using</h3>
<p>The data files are called:</p>
<ul>
<li><code>study-two-general-participants.csv</code></li>
<li><code>2023-24_PSYC122-participants.csv</code></li>
</ul>
<p>Use the <code>read_csv()</code> function to read the data files into R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>study.two.gen <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"study-two-general-participants.csv"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 172 Columns: 12
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY
dbl (7): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3, QRITOTAL

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>study<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"2023-24_PSYC122-participants.csv"</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 65 Columns: 15
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): ResponseId, GENDER, EDUCATION, ETHNICITY, NATIVE.LANGUAGE, OTHER.LA...
dbl (8): AGE, EDUCATION.rating_1, ENGLISH.PROFICIENCY, SHIPLEY, HLVA, FACTOR...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>When you read the data files in, give the data objects you create distinct name e.g.&nbsp;<code>study.two.gen</code> versus <code>study.122</code>.</p>
</section>
<section id="task-4-inspect-the-data-file" class="level3">
<h3 class="anchored" data-anchor-id="task-4-inspect-the-data-file">Task 4 – Inspect the data file</h3>
<p>Use the <code>summary()</code> or <code>head()</code> functions to take a look at both datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(study.two.gen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> participant_ID        mean.acc        mean.self        study          
 Length:172         Min.   :0.4107   Min.   :3.786   Length:172        
 Class :character   1st Qu.:0.6786   1st Qu.:6.411   Class :character  
 Mode  :character   Median :0.7679   Median :7.321   Mode  :character  
                    Mean   :0.7596   Mean   :7.101                     
                    3rd Qu.:0.8393   3rd Qu.:7.946                     
                    Max.   :0.9821   Max.   :9.000                     
      AGE           SHIPLEY           HLVA           FACTOR3     
 Min.   :18.00   Min.   :23.00   Min.   : 3.000   Min.   :29.00  
 1st Qu.:25.00   1st Qu.:32.75   1st Qu.: 7.750   1st Qu.:47.00  
 Median :32.50   Median :36.00   Median : 9.000   Median :51.00  
 Mean   :35.37   Mean   :35.13   Mean   : 9.064   Mean   :51.24  
 3rd Qu.:44.00   3rd Qu.:39.00   3rd Qu.:11.000   3rd Qu.:56.25  
 Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  
    QRITOTAL        GENDER           EDUCATION          ETHNICITY        
 Min.   : 6.00   Length:172         Length:172         Length:172        
 1st Qu.:12.00   Class :character   Class :character   Class :character  
 Median :14.00   Mode  :character   Mode  :character   Mode  :character  
 Mean   :13.88                                                           
 3rd Qu.:16.00                                                           
 Max.   :20.00                                                           </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(study<span class="fl">.122</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ResponseId             AGE           GENDER           EDUCATION        
 Length:65          Min.   :18.00   Length:65          Length:65         
 Class :character   1st Qu.:18.00   Class :character   Class :character  
 Mode  :character   Median :19.00   Mode  :character   Mode  :character  
                    Mean   :19.42                                        
                    3rd Qu.:19.00                                        
                    Max.   :56.00                                        
                                                                         
 EDUCATION.rating_1  ETHNICITY         NATIVE.LANGUAGE    OTHER.LANGUAGE    
 Min.   :4.000      Length:65          Length:65          Length:65         
 1st Qu.:7.000      Class :character   Class :character   Class :character  
 Median :7.000      Mode  :character   Mode  :character   Mode  :character  
 Mean   :7.077                                                              
 3rd Qu.:8.000                                                              
 Max.   :9.000                                                              
                                                                            
 ENGLISH.PROFICIENCY  OCCUPATION           SHIPLEY           HLVA       
 Min.   :1.000       Length:65          Min.   :10.00   Min.   : 1.000  
 1st Qu.:2.500       Class :character   1st Qu.:30.00   1st Qu.: 7.000  
 Median :3.000       Mode  :character   Median :32.00   Median : 8.000  
 Mean   :2.571                          Mean   :32.31   Mean   : 8.508  
 3rd Qu.:3.000                          3rd Qu.:36.00   3rd Qu.:10.000  
 Max.   :3.000                          Max.   :40.00   Max.   :14.000  
 NA's   :58                                                             
    FACTOR3         mean.acc        mean.self   
 Min.   :28.00   Min.   :0.2500   Min.   :2.60  
 1st Qu.:43.00   1st Qu.:0.7500   1st Qu.:6.20  
 Median :46.00   Median :0.8500   Median :7.00  
 Mean   :46.91   Mean   :0.8231   Mean   :6.92  
 3rd Qu.:52.00   3rd Qu.:0.9500   3rd Qu.:7.80  
 Max.   :61.00   Max.   :1.0000   Max.   :9.00  
                                                </code></pre>
</div>
</div>
</section>
</section>
<section id="step-3-compare-the-data-from-the-different-studies" class="level2">
<h2 class="anchored" data-anchor-id="step-3-compare-the-data-from-the-different-studies">Step 3: Compare the data from the different studies</h2>
<section id="revise-practice-to-strengthen-skills" class="level3">
<h3 class="anchored" data-anchor-id="revise-practice-to-strengthen-skills">Revise: practice to strengthen skills</h3>
</section>
<section id="task-5-compare-the-data-distributions-from-the-two-studies" class="level3">
<h3 class="anchored" data-anchor-id="task-5-compare-the-data-distributions-from-the-two-studies">Task 5 – Compare the data distributions from the two studies</h3>
<ul>
<li><p>Q.1. What is the mean of the <code>mean.acc</code> and <code>SHIPLEY</code> variables in the two studies?</p></li>
<li><p>A.1. The means are:</p></li>
<li><p>study two – <code>mean.acc</code>: mean = 0.7596</p></li>
<li><p>study two – <code>SHIPLEY</code>: mean = 35.13</p></li>
<li><p>study PSYC122 – <code>mean.acc</code>: mean = 0.8231</p></li>
<li><p>study PSYC122 – <code>SHIPLEY</code>: mean = 32.31</p></li>
<li><p>Q.2. Draw histograms of both mean.acc and mean.self for both studies.</p></li>
<li><p>A.2. You can write the code as you have been shown to do e.g.&nbsp;in <code>2023-24-PSYC122-w19-how-to.Rmd</code>:</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study.two.gen, <span class="fu">aes</span>(<span class="at">x =</span> mean.acc)) <span class="sc">+</span> </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mean accuracy (mean.acc)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study.two.gen, <span class="fu">aes</span>(<span class="at">x =</span> SHIPLEY)) <span class="sc">+</span> </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vocabulary (SHIPLEY)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study<span class="fl">.122</span>, <span class="fu">aes</span>(<span class="at">x =</span> mean.acc)) <span class="sc">+</span> </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mean accuracy (mean.acc)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study<span class="fl">.122</span>, <span class="fu">aes</span>(<span class="at">x =</span> SHIPLEY)) <span class="sc">+</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vocabulary (SHIPLEY)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-5-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="introduce-make-some-new-moves" class="level3">
<h3 class="anchored" data-anchor-id="introduce-make-some-new-moves">Introduce: make some new moves</h3>
</section>
<section id="task-6-create-grids-of-plots-to-make-the-comparison-easier-to-do" class="level3">
<h3 class="anchored" data-anchor-id="task-6-create-grids-of-plots-to-make-the-comparison-easier-to-do">Task 6 – Create grids of plots to make the comparison easier to do</h3>
</section>
<section id="hint-task-6-what-we-are-going-to-do-is-to-create-two-histograms-and-then-present-them-side-by-side-to-allow-easy-comparison-of-variable-distributions" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-6-what-we-are-going-to-do-is-to-create-two-histograms-and-then-present-them-side-by-side-to-allow-easy-comparison-of-variable-distributions">hint: Task 6 – What we are going to do is to create two histograms and then present them side by side to allow easy comparison of variable distributions</h3>
<p>We need to make two changes to the coding approach you have been using until now.</p>
<p>Before we explain anything, let’s look at an example: run these line of code and check the result.</p>
<ul>
<li>Make sure you identify what is different about the plotting code, shown following, compared to what you have done before: there is a <em>surprise</em> in what is going to happen.</li>
</ul>
<p>First, create plot objects, give them names, but do not show them:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> study.two.gen, <span class="fu">aes</span>(<span class="at">x =</span> mean.acc)) <span class="sc">+</span> </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mean accuracy (mean.acc)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>, <span class="at">title =</span> <span class="st">"Study Two"</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>plot<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> study<span class="fl">.122</span>, <span class="fu">aes</span>(<span class="at">x =</span> mean.acc)) <span class="sc">+</span> </span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Mean accuracy (mean.acc)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>, <span class="at">title =</span> <span class="st">"Study PSYC122"</span>) <span class="sc">+</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Second, show the plots, side-by-side:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="sc">+</span> plot<span class="fl">.122</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_bar()`).
Removed 2 rows containing missing values or values outside the scale range
(`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This is what you are doing: check out the process, step-by-step. (And notice that you repeat the process for each of two (or more) plots.)</p>
<ol type="1">
<li><code>ggplot(...)</code> tell R you want to make a plot using the <code>ggplot()</code> function;</li>
<li><code>plot.one &lt;-</code> tell R you want to give the plot a name; the name appears in the environment;</li>
<li><code>ggplot(data = study.two.gen ...)</code> tell R you want to make a plot with the <code>study.two</code> data;</li>
<li><code>ggplot(..., aes(x = mean.acc))</code> tell R that you want to make a plot with the variable <code>mean.acc</code>;</li>
</ol>
<ul>
<li>here, specify the aesthetic mapping, <code>x = mean.acc</code></li>
</ul>
<ol start="5" type="1">
<li><code>geom_histogram()</code> tell R you want to plot values of <code>mean.acc</code> as a histogram;</li>
<li><code>binwidth = .1</code> adjust the binwidth to show enough detail but not too much in the distribution;</li>
<li><code>theme_bw()</code> tell R what theme you want, adjusting the plot appearance;</li>
<li><code>labs(x = "Mean accuracy (mean.acc)", y = "frequency count", title = "Study Two")</code> fix the x-axis and y-axis labels;</li>
</ol>
<ul>
<li>here, add a title for the plot, so you can tell the two plots apart;</li>
</ul>
<ol start="9" type="1">
<li><code>xlim(0, 1)</code> adjust the x-axis limits to show the full range of possible score values on this variable.</li>
</ol>
<p>Do this process twice, once for each dataset, creating two plots so that you can compare the distribution of <code>mean.acc</code> scores between the studies.</p>
<p>Finally, having created the two plots, produce them for viewing:</p>
<ol start="10" type="1">
<li><code>plot.two + plot.122</code> having constructed – and named – both plots, you enter their names, separated by a +, to show them in a grid of two plots.</li>
</ol>
<p>Notice: until you get to step 10, <strong>nothing will appear</strong>. This will be <strong>surprising</strong> but it is perfectly normal when we increase the <em>level of complexity</em> of the plots we build.</p>
<ul>
<li>You first build the plots.</li>
<li>You are creating plot objects and you give these objects names.</li>
<li>The objects will appear in the <code>Environment</code> with the names you give them.</li>
<li>You then <em>produce</em> the plots for viewing, by using their names.</li>
</ul>
<p>Until you complete the last step, you will not see any changes until you use the object names to produce them for viewing.</p>
<p>This is how you construct complex arrays of plots.</p>
</section>
<section id="task-7-try-this-out-for-yourself-focusing-now-on-the-distribution-of-shipley-scores-in-the-two-studies" class="level3">
<h3 class="anchored" data-anchor-id="task-7-try-this-out-for-yourself-focusing-now-on-the-distribution-of-shipley-scores-in-the-two-studies">Task 7 – Try this out for yourself, focusing now on the distribution of <code>SHIPLEY</code> scores in the two studies</h3>
<p>First, create plot objects but do not show them.</p>
<ul>
<li>Give each plot a name. You will use the names next.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> study.two.gen, <span class="fu">aes</span>(<span class="at">x =</span> SHIPLEY)) <span class="sc">+</span> </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vocabulary (SHIPLEY)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>, <span class="at">title =</span> <span class="st">"Study Two"</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">40</span>)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>plot<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> study<span class="fl">.122</span>, <span class="fu">aes</span>(<span class="at">x =</span> SHIPLEY)) <span class="sc">+</span> </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Vocabulary (SHIPLEY)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>, <span class="at">title =</span> <span class="st">"PSYC122"</span>) <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">40</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Second produce the plots for viewing, side-by-side, by <em>naming</em> them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="sc">+</span> plot<span class="fl">.122</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_bar()`).
Removed 2 rows containing missing values or values outside the scale range
(`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Q.3. Now use the plots to do some data analysis work: how do the <code>SHIPLEY</code> distributions compare, when you compare the <code>SHIPLEY</code> of <code>study.two.gen</code> versus <code>SHIPLEY</code> of <code>study.122</code>?</li>
<li>A.3. When you compare the plots side-by-side you can see that the <code>SHIPLEY</code> distributions are <em>mostly</em> similar: most people have high <code>SHIPLEY</code> scores.</li>
</ul>
<p>But you can also see striking differences:</p>
<ul>
<li><p>The peak of the distribution – where the tallest bar is – is at a higher <code>SHIPLEY</code> score in <code>study.two.gen</code> (around <code>SHIPLEY</code> = 37-38) than in <code>study.122</code> (where is it around <code>SHIPLEY</code> = 30).</p></li>
<li><p>There appear to be <em>fewer</em> participants with lower <code>SHIPLEY</code> scores in <code>study.122</code> than in <code>study.two</code>.</p></li>
<li><p>Q.4. Is the visual impression you get from comparing the distributions consistent with the statistics you see in the summary?</p></li>
<li><p>A.4. Yes: If you go back to the summary of <code>SHIPLEY</code>, comparing the two studies datasets, then you can see that the median and mean are higher in <code>study.122</code> than in <code>study.two.gen</code>.</p></li>
</ul>
</section>
</section>
<section id="step-4-now-use-scatterplots-and-correlation-to-examine-associations-between-variables" class="level2">
<h2 class="anchored" data-anchor-id="step-4-now-use-scatterplots-and-correlation-to-examine-associations-between-variables">Step 4: Now use scatterplots and correlation to examine associations between variables</h2>
<section id="revise-practice-to-strengthen-skills-1" class="level3">
<h3 class="anchored" data-anchor-id="revise-practice-to-strengthen-skills-1">Revise: practice to strengthen skills</h3>
</section>
<section id="task-8-draw-scatterplots-to-compare-the-potential-association-between-mean.acc-and-mean.self-in-both-study.two.gen-and-study.122-datasets" class="level3">
<h3 class="anchored" data-anchor-id="task-8-draw-scatterplots-to-compare-the-potential-association-between-mean.acc-and-mean.self-in-both-study.two.gen-and-study.122-datasets">Task 8 – Draw scatterplots to compare the potential association between <code>mean.acc</code> and <code>mean.self</code> in both <code>study.two.gen</code> and <code>study.122</code> datasets</h3>
</section>
<section id="hint-task-8-the-plotting-steps-are-explained-in-some-detail-in-2023-24-psyc122-w17-how-to.rmd-and-you-can-see-example-code-in-2023-24-psyc122-w19-how-to.rmd" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-8-the-plotting-steps-are-explained-in-some-detail-in-2023-24-psyc122-w17-how-to.rmd-and-you-can-see-example-code-in-2023-24-psyc122-w19-how-to.rmd">hint: Task 8 – The plotting steps are explained in some detail in <code>2023-24-PSYC122-w17-how-to.Rmd</code> and you can see example code in <code>2023-24-PSYC122-w19-how-to.Rmd</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study.two.gen, <span class="fu">aes</span>(<span class="at">x =</span> mean.self, <span class="at">y =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.75</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">colour =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">colour =</span> <span class="st">"green"</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"mean self-rated accuracy"</span>, <span class="at">y =</span> <span class="st">"mean accuracy"</span>) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">10</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> study<span class="fl">.122</span>, <span class="fu">aes</span>(<span class="at">x =</span> mean.self, <span class="at">y =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.75</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">colour =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">colour =</span> <span class="st">"green"</span>) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"mean self-rated accuracy"</span>, <span class="at">y =</span> <span class="st">"mean accuracy"</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">10</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="task-9-create-a-grid-of-plots-to-make-the-comparison-easier-to-do" class="level3">
<h3 class="anchored" data-anchor-id="task-9-create-a-grid-of-plots-to-make-the-comparison-easier-to-do">Task 9 – Create a grid of plots to make the comparison easier to do</h3>
</section>
<section id="hint-task-9-we-follow-the-same-steps-as-we-used-in-tasks-6-and-7-to-create-the-plots" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-9-we-follow-the-same-steps-as-we-used-in-tasks-6-and-7-to-create-the-plots">hint: Task 9 – We follow the same steps as we used in tasks 6 and 7 to create the plots</h3>
<p>We again:</p>
<ol type="1">
<li>First construct the plot objects and give them names;</li>
<li>create and show a grid of named plots.</li>
</ol>
<p>Though this time we are producing a grid of <strong>scatterplots</strong>.</p>
<p>First, create plot objects, give them names, but do not show them:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> study.two.gen, <span class="fu">aes</span>(<span class="at">x =</span> mean.self, <span class="at">y =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.75</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">colour =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">colour =</span> <span class="st">"green"</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"mean self-rated accuracy"</span>, <span class="at">y =</span> <span class="st">"mean accuracy"</span>) <span class="sc">+</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">10</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>plot<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> study<span class="fl">.122</span>, <span class="fu">aes</span>(<span class="at">x =</span> mean.self, <span class="at">y =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.75</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">colour =</span> <span class="st">"darkgrey"</span>) <span class="sc">+</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">colour =</span> <span class="st">"green"</span>) <span class="sc">+</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"mean self-rated accuracy"</span>, <span class="at">y =</span> <span class="st">"mean accuracy"</span>) <span class="sc">+</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">10</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Second name the plots, to show them side-by-side in the plot window:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="sc">+</span> plot<span class="fl">.122</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'
`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now use the plots to make comparison judgments.</p>
<ul>
<li>Q.5. How does the association, shown in the plots, between <code>mean.self</code> and <code>mean.acc</code> compare when you look at the <code>study.two.gen</code> versus the <code>study.122</code> plot?</li>
<li>hint: Q.5. When comparing evidence about associations in different studies, we are mostly going to focus on the slope – the angle – of the prediction lines, and the ways in which points do or do not cluster about the prediction lines.</li>
<li>A.5. If you examine the <code>study.two.gen</code> versus the <code>study.122</code> plots then you can see that in both plots higher <code>mean.self</code> scores appear to be associated with higher <code>mean.acc</code> scores. But the trend maybe is a bit stronger – the line is steeper – in <code>study.two.gen</code>.</li>
</ul>
<p>We are now in a position to answer one of our research questions:</p>
<ol start="2" type="1">
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<p>If people <em>can</em> accurately evaluate whether they correctly understand written health information then <code>mean.self</code> (a score representing their evaluation) <em>should</em> be associated with <code>mean.acc</code> (a score representing their accuracy of understanding) for each person.</p>
</section>
<section id="revise-practice-to-strengthen-skills-2" class="level3">
<h3 class="anchored" data-anchor-id="revise-practice-to-strengthen-skills-2">Revise: practice to strengthen skills</h3>
</section>
<section id="task-10-can-you-estimate-the-association-between-mean.acc-and-mean.self-in-both-datasets" class="level3">
<h3 class="anchored" data-anchor-id="task-10-can-you-estimate-the-association-between-mean.acc-and-mean.self-in-both-datasets">Task 10 – Can you estimate the association between <code>mean.acc</code> and <code>mean.self</code> in both datasets?</h3>
</section>
<section id="hint-task-10-we-use-cor.test-as-you-have-been-shown-how-to-do-e.g.-in-2023-24-psyc122-w16-how-to.rmd" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-10-we-use-cor.test-as-you-have-been-shown-how-to-do-e.g.-in-2023-24-psyc122-w16-how-to.rmd">hint: Task 10 – We use <code>cor.test()</code> as you have been shown how to do e.g.&nbsp;in <code>2023-24-PSYC122-w16-how-to.Rmd</code></h3>
<p>Do the correlation for both datasets.</p>
<p>First, look at the correlation between <code>mean.acc</code> and <code>mean.self</code> in <code>study.two</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(study.two.gen<span class="sc">$</span>mean.acc, study.two.gen<span class="sc">$</span>mean.self, <span class="at">method =</span> <span class="st">"pearson"</span>,  <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  study.two.gen$mean.acc and study.two.gen$mean.self
t = 8.4991, df = 170, p-value = 9.356e-15
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4317217 0.6431596
sample estimates:
      cor 
0.5460792 </code></pre>
</div>
</div>
<ul>
<li><p>Q.6. What is r, the correlation coefficient?</p></li>
<li><p>A.6. r = 0.5460792</p></li>
<li><p>Q.7. Is the correlation significant?</p></li>
<li><p>A.7. r is significant</p></li>
<li><p>Q.8. What are the values for t and p for the significance test for the correlation?</p></li>
<li><p>A.8. t = 8.4991, p = 9.356e-15</p></li>
</ul>
<p>Second, look at the correlation between <code>mean.acc</code> and <code>mean.self</code> in <code>study.122</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(study<span class="fl">.122</span><span class="sc">$</span>mean.acc, study<span class="fl">.122</span><span class="sc">$</span>mean.self, <span class="at">method =</span> <span class="st">"pearson"</span>,  <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  study.122$mean.acc and study.122$mean.self
t = 3.4924, df = 63, p-value = 0.0008808
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1761474 0.5888052
sample estimates:
      cor 
0.4027438 </code></pre>
</div>
</div>
<ul>
<li><p>Q.9. What is r, the correlation coefficient?</p></li>
<li><p>A.9. r = 0.4027438</p></li>
<li><p>Q.10. Is the correlation significant?</p></li>
<li><p>A.10. r is significant</p></li>
<li><p>Q.11. What are the values for t and p for the significance test for the correlation?</p></li>
<li><p>A.11. t = 3.4924, p = 0.0008808</p></li>
</ul>
<p>Now we can answer the research question:</p>
<ol start="2" type="1">
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<ul>
<li>Q.12. What do the correlation estimates tell you is the answer to the research question?</li>
<li>A.12.</li>
</ul>
<blockquote class="blockquote">
<p>The correlations are positive and significant, indicating that higher <code>mean.self</code> (evaluations) are associated with higher <code>mean.acc</code> (understanding), suggesting that people <em>can</em> judge their accuracy of understanding.</p>
</blockquote>
<ul>
<li><p>Q.13. Can you compare the estimates, given the two datasets, to evaluate if the result in <code>study.two.gen</code> is <em>replicated</em> in <code>study.122</code>?</p></li>
<li><p>hint: Q.13. We can judge if the result in a study is replicated in another study by examining if – here – the correlation coefficient is significant in both studies <em>and</em> if the coefficient has the same size and sign in both studies.</p></li>
<li><p>A.13. If you compare the correlation estimates from both <code>study.two.gen</code> and <code>study.122</code> you can see:</p></li>
<li><p>first, the correlation is significant in both <code>study.two.gen</code> and <code>study.122</code>;</p></li>
<li><p>second, the correlation is positive in both studies.</p></li>
</ul>
<p>But, if you compare the correlation estimates, you can see that the coefficient estimate is smaller in <code>study.122</code> (where r = .40) than in <code>study.two.gen</code> (where r = .55).</p>
<p>This may suggest that the association observed in <code>study.two.gen</code> is different from the association in <code>study.122</code>, for some reason.</p>
</section>
<section id="task-11-in-working-with-r-to-do-data-analysis-we-often-work-with-libraries-of-function-like-tidyverse-that-enable-us-to-do-things-see-the-week-19-lecture-for-discussion." class="level3">
<h3 class="anchored" data-anchor-id="task-11-in-working-with-r-to-do-data-analysis-we-often-work-with-libraries-of-function-like-tidyverse-that-enable-us-to-do-things-see-the-week-19-lecture-for-discussion.">Task 11 – In working with R to do data analysis, we often work with libraries of function like <code>{tidyverse}</code> that enable us to do things (see the week 19 lecture for discussion).</h3>
<p>In this way, we are using the <code>{patchwork}</code> library so that we can create plots and then present them in a grid.</p>
<p>Can you find the online information about <code>{patchwork}</code> and use it to adjust the layout of the grids of plots you are using?</p>
</section>
<section id="hint-task-11-to-find-out-more-information-about-a-function-or-a-library-in-r-do-a-search-for-the-keywords" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-11-to-find-out-more-information-about-a-function-or-a-library-in-r-do-a-search-for-the-keywords">hint: Task 11 – To find out more information about a function or a library in R, do a search for the keywords</h3>
<p>You can do a search, using any search engine (e.g., Bing, Chrome, Google), by entering:</p>
<blockquote class="blockquote">
<p>in r …</p>
</blockquote>
<p>And pasting the words you want to know about to replace the <code>...</code> e.g.&nbsp;“in r patchwork”.</p>
<p>You will then see a list of results including the link to the <code>{patchwork}</code> information:</p>
<p><a href="https://patchwork.data-imaginist.com" class="uri">https://patchwork.data-imaginist.com</a></p>
</section>
</section>
<section id="step-5-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors" class="level2">
<h2 class="anchored" data-anchor-id="step-5-use-a-linear-model-to-to-answer-the-research-questions-multiple-predictors">Step 5: Use a linear model to to answer the research questions – multiple predictors</h2>
<section id="revise-practice-to-strengthen-skills-3" class="level3">
<h3 class="anchored" data-anchor-id="revise-practice-to-strengthen-skills-3">Revise: practice to strengthen skills</h3>
</section>
<section id="task-12-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors" class="level3">
<h3 class="anchored" data-anchor-id="task-12-examine-the-relation-between-outcome-mean-accuracy-mean.acc-and-multiple-predictors">Task 12 – Examine the relation between outcome mean accuracy (<code>mean.acc</code>) and multiple predictors</h3>
<p>We specify linear models including as predictors the variables:</p>
<ul>
<li>health literacy (<code>HLVA</code>);</li>
<li>vocabulary (<code>SHIPLEY</code>);</li>
<li>reading strategy (<code>FACTOR3</code>).</li>
</ul>
</section>
<section id="hint-task-12-we-use-lm-as-we-have-been-doing-before-see-e.g.-2023-24-psyc122-w18-how-to.r" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-12-we-use-lm-as-we-have-been-doing-before-see-e.g.-2023-24-psyc122-w18-how-to.r">hint: Task 12 – We use <code>lm()</code>, as we have been doing before, see e.g.&nbsp;<code>2023-24-PSYC122-w18-how-to.R</code></h3>
</section>
<section id="task-12-examine-the-predictors-of-mean-accuracy-mean.acc-first-for-the-study.two.gen-data" class="level3">
<h3 class="anchored" data-anchor-id="task-12-examine-the-predictors-of-mean-accuracy-mean.acc-first-for-the-study.two.gen-data">Task 12 – Examine the predictors of mean accuracy (<code>mean.acc</code>), first, for the <code>study.two.gen</code> data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study.two.gen)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.two.gen)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.242746 -0.074188  0.003173  0.075361  0.211357 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.146896   0.076325   1.925  0.05597 .  
HLVA        0.017598   0.003589   4.904  2.2e-06 ***
SHIPLEY     0.008397   0.001853   4.533  1.1e-05 ***
FACTOR3     0.003087   0.001154   2.675  0.00822 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.097 on 168 degrees of freedom
Multiple R-squared:  0.3636,    Adjusted R-squared:  0.3522 
F-statistic: 31.99 on 3 and 168 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Using the model estimates, we can answer the research question:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<p>Inspect the model summary, then answer the following questions:</p>
<ul>
<li><p>Q.14. What is the estimate for the coefficient of the effect of the predictor <code>SHIPLEY</code> in <em>this</em> model?</p></li>
<li><p>A.14. 0.008397</p></li>
<li><p>Q.15. Is the effect significant?</p></li>
<li><p>A.15. It is significant, p &lt; .05</p></li>
<li><p>Q.16. What are the values for t and p for the significance test for the coefficient?</p></li>
<li><p>A.16. t = 4.533, p = 1.1e-05</p></li>
<li><p>Q.17. Now consider the estimates for all the variables, what do you conclude is the answer to the research question – given the <code>study.two.gen</code> data:</p></li>
</ul>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<ul>
<li><p>hint: Q.17. Can you report the model and the model fit statistics using the language you have been shown in the week 18 lecture?</p></li>
<li><p>A.17.</p></li>
</ul>
<blockquote class="blockquote">
<p>We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (<code>HLVA</code>), reading strategy (<code>FACTOR3</code>), and vocabulary (<code>SHIPLEY</code>) as predictors. The model is significant overall, with F(3, 168) = 31.99, p&lt; .001, and explains 35% of variance (adjusted R2 = 0.35). Mean accuracy was predicted to be higher given higher scores in health literacy (<code>HLVA</code> estimate = .018, t = 4.90, p &lt; .001), vocabulary knowledge (<code>SHIPLEY</code> estimate = .008, t = 4.53, p &lt; .001), and reading strategy (<code>FACTOR3</code> estimate = .003, t = 2.68, p = .008).</p>
</blockquote>
</section>
<section id="task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data" class="level3">
<h3 class="anchored" data-anchor-id="task-13-examine-the-predictors-of-mean-accuracy-mean.acc-now-for-the-study.122-data">Task 13 – Examine the predictors of mean accuracy (<code>mean.acc</code>), now, for the <code>study.122</code> data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study<span class="fl">.122</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.122)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.37214 -0.07143 -0.01102  0.07411  0.25329 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.3066150  0.1447265   2.119   0.0382 *  
HLVA        0.0335342  0.0071332   4.701 1.52e-05 ***
SHIPLEY     0.0062524  0.0034741   1.800   0.0768 .  
FACTOR3     0.0006217  0.0024450   0.254   0.8001    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1162 on 61 degrees of freedom
Multiple R-squared:  0.4158,    Adjusted R-squared:  0.3871 
F-statistic: 14.47 on 3 and 61 DF,  p-value: 3.156e-07</code></pre>
</div>
</div>
<p>Using the model estimates, we can answer the research question:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<p>Inspect the model summary, then answer the following questions:</p>
<ul>
<li><p>Q.18. What is the estimate for the coefficient of the effect of the predictor, <code>HLVA</code>, in <em>this</em> model?</p></li>
<li><p>A.18. 0.0335342</p></li>
<li><p>Q.19. Is the effect significant?</p></li>
<li><p>A.19. It is significant, p &gt; .05 because p = 1.52e-05</p></li>
<li><p>Q.20. What are the values for t and p for the significance test for the coefficient?</p></li>
<li><p>A.20. t = 4.701, p &lt; .001</p></li>
<li><p>Q.21. Now consider the estimates for all the variables, what do you conclude is the answer to the research question – given the <code>study.122</code> data:</p></li>
</ul>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
</ol>
<ul>
<li><p>hint: Q.21. Can you report the model and the model fit statistics using the language you have been shown in the week 18 lecture?</p></li>
<li><p>A.21.</p></li>
</ul>
<blockquote class="blockquote">
<p>We fitted a linear model with mean comprehension accuracy as the outcome and health literacy (<code>HLVA</code>), reading strategy (<code>FACTOR3</code>), and vocabulary (<code>SHIPLEY)</code> as predictors. The model is significant overall, with F(3, 61) = 14.47, p &lt; .001, and explains 39% of variance (adjusted R2 = .387). Mean accuracy was predicted to be higher given higher scores in health literacy (<code>HLVA</code> estimate = .034, t = 4.70, p &lt; .001). There were non-significant effects of individual differences in vocabulary knowledge (<code>SHIPLEY</code> estimate = .006, t = 1.80, p = .077) and reading strategy (<code>FACTOR3</code> estimate = .001, t = .25, p = .800).</p>
</blockquote>
<ul>
<li><p>At this point, we can evaluate the evidence from the PSYC122 sample – based on your responses – to assess if the patterns, the estimates, we saw previously are repeated in analyses of PSYC122 responses.</p></li>
<li><p>Q.22. Are the findings from <code>study.two.gen</code> replicated in <code>study.122</code>?</p></li>
<li><p>hint: Q.22. We can judge if the results in an earlier study are replicated in another study by examining if – here – the linear model estimates are significant in both studies <em>and</em> if the coefficient estimates have the same size and sign in both studies.</p></li>
<li><p>A.22. If you compare the linear model coefficient estimates from both the <code>study.two.gen</code> and <code>study.122</code> models, you can see:</p></li>
<li><p>first, that the <code>HLVA</code> effect estimate is significant in both <code>study.two.gen</code> and <code>study.122</code>;</p></li>
<li><p>second, that the estimates of the <code>HLVA</code> effect have the same sign – positive – in both studies while the estimated coefficient is a bit bigger in the <code>study.122</code> data (implying a stronger effect);</p></li>
<li><p>but, third that the estimates of the effects of variation in vocabulary knowledge (<code>SHIPLEY</code>) and reading strategy (<code>FACTOR3</code>) are significant in <code>study.two.gen</code> but not in <code>study.122</code>.</p></li>
</ul>
<p>This suggests that the attributes – the set of abilities – that predict comprehension accuracy are similar but not the same in the <code>study.two.gen</code> participants compared to <code>study.122</code> participants.</p>
<ul>
<li><p>Q.23. How would you describe the outstanding difference between the results of the two studies?</p></li>
<li><p>hint: Q.23. We can look at the estimates but we can also use the model prediction plotting code you used before, see:</p></li>
<li><p><code>2022-23-PSYC122-w18-how-to.R</code></p></li>
<li><p><code>2022-23-PSYC122-w19-how-to.R</code></p></li>
<li><p>hint: Q.23. Let’s focus on comparing the <code>study.two.gen</code> and <code>study.122</code> estimates for the effect of <code>HLVA</code> in both models: we can plot model predictions, for comparison:</p></li>
</ul>
<p>First: fit the models – using different names for the different models:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model.two <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study.two.gen)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model.two)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.two.gen)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.242746 -0.074188  0.003173  0.075361  0.211357 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.146896   0.076325   1.925  0.05597 .  
HLVA        0.017598   0.003589   4.904  2.2e-06 ***
SHIPLEY     0.008397   0.001853   4.533  1.1e-05 ***
FACTOR3     0.003087   0.001154   2.675  0.00822 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.097 on 168 degrees of freedom
Multiple R-squared:  0.3636,    Adjusted R-squared:  0.3522 
F-statistic: 31.99 on 3 and 168 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>model<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> HLVA <span class="sc">+</span> SHIPLEY <span class="sc">+</span> FACTOR3, <span class="at">data =</span> study<span class="fl">.122</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model<span class="fl">.122</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ HLVA + SHIPLEY + FACTOR3, data = study.122)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.37214 -0.07143 -0.01102  0.07411  0.25329 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.3066150  0.1447265   2.119   0.0382 *  
HLVA        0.0335342  0.0071332   4.701 1.52e-05 ***
SHIPLEY     0.0062524  0.0034741   1.800   0.0768 .  
FACTOR3     0.0006217  0.0024450   0.254   0.8001    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1162 on 61 degrees of freedom
Multiple R-squared:  0.4158,    Adjusted R-squared:  0.3871 
F-statistic: 14.47 on 3 and 61 DF,  p-value: 3.156e-07</code></pre>
</div>
</div>
<p>Second, create prediction plots for the <code>HLVA</code> effect for each model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>dat.two <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model.two, <span class="st">"HLVA"</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>plot.two <span class="ot">&lt;-</span> <span class="fu">plot</span>(dat.two) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Study Two"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model<span class="fl">.122</span>, <span class="st">"HLVA"</span>)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>plot<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">plot</span>(dat<span class="fl">.122</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Study PSYC122"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Third, show the plots side-by-side:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="sc">+</span> plot<span class="fl">.122</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>A.23. If we compare the estimates for the coefficient of the <code>HLVA</code> effect in the <code>study.two.gen</code> and <code>study.122</code> models we can see that:</li>
</ul>
<ol type="1">
<li>The health literacy <code>HLVA</code> effect is significant in both <code>study.two.gen</code> and <code>study.122</code>.</li>
<li>The effect trends positive in both studies.</li>
<li>The coefficient estimate is bigger in <code>study.122</code> than in <code>study.two.gen</code>.</li>
<li>The prediction plots suggest the prediction line slope is steeper in <code>study.122</code>.</li>
<li>The grey shaded area around the trend line (indicating our uncertainty about the estimated trend) is wider for <code>study.two.gen</code> than for <code>study.122</code>, suggesting we are more uncertain about the association for the <code>study.two.gen</code> data.</li>
</ol>
<ul>
<li>The breadth of the grey shaded area around the trend line is hard to compare between the two plots. You have to look carefully at the y-axis scale information to make a judgment about the relative width of these uncertainty ellipses.</li>
</ul>
<p>The visualizations plus the model summaries suggests that the estimates of the effect of health literacy are different in the <code>study.122</code> compared to the <code>study.two.gen</code> data. Why is that?</p>
<ul>
<li>We can redraw the prediction plots to add in more information about our samples. This change, see following, will help us to interpret the results of the analyses we have done.</li>
<li>And <em>that</em> will help you to see why data visualization and data analysis work well together.</li>
</ul>
</section>
<section id="task-14-in-producing-prediction-plots-we-are-using-functions-from-the-ggefects-library.-can-you-locate-online-information-about-working-with-the-library-functions" class="level3">
<h3 class="anchored" data-anchor-id="task-14-in-producing-prediction-plots-we-are-using-functions-from-the-ggefects-library.-can-you-locate-online-information-about-working-with-the-library-functions">Task 14 – In producing prediction plots, we are using functions from the <code>{ggefects}</code> library. Can you locate online information about working with the library functions?</h3>
<p>Try doing a search with the key words: <code>in r ggeffects</code>.</p>
<p>If you do that, you will see links to the website:</p>
<p><a href="https://strengejacke.github.io/ggeffects/" class="uri">https://strengejacke.github.io/ggeffects/</a></p>
</section>
<section id="task-15-in-the-ggeffects-online-information-you-can-see-links-to-practical-examples.-can-you-use-the-information-under-practical-examples-to-adjust-the-appearance-of-the-prediction-plots-to-make-them-black-and-white-to-add-points" class="level3">
<h3 class="anchored" data-anchor-id="task-15-in-the-ggeffects-online-information-you-can-see-links-to-practical-examples.-can-you-use-the-information-under-practical-examples-to-adjust-the-appearance-of-the-prediction-plots-to-make-them-black-and-white-to-add-points">Task 15 – In the <code>{ggeffects}</code> online information, you can see links to practical examples. Can you use the information under “Practical examples” to adjust the appearance of the prediction plots: to make them black and white; to add points?</h3>
<p>First create the plots:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>dat.two <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model.two, <span class="st">"HLVA"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>plot.two <span class="ot">&lt;-</span> <span class="fu">plot</span>(dat.two, <span class="at">colors =</span> <span class="st">"bw"</span>, <span class="at">add.data =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Study Two"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>dat<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">ggpredict</span>(model<span class="fl">.122</span>, <span class="st">"HLVA"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>plot<span class="fl">.122</span> <span class="ot">&lt;-</span> <span class="fu">plot</span>(dat<span class="fl">.122</span>, <span class="at">colors =</span> <span class="st">"bw"</span>, <span class="at">add.data =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Study PSYC122"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Data points may overlap. Use the `jitter` argument to add some amount of
  random variation to the location of data points and avoid overplotting.</code></pre>
</div>
</div>
<p>Then show the plots:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>plot.two <span class="sc">+</span> plot<span class="fl">.122</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="2023-24-PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Q.24. Given the information in the adjusted plots, can you explain what is different about the <code>HLVA</code> effect estimate in the <code>study.122</code> data compared to the ?</li>
<li>A.24. Adding points allow us to see:</li>
</ul>
<ol type="1">
<li>There are far fewer observations in the <code>study.122</code> dataset than in the <code>study.two.gen</code> data: this means that our estimate of the effect will be <em>more uncertain</em> because we have <em>less information</em> when we look at the <code>study.122</code> data.</li>
<li>But it is also clear that the effect of <code>HLVA</code> appears to be stronger in the <code>study.122</code> data because observed scores are <em>closer</em> to model predictions: the <code>HLVA</code> effect <em>explains more variation</em> in the <code>study.122</code> data than in the <code>study.two.gen</code> data.</li>
</ol>


</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Website developed by Matthew Ivory</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../previous-content/index.html">
<p>Previous Content</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>