<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rob Davies">

<title>PSYC122-w19-workbook-answers – Statistics for Psychologists</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../Images/favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-ae99d8970fe14d16d849e9a6fc4cfcb4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search Year 1";};</script>
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


<link rel="stylesheet" href="https://lu-psy-r.github.io/essentials/index_24.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="https://lu-psy-r.github.io/" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="https://lu-psy-r.github.io/">
    <span class="navbar-title">Statistics for Psychologists</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year1/index.html"> 
<span class="menu-text">Year 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year2/index.html"> 
<span class="menu-text">Year 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/year3/index.html"> 
<span class="menu-text">Year 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/MSc/index.html"> 
<span class="menu-text">MSc</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://lu-psy-r.github.io/more/index.html"> 
<span class="menu-text">And More…</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">PSYC122-w19-workbook-answers</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../../index.html" class="sidebar-logo-link">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../PSYC121/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC121</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Introduction to PSYC121</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Descriptive statistics in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. DVs and IVs in RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Customisation of graphs, and z-scores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Class test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Sampling, probability and binomial tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Filtering data and testing means (one-sample t-test)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Related-samples t-tests, plotting means and SE bars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC121/Week9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">9. Unrelated-samples t-test and Power</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../PSYC122/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PSYC122</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Part 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">1. Week 11 - Correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">2. Week 12 - Correlation Part 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">3. Week 13 - The Linear Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">4. Week 14 - Chi-Square</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">5. Week 16 – Hypotheses, associations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">6. Week 17 – Better understanding the linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">7. Week 18 – Developing the linear model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../PSYC122/Week19.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">8. Week 19 – Linear models – interactions</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#naming-things" id="toc-naming-things" class="nav-link" data-scroll-target="#naming-things">Naming things</a></li>
  <li><a href="#the-data-we-will-be-using" id="toc-the-data-we-will-be-using" class="nav-link" data-scroll-target="#the-data-we-will-be-using">The data we will be using</a></li>
  </ul></li>
  <li><a href="#answers" id="toc-answers" class="nav-link" data-scroll-target="#answers">Answers</a>
  <ul class="collapse">
  <li><a href="#step-1-set-up" id="toc-step-1-set-up" class="nav-link" data-scroll-target="#step-1-set-up">Step 1: Set-up</a>
  <ul class="collapse">
  <li><a href="#task-1-run-code-to-empty-the-r-environment" id="toc-task-1-run-code-to-empty-the-r-environment" class="nav-link" data-scroll-target="#task-1-run-code-to-empty-the-r-environment">Task 1 – Run code to empty the R environment</a></li>
  <li><a href="#task-2-run-code-to-load-relevant-libraries" id="toc-task-2-run-code-to-load-relevant-libraries" class="nav-link" data-scroll-target="#task-2-run-code-to-load-relevant-libraries">Task 2 – Run code to load relevant libraries</a></li>
  </ul></li>
  <li><a href="#step-2-load-the-data" id="toc-step-2-load-the-data" class="nav-link" data-scroll-target="#step-2-load-the-data">Step 2: Load the data</a>
  <ul class="collapse">
  <li><a href="#task-3-read-in-the-data-file-we-will-be-using" id="toc-task-3-read-in-the-data-file-we-will-be-using" class="nav-link" data-scroll-target="#task-3-read-in-the-data-file-we-will-be-using">Task 3 – Read in the data file we will be using</a></li>
  <li><a href="#task-4-inspect-the-data-file" id="toc-task-4-inspect-the-data-file" class="nav-link" data-scroll-target="#task-4-inspect-the-data-file">Task 4 – Inspect the data file</a></li>
  </ul></li>
  <li><a href="#step-3-work-with-different-kinds-of-variables" id="toc-step-3-work-with-different-kinds-of-variables" class="nav-link" data-scroll-target="#step-3-work-with-different-kinds-of-variables">Step 3: Work with different kinds of variables</a></li>
  <li><a href="#revise-consolidate-what-you-know" id="toc-revise-consolidate-what-you-know" class="nav-link" data-scroll-target="#revise-consolidate-what-you-know">Revise: consolidate what you know</a>
  <ul class="collapse">
  <li><a href="#task-5-use-summaries-or-plots-to-examine-variables" id="toc-task-5-use-summaries-or-plots-to-examine-variables" class="nav-link" data-scroll-target="#task-5-use-summaries-or-plots-to-examine-variables">Task 5 – Use summaries or plots to examine variables</a></li>
  </ul></li>
  <li><a href="#extend-make-some-new-moves" id="toc-extend-make-some-new-moves" class="nav-link" data-scroll-target="#extend-make-some-new-moves">Extend: make some new moves</a></li>
  <li><a href="#revise-consolidate-what-you-know-1" id="toc-revise-consolidate-what-you-know-1" class="nav-link" data-scroll-target="#revise-consolidate-what-you-know-1">Revise: consolidate what you know</a>
  <ul class="collapse">
  <li><a href="#task-6-identify-and-change-what-kind-of-variable-numeric-or-factor-a-variable-is" id="toc-task-6-identify-and-change-what-kind-of-variable-numeric-or-factor-a-variable-is" class="nav-link" data-scroll-target="#task-6-identify-and-change-what-kind-of-variable-numeric-or-factor-a-variable-is">Task 6 – Identify (and change) what kind of variable – numeric or factor – a variable is</a></li>
  </ul></li>
  <li><a href="#step-4-now-draw-plots-to-examine-associations-between-variables-and-to-visualize-interactions" id="toc-step-4-now-draw-plots-to-examine-associations-between-variables-and-to-visualize-interactions" class="nav-link" data-scroll-target="#step-4-now-draw-plots-to-examine-associations-between-variables-and-to-visualize-interactions">Step 4: Now draw plots to examine associations between variables and to visualize interactions</a>
  <ul class="collapse">
  <li><a href="#consolidation-practice-to-strengthen-skills" id="toc-consolidation-practice-to-strengthen-skills" class="nav-link" data-scroll-target="#consolidation-practice-to-strengthen-skills">Consolidation: practice to strengthen skills</a></li>
  <li><a href="#task-7-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables" id="toc-task-7-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables" class="nav-link" data-scroll-target="#task-7-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables">Task 7 – Create a scatterplot to examine the association between two numeric variables</a></li>
  <li><a href="#introduce-make-some-new-moves" id="toc-introduce-make-some-new-moves" class="nav-link" data-scroll-target="#introduce-make-some-new-moves">Introduce: make some new moves</a></li>
  <li><a href="#task-8-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables-showing-how-the-association-is-different-for-different-values-of-a-third-variable" id="toc-task-8-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables-showing-how-the-association-is-different-for-different-values-of-a-third-variable" class="nav-link" data-scroll-target="#task-8-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables-showing-how-the-association-is-different-for-different-values-of-a-third-variable">Task 8 – Create a scatterplot to examine the association between two numeric variables, showing how the association is different for different values of a third variable</a></li>
  </ul></li>
  <li><a href="#step-5-use-linear-models-with-multiple-predictors-to-estimate-the-effects-of-factors-as-well-as-numeric-variables" id="toc-step-5-use-linear-models-with-multiple-predictors-to-estimate-the-effects-of-factors-as-well-as-numeric-variables" class="nav-link" data-scroll-target="#step-5-use-linear-models-with-multiple-predictors-to-estimate-the-effects-of-factors-as-well-as-numeric-variables">Step 5: Use linear models with multiple predictors, to estimate the effects of factors as well as numeric variables</a>
  <ul class="collapse">
  <li><a href="#consolidation-practice-to-strengthen-skills-1" id="toc-consolidation-practice-to-strengthen-skills-1" class="nav-link" data-scroll-target="#consolidation-practice-to-strengthen-skills-1">Consolidation: practice to strengthen skills</a></li>
  <li><a href="#task-9-first-fit-a-linear-model-including-just-numeric-variables-as-predictors" id="toc-task-9-first-fit-a-linear-model-including-just-numeric-variables-as-predictors" class="nav-link" data-scroll-target="#task-9-first-fit-a-linear-model-including-just-numeric-variables-as-predictors">Task 9 – First, fit a linear model including just numeric variables as predictors</a></li>
  <li><a href="#task-10-second-fit-a-linear-model-including-a-numeric-variable-and-a-factor-as-predictors" id="toc-task-10-second-fit-a-linear-model-including-a-numeric-variable-and-a-factor-as-predictors" class="nav-link" data-scroll-target="#task-10-second-fit-a-linear-model-including-a-numeric-variable-and-a-factor-as-predictors">Task 10 – Second, fit a linear model including a numeric variable and a factor as predictors</a></li>
  </ul></li>
  <li><a href="#step-6-use-linear-models-with-multiple-predictors-including-interaction-effects" id="toc-step-6-use-linear-models-with-multiple-predictors-including-interaction-effects" class="nav-link" data-scroll-target="#step-6-use-linear-models-with-multiple-predictors-including-interaction-effects">Step 6: Use linear models with multiple predictors, including interaction effects</a>
  <ul class="collapse">
  <li><a href="#introduce-make-some-new-moves-1" id="toc-introduce-make-some-new-moves-1" class="nav-link" data-scroll-target="#introduce-make-some-new-moves-1">Introduce: make some new moves</a></li>
  <li><a href="#task-11-center-numeric-variables-before-using-them-as-predictors" id="toc-task-11-center-numeric-variables-before-using-them-as-predictors" class="nav-link" data-scroll-target="#task-11-center-numeric-variables-before-using-them-as-predictors">Task 11 – Center numeric variables before using them as predictors</a></li>
  <li><a href="#hint-task-11" id="toc-hint-task-11" class="nav-link" data-scroll-target="#hint-task-11">Hint: Task 11</a></li>
  <li><a href="#task-12-specify-models-to-include-interaction-effects-interactions-between-two-numeric-predictor-variables" id="toc-task-12-specify-models-to-include-interaction-effects-interactions-between-two-numeric-predictor-variables" class="nav-link" data-scroll-target="#task-12-specify-models-to-include-interaction-effects-interactions-between-two-numeric-predictor-variables">Task 12 – Specify models to include interaction effects: interactions between two numeric predictor variables</a></li>
  <li><a href="#hint-task-12" id="toc-hint-task-12" class="nav-link" data-scroll-target="#hint-task-12">Hint: Task 12</a></li>
  <li><a href="#task-13-plot-model-predictions-to-help-with-interpretation-of-interaction-effects" id="toc-task-13-plot-model-predictions-to-help-with-interpretation-of-interaction-effects" class="nav-link" data-scroll-target="#task-13-plot-model-predictions-to-help-with-interpretation-of-interaction-effects">Task 13 – Plot model predictions to help with interpretation of interaction effects</a></li>
  <li><a href="#hint-task-13" id="toc-hint-task-13" class="nav-link" data-scroll-target="#hint-task-13">Hint: Task 13</a></li>
  <li><a href="#task-14-specify-models-to-include-interaction-effects-interactions-between-a-numeric-predictor-variable-and-a-factor-predictor-variable" id="toc-task-14-specify-models-to-include-interaction-effects-interactions-between-a-numeric-predictor-variable-and-a-factor-predictor-variable" class="nav-link" data-scroll-target="#task-14-specify-models-to-include-interaction-effects-interactions-between-a-numeric-predictor-variable-and-a-factor-predictor-variable">Task 14 – Specify models to include interaction effects: interactions between a numeric predictor variable and a factor predictor variable</a></li>
  <li><a href="#hint-task-14-we-follow-the-same-approach-that-we-followed-through-task-12." id="toc-hint-task-14-we-follow-the-same-approach-that-we-followed-through-task-12." class="nav-link" data-scroll-target="#hint-task-14-we-follow-the-same-approach-that-we-followed-through-task-12.">Hint: Task 14 – We follow the same approach that we followed through Task 12.</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PSYC122-w19-workbook-answers</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rob Davies </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In Week 19, we aim to <em>further develop</em> skills in working with the linear model.</p>
<p>We do this to learn how to answer research questions like:</p>
<ol type="1">
<li>What person attributes predict success in understanding?</li>
<li>Can people accurately evaluate whether they correctly understand written health information?</li>
</ol>
<p>In this class, what is new is our focus on critically evaluating the ways in which people, effects or results can vary using <em>interaction</em> analyses.</p>
<ul>
<li>This work simulates the kinds of interaction analyses that psychologists must often do in professional research.</li>
</ul>
<section id="naming-things" class="level2">
<h2 class="anchored" data-anchor-id="naming-things">Naming things</h2>
<p>I will format dataset names like this:</p>
<ul>
<li><code>all.data.csv</code></li>
</ul>
<p>I will also format variable (data column) names like this: <code>variable</code></p>
<p>I will also format value or other data object (e.g.&nbsp;cell value) names like this: <code>all.data</code></p>
<p>I will format functions and library names like this: e.g.&nbsp;function <code>ggplot()</code> or e.g.&nbsp;library <code>{tidyverse}</code>.</p>
</section>
<section id="the-data-we-will-be-using" class="level2">
<h2 class="anchored" data-anchor-id="the-data-we-will-be-using">The data we will be using</h2>
<p>In this how-to guide, we use data from:</p>
<p>(1.) two 2020 studies of the response of adults from a UK national sample to written health information</p>
<ul>
<li><code>study-one-general-participants.csv</code></li>
<li><code>study-two-general-participants.csv</code></li>
</ul>
<p>(2.) along with data recently collected from PSYC122 students.</p>
<p>These data have been joined together to create a dataset of over 400 observations. This is because it often requires a lot of evidence to be able to draw precise or accurate conclusions about potential interaction effects.</p>
</section>
</section>
<section id="answers" class="level1">
<h1>Answers</h1>
<section id="step-1-set-up" class="level2">
<h2 class="anchored" data-anchor-id="step-1-set-up">Step 1: Set-up</h2>
<p>To begin, we set up our environment in R.</p>
<section id="task-1-run-code-to-empty-the-r-environment" class="level3">
<h3 class="anchored" data-anchor-id="task-1-run-code-to-empty-the-r-environment">Task 1 – Run code to empty the R environment</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())                            </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="task-2-run-code-to-load-relevant-libraries" class="level3">
<h3 class="anchored" data-anchor-id="task-2-run-code-to-load-relevant-libraries">Task 2 – Run code to load relevant libraries</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggeffects"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"sjPlot"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"tidyverse"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.2
✔ purrr     1.2.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter()      masks stats::filter()
✖ dplyr::lag()         masks stats::lag()
✖ ggplot2::set_theme() masks sjPlot::set_theme()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
</section>
</section>
<section id="step-2-load-the-data" class="level2">
<h2 class="anchored" data-anchor-id="step-2-load-the-data">Step 2: Load the data</h2>
<section id="task-3-read-in-the-data-file-we-will-be-using" class="level3">
<h3 class="anchored" data-anchor-id="task-3-read-in-the-data-file-we-will-be-using">Task 3 – Read in the data file we will be using</h3>
<p>The data file is called:</p>
<ul>
<li><code>all-data.csv</code></li>
</ul>
<p>Use the <code>read_csv()</code> function to read the data file into R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>all.data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"all.data.csv"</span>)  </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 478 Columns: 11
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): participant_ID, study, GENDER, EDUCATION, ETHNICITY
dbl (6): mean.acc, mean.self, AGE, SHIPLEY, HLVA, FACTOR3

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
</section>
<section id="task-4-inspect-the-data-file" class="level3">
<h3 class="anchored" data-anchor-id="task-4-inspect-the-data-file">Task 4 – Inspect the data file</h3>
<p>Use the <code>summary()</code> function to take a look at the dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(all.data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> participant_ID        mean.acc        mean.self        study          
 Length:478         Min.   :0.3600   Min.   :2.250   Length:478        
 Class :character   1st Qu.:0.7500   1st Qu.:6.200   Class :character  
 Mode  :character   Median :0.8300   Median :7.200   Mode  :character  
                    Mean   :0.8066   Mean   :6.967                     
                    3rd Qu.:0.9000   3rd Qu.:7.910                     
                    Max.   :1.0000   Max.   :9.000                     
      AGE           SHIPLEY           HLVA           FACTOR3     
 Min.   :18.00   Min.   :19.00   Min.   : 2.000   Min.   : 9.00  
 1st Qu.:21.00   1st Qu.:31.00   1st Qu.: 7.000   1st Qu.:46.00  
 Median :29.00   Median :35.00   Median : 9.000   Median :50.00  
 Mean   :32.85   Mean   :34.19   Mean   : 8.929   Mean   :49.84  
 3rd Qu.:43.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00  
 Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00  
    GENDER           EDUCATION          ETHNICITY        
 Length:478         Length:478         Length:478        
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         </code></pre>
</div>
</div>
<p>Notice that we conducted a series of studies using the same online survey methods.</p>
<ul>
<li>Our data include the responses made by <em>PSYC122</em> students.</li>
</ul>
</section>
</section>
<section id="step-3-work-with-different-kinds-of-variables" class="level2">
<h2 class="anchored" data-anchor-id="step-3-work-with-different-kinds-of-variables">Step 3: Work with different kinds of variables</h2>
<p>It is an important skill in psychological data analysis to be able to:</p>
<p>(1.) identify the different kinds of data variables we are working with; (2.) adapt our methods depending on differences in kind (variable <code>Class</code> or type).</p>
<p>We learn about these skills, next, in exercises that combine some revision with some new moves.</p>
</section>
<section id="revise-consolidate-what-you-know" class="level2">
<h2 class="anchored" data-anchor-id="revise-consolidate-what-you-know">Revise: consolidate what you know</h2>
<section id="task-5-use-summaries-or-plots-to-examine-variables" class="level3">
<h3 class="anchored" data-anchor-id="task-5-use-summaries-or-plots-to-examine-variables">Task 5 – Use summaries or plots to examine variables</h3>
<ul>
<li><p>Q.1. What is the median of the <code>FACTOR3</code> variable in the dataset?</p></li>
<li><p>A.1. You can use the <code>summary()</code> function to calculate that the median <code>FACTOR3</code> score is 50.00</p></li>
<li><p>Q.2. Draw a histogram of the <code>FACTOR3</code> distribution.</p></li>
<li><p>A.2. You can write the code as you have been shown to do previously (e.g., in week 16):</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> all.data, <span class="fu">aes</span>(<span class="at">x =</span> FACTOR3)) <span class="sc">+</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Reading strategy (FACTOR3)"</span>, <span class="at">y =</span> <span class="st">"frequency count"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Q.3. Examine the reading strategy (<code>FACTOR3</code>) scores distribution: what does it tell you about the variation in the reading strategies of the participants in the sample?</li>
<li>A.3. The histogram shows that most participants present scores varying somewhere between 40-60 but there is a “long tail” of smaller numbers of participants with low or very low scores on the reading strategy (<code>FACTOR3</code>) measure.</li>
</ul>
</section>
</section>
<section id="extend-make-some-new-moves" class="level2">
<h2 class="anchored" data-anchor-id="extend-make-some-new-moves">Extend: make some new moves</h2>
<p>We can tell from the summary and the distribution that the <code>FACTOR3</code> variable consists of numbers.</p>
<p>Another way to identify what kind of variable we have is by using a check question:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(all.data<span class="sc">$</span>FACTOR3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(all.data<span class="sc">$</span>FACTOR3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>The <code>is._()</code> family of functions act like identity checks: what is this variable? These functions work like questions with TRUE or FALSE answers.</p>
<ul>
<li>Is this variable a factor? [TRUE or FALSE]</li>
<li>Is this variable numeric? [TRUE or FALSE]</li>
</ul>
</section>
<section id="revise-consolidate-what-you-know-1" class="level2">
<h2 class="anchored" data-anchor-id="revise-consolidate-what-you-know-1">Revise: consolidate what you know</h2>
<section id="task-6-identify-and-change-what-kind-of-variable-numeric-or-factor-a-variable-is" class="level3">
<h3 class="anchored" data-anchor-id="task-6-identify-and-change-what-kind-of-variable-numeric-or-factor-a-variable-is">Task 6 – Identify (and change) what kind of variable – numeric or factor – a variable is</h3>
<section id="hint-task-6-the-is._-functions-are-available-to-ask-what-kind-a-variable-is" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-6-the-is._-functions-are-available-to-ask-what-kind-a-variable-is">Hint: Task 6 – The <code>is._()</code> functions are available to ask what kind a variable is</h4>
</section>
<section id="hint-task-6-the-as._-functions-can-be-used-to-change-variable-types" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-6-the-as._-functions-can-be-used-to-change-variable-types">Hint: Task 6 – The <code>as._()</code> functions can be used to change variable types</h4>
<ul>
<li>Q.4. What kind of variable is <code>GENDER</code>?</li>
<li>A.4. Use the same functions but change the variable name:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.factor</span>(all.data<span class="sc">$</span>GENDER)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.numeric</span>(all.data<span class="sc">$</span>GENDER)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<ul>
<li><p>Q.5. What do the <code>is._()</code> functions tell us?</p></li>
<li><p>A.5. The function calls tell us that <code>GENDER</code> is not a factor and is not numeric.</p></li>
<li><p>Q.6. If you look at the <code>summary()</code> results, what does it tell you the <code>Class</code> of <code>GENDER</code> is?</p></li>
<li><p>A.6. The summary shows that <code>GENDER</code> is identified as <code>Class: character</code>.</p></li>
</ul>
<p>You can check this by doing the <code>is._()</code> test again.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.character</span>(all.data<span class="sc">$</span>GENDER)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<ul>
<li>Q.7. How do you change the class or type of the variable <code>GENDER</code>? Change the variable’s type (<code>Class</code>) into a factor.</li>
<li>A.7. The <code>as._()</code> functions can be used to change variable type, as you have done previously (e.g., in week 16).</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>all.data<span class="sc">$</span>GENDER <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(all.data<span class="sc">$</span>GENDER)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Q.8. What does a <code>summary()</code> tell us about <code>GENDER</code>?</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(all.data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> participant_ID        mean.acc        mean.self        study          
 Length:478         Min.   :0.3600   Min.   :2.250   Length:478        
 Class :character   1st Qu.:0.7500   1st Qu.:6.200   Class :character  
 Mode  :character   Median :0.8300   Median :7.200   Mode  :character  
                    Mean   :0.8066   Mean   :6.967                     
                    3rd Qu.:0.9000   3rd Qu.:7.910                     
                    Max.   :1.0000   Max.   :9.000                     
      AGE           SHIPLEY           HLVA           FACTOR3         GENDER   
 Min.   :18.00   Min.   :19.00   Min.   : 2.000   Min.   : 9.00   Female:323  
 1st Qu.:21.00   1st Qu.:31.00   1st Qu.: 7.000   1st Qu.:46.00   Male  :155  
 Median :29.00   Median :35.00   Median : 9.000   Median :50.00               
 Mean   :32.85   Mean   :34.19   Mean   : 8.929   Mean   :49.84               
 3rd Qu.:43.00   3rd Qu.:38.00   3rd Qu.:10.000   3rd Qu.:55.00               
 Max.   :76.00   Max.   :40.00   Max.   :14.000   Max.   :63.00               
  EDUCATION          ETHNICITY        
 Length:478         Length:478        
 Class :character   Class :character  
 Mode  :character   Mode  :character  
                                      
                                      
                                      </code></pre>
</div>
</div>
<ul>
<li>A.8. The summary will show how many different participants report themselves as belonging to one of the different <code>GENDER</code> self-identification groups in the corresponding survey question.</li>
</ul>
<p>You should see counts of the numbers of people in different <code>GENDER</code> level groups in the total survey sample:</p>
<p>GENDER Female:323 Male :155</p>
<p>We can see that 323 participants identified themselves as <code>Female</code> in the survey.</p>
<p>We can see that 155 participants identified themselves as <code>Male</code> in the survey.</p>
<section id="gender-identity-representation-in-survey-samples" class="level5">
<h5 class="anchored" data-anchor-id="gender-identity-representation-in-survey-samples">Gender identity representation in survey samples</h5>
<p>We note, here, that in addition to the numbers shown in the summary, six participants in the survey data entered the <code>Non-Binary</code> identification response option, and two participants entered the <code>Prefer not to say</code> option, in response to the gender identification question in the survey.</p>
<p>In the present exercises, we are looking at the way in which the effect on outcomes of variables – like variation in health literacy (<code>HLVA</code>) or reading strategy (<code>FACTOR3</code>) score – vary for different values of a categorical variable (like <code>GENDER</code>). These kinds of interactions become more complicated to analyse where there are more than two categories or levels in a factor, especially when the numbers of participants in one or more categories or levels is relatively small.</p>
<p>We think it is important to ensure representation of the responses and experiences of the full range of diversity among the populations we study. In future work, we hope to have collected sufficient numbers of observations from groups of participants like those entering responses like <code>Non-Binary</code> or <code>Prefer not to say</code> in order to be able to incorporate all possible between-group comparisons in analyses.</p>
<p>For now, we enter this explanation as a promise to to examine more representative samples in future work. Here is a link, for those who are interested, to reports of analyses of data from a survey conducted by a leading research organization (Pew Research Center). Follow the link to “Methodology” for information on how this organization exemplify good practice in obtaining representative samples.</p>
<p><a href="https://www.pewresearch.org/social-trends/2025/05/29/the-experiences-of-lgbtq-americans-today/" class="uri">https://www.pewresearch.org/social-trends/2025/05/29/the-experiences-of-lgbtq-americans-today/</a></p>
</section>
</section>
</section>
</section>
<section id="step-4-now-draw-plots-to-examine-associations-between-variables-and-to-visualize-interactions" class="level2">
<h2 class="anchored" data-anchor-id="step-4-now-draw-plots-to-examine-associations-between-variables-and-to-visualize-interactions">Step 4: Now draw plots to examine associations between variables and to visualize interactions</h2>
<p>Here, we are going to build on previous work to use plots to:</p>
<p>(1.) Examine the associations between pairs of variables, an outcome and a predictor (2.) Examine how the association between two variables can be different for different levels of a third variable</p>
<p>Scenario (2.) comes up if we are thinking about or working with <em>interaction</em> effects.</p>
<section id="consolidation-practice-to-strengthen-skills" class="level3">
<h3 class="anchored" data-anchor-id="consolidation-practice-to-strengthen-skills">Consolidation: practice to strengthen skills</h3>
</section>
<section id="task-7-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables" class="level3">
<h3 class="anchored" data-anchor-id="task-7-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables">Task 7 – Create a scatterplot to examine the association between two numeric variables</h3>
<section id="hint-task-7-we-are-working-with-geom_point-and-you-need-x-and-y-aesthetic-mappings." class="level4">
<h4 class="anchored" data-anchor-id="hint-task-7-we-are-working-with-geom_point-and-you-need-x-and-y-aesthetic-mappings.">Hint: Task 7 – We are working with <code>geom_point()</code> and you need x and y aesthetic mappings.</h4>
<p>Here, we can look at the potential association between variation in reading strategy (using the <code>FACTOR3</code> measure) and accuracy of understanding of health information (<code>mean.acc</code>).</p>
<p>Run a chunk of code to make the plot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> all.data, <span class="fu">aes</span>(<span class="at">x =</span> FACTOR3, <span class="at">y =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Accuracy of understanding (mean.acc)"</span>, </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Reading strategy (FACTOR3)"</span>) <span class="sc">+</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">65</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows:</p>
<ul>
<li>the possible association between x-axis variable <code>FACTOR3</code> and y-axis variable <code>mean.acc</code>.</li>
</ul>
<p>The plot code moves through the following steps:</p>
<ol type="1">
<li><code>ggplot(...)</code> make a plot;</li>
<li><code>ggplot(data = all.data, ...)</code> with the <code>all.data</code> dataset;</li>
<li><code>ggplot(...aes(x = FACTOR3, y = mean.acc))</code> using two aesthetic mappings</li>
</ol>
<ul>
<li><code>x = FACTOR3</code> map <code>FACTOR3</code> values to x-axis (horizontal, left to right) positions;</li>
<li><code>y = mean.acc</code> map <code>mean.acc</code> values to y-axis (vertical, bottom to top) positions;</li>
</ul>
<ol start="4" type="1">
<li><code>geom_point()</code> show the mappings as points.</li>
<li><code>theme_bw()</code> changes the theme to a white background.</li>
<li><code>labs(y = "Accuracy of understanding (mean.acc)", x = "Reading strategy (FACTOR3)")</code> changes axis labels.</li>
<li><code>xlim(0, 65) + ylim(0, 1)</code> changes axis limits.</li>
</ol>
</section>
<section id="questions-task-7" class="level4">
<h4 class="anchored" data-anchor-id="questions-task-7">Questions: Task 7</h4>
<ul>
<li><p>Q.9. What do you notice about the distribution of <code>mean.acc</code> scores at increasing values of reading strategy (<code>FACTOR3</code>) scores?</p></li>
<li><p>A.9. The scatterplot shows that, for increasing reading strategy (<code>FACTOR3</code>) scores, there is an associated rise in accuracy of understanding (<code>mean.acc</code>) scores.</p></li>
<li><p>There is extra credit for noticing that variation in outcome and predictor variable values is not tightly coupled: it is possible to have low reading strategy (<code>FACTOR3</code>) scores and high accuracy of understanding (<code>mean.acc</code>).</p></li>
</ul>
</section>
</section>
<section id="introduce-make-some-new-moves" class="level3">
<h3 class="anchored" data-anchor-id="introduce-make-some-new-moves">Introduce: make some new moves</h3>
<p>In the next sequence of exercises, we are going to take the <code>all.data</code> dataset and split it into parts (sub-sets) in different ways.</p>
<ul>
<li>We split the dataset vertically, into different sets of rows or observations.</li>
</ul>
<section id="why-are-we-learning-how-to-do-this" class="level4">
<h4 class="anchored" data-anchor-id="why-are-we-learning-how-to-do-this">Why are we learning how to do this?</h4>
<p>The capacity to do this kind of split-analyse operation is <em>extremely</em> useful.</p>
<p>We are going to do this so that we can examine how the effects of interest to us (here, associations) can vary between different groups of people.</p>
<ul>
<li><p>Remember, observations about different people are on different rows in <code>all.data</code>.</p></li>
<li><p>We are going to focus on an association between two column variables (<code>mean.acc</code>, <code>FACTOR3</code>).</p></li>
<li><p>We are going to identify different groups (sub-sets) of observations using values on a third variable.</p></li>
</ul>
</section>
</section>
<section id="task-8-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables-showing-how-the-association-is-different-for-different-values-of-a-third-variable" class="level3">
<h3 class="anchored" data-anchor-id="task-8-create-a-scatterplot-to-examine-the-association-between-two-numeric-variables-showing-how-the-association-is-different-for-different-values-of-a-third-variable">Task 8 – Create a scatterplot to examine the association between two numeric variables, showing how the association is different for different values of a third variable</h3>
<section id="hint-task-8-we-are-working-with-geom_point-again." class="level4">
<h4 class="anchored" data-anchor-id="hint-task-8-we-are-working-with-geom_point-again.">Hint: Task 8 – We are working with <code>geom_point()</code> again.</h4>
</section>
<section id="hint-task-8-we-can-show-how-the-association-between-two-variables-mean.acc-factor3-is-different-for-different-values-of-a-third-categorical-factor-variable-gender-by-splitting-the-plot-so-that-we-see-the-association-for-different-levels-of-gender." class="level4">
<h4 class="anchored" data-anchor-id="hint-task-8-we-can-show-how-the-association-between-two-variables-mean.acc-factor3-is-different-for-different-values-of-a-third-categorical-factor-variable-gender-by-splitting-the-plot-so-that-we-see-the-association-for-different-levels-of-gender.">Hint: Task 8 – We can show how the association between two variables (<code>mean.acc</code>, <code>FACTOR3</code>) is different for different values of a third, categorical (factor), variable (<code>GENDER</code>) by splitting the plot so that we see the association for different levels of <code>GENDER</code>.</h4>
<p>Here, we are splitting the dataset into:</p>
<ul>
<li>observation data from people with just <code>GENDER</code> level <code>Female</code></li>
<li>observation data from people with just <code>GENDER</code> level <code>Male</code></li>
</ul>
<p>and we are then producing a different scatterplot for each sub-set of data produced by the split.</p>
<p>Run the following chunk of code to make the plot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> all.data, <span class="fu">aes</span>(<span class="at">x =</span> FACTOR3, <span class="at">y =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Accuracy of understanding (mean.acc)"</span>, </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Reading strategy (FACTOR3)"</span>) <span class="sc">+</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">65</span>) <span class="sc">+</span> <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> GENDER)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot shows:</p>
<ul>
<li>the possible association between x-axis variable <code>FACTOR3</code> and y-axis variable <code>mean.acc</code></li>
<li>for different groups of people – people with self-reported <code>GENDER</code> responses of <code>Female</code> or <code>Male</code>.</li>
</ul>
<p>The plot code moves through steps we have seen before. What is new here is this bit:</p>
<p><code>facet_wrap(~ GENDER)</code></p>
<p>The function <code>facet_wrap()</code> splits the dataset into sub-sets (different parts): different sets of rows, where different sets are defined according to different values of the variable identified inside the brackets <code>(~ GENDER)</code>.</p>
<p>Here, we are asking for different scatterplots for the dataset split by whether participants are coded as <code>Female</code> or <code>Male</code> for this survey.</p>
<p>You can see a general guide to the function here:</p>
<p><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html" class="uri">https://ggplot2.tidyverse.org/reference/facet_wrap.html</a></p>
</section>
<section id="questions-task-8" class="level4">
<h4 class="anchored" data-anchor-id="questions-task-8">Questions: Task 8</h4>
<ul>
<li><p>Q.10. What do you notice about the distribution of <code>mean.acc</code> scores at increasing values of reading strategy (<code>FACTOR3</code>) scores, for different sub-sets of the data: for people with <code>Female</code> or <code>Male</code> <code>GENDER</code> coding?</p></li>
<li><p>A.10. You can see that the association between <code>mean.acc</code> and <code>FACTOR3</code> scores appears to be <em>mostly</em> similar for different <code>GENDER</code> codes.</p></li>
<li><p>The distribution of scores is different: we have more <code>Female</code> participants; their scores vary more widely.</p></li>
<li><p>But the trend is similar overall: the trend line representing the association between <code>mean.acc</code> and <code>FACTOR3</code> looks similar such that for both sub-groups in the sample, increasing <code>FACTOR3</code> scores are associated with higher <code>mean.acc</code> scores.</p></li>
</ul>
</section>
<section id="hint-task-8-we-can-show-how-the-association-between-two-variables-mean.acc-factor3-is-different-for-different-values-of-a-third-numeric-variable-hlva-by-splitting-the-dataset" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-8-we-can-show-how-the-association-between-two-variables-mean.acc-factor3-is-different-for-different-values-of-a-third-numeric-variable-hlva-by-splitting-the-dataset">Hint: Task 8 – We can show how the association between two variables (<code>mean.acc</code>, <code>FACTOR3</code>) is different for different values of a third numeric variable (<code>HLVA</code>) by splitting the dataset</h4>
<p>Here, we are first creating a new variable to code for (distinguish between) different sub-sets of observations (different rows in the dataset) based on <code>HLVA</code> scores, and then second drawing different plots based on different subsets.</p>
<p>We do this in two steps, as follows.</p>
<p>First, run a chunk of code to divide (<code>cut</code>) the dataset into parts:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>all.data<span class="sc">$</span>HLVA_splits <span class="ot">&lt;-</span> <span class="fu">cut_number</span>(all.data<span class="sc">$</span>HLVA, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The code works bit-by-bit like this:</p>
<ol type="1">
<li><code>all.data$HLVA_splits &lt;-</code> create a new variable, <code>HLVA_splits</code> and add it to the dataset <code>all.data</code> given the work done by the bit of code on the right of the arrow <code>&lt;-</code>.</li>
</ol>
<p>On the right of the arrow <code>&lt;-</code> …</p>
<ol start="2" type="1">
<li><code>cut_number(all.data$HLVA, 3)</code> uses the <code>cut_number(...)</code> to divide the dataset observations into three sets based on the values in the <code>all.data$HLVA</code> variable named inside the brackets.</li>
</ol>
<p>The function works by ordering all the observations (the rows) in the dataset according to the values in the named variable <code>all.data$HLVA</code>, then splitting the dataset (here, into three sub-sets) based on values in that named variable.</p>
<ul>
<li>Given this code, we are going to get three sub-sets of the data, observations corresponding to (1.) low (2.) mid or (3.) high <code>HLVA</code> values.</li>
<li>We split the data into data about people with:</li>
</ul>
<p>(1.) low <code>HLVA</code> values, scores between 2-8 on the <code>HLVA</code> test; (2.) mid <code>HLVA</code> values, scores between 8-10 on the <code>HLVA</code> test; (3.) high <code>HLVA</code> values, scores between 10-14 on the <code>HLVA</code> test.</p>
<p>You can see a guide to the function here:</p>
<p><a href="https://ggplot2.tidyverse.org/reference/cut_interval.html" class="uri">https://ggplot2.tidyverse.org/reference/cut_interval.html</a></p>
<p>Note that <em>where</em> we split the data (what ranges of scores we use) will depend on the sample.</p>
<p>Second, we draw a plot to examine if the association between two variables (<code>mean.acc</code>, <code>HLVA</code>) is different for different values of a third variable (<code>SHIPLEY</code>) by splitting the data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> all.data, <span class="fu">aes</span>(<span class="at">x =</span> FACTOR3, <span class="at">y =</span> mean.acc)) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>) <span class="sc">+</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> HLVA_splits, <span class="at">nrow =</span> <span class="dv">1</span>, <span class="at">labeller =</span> label_both) <span class="sc">+</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Accuracy of understanding (mean.acc)"</span>, </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Reading strategy (FACTOR3)"</span>) <span class="sc">+</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot code moves through the scatterplot production steps we have seen before.</p>
<p>The bit that is new is here:</p>
<p><code>facet_wrap(~ HLVA_splits, nrow = 1, labeller = label_both)</code> which is included to use the data split, constructed earlier.</p>
<p>This addition allows us to show:</p>
<ul>
<li>the nature of the association between two variables (<code>mean.acc</code>, <code>FACTOR3</code>)</li>
<li>for different values of the third variable (<code>HLVA</code>)</li>
<li>by splitting the data into three sub-sets according to <code>HLVA</code> score (2-8 low, 8-10 mid, 10-14 high).</li>
</ul>
</section>
<section id="questions-task-8-1" class="level4">
<h4 class="anchored" data-anchor-id="questions-task-8-1">Questions: Task 8</h4>
<ul>
<li><p>Q.11. What do you notice about the distribution of <code>mean.acc</code> scores at increasing values of reading strategy (<code>FACTOR3</code>) scores, for different sub-sets of the data: for (1.) low (2.) mid (3.) high <code>HLVA</code> values?</p></li>
<li><p>A.11. You can see that the association between <code>mean.acc</code> and <code>FACTOR3</code> scores appears to vary (the slope differs) given different values of the third variable (<code>HLVA</code>).</p></li>
<li><p>Q.12. What do you think the values in the grey labels at the top of the facets (the plot panels) tell us?</p></li>
<li><p>A.12. The values tell us what values (e.g., <code>2,8</code>) are used to identify the range of <code>HLVA</code> scores that have been used to define the sub-set of observations for which the plot below shows the association between <code>mean.acc</code> and <code>FACTOR3</code> scores.</p></li>
</ul>
</section>
</section>
</section>
<section id="step-5-use-linear-models-with-multiple-predictors-to-estimate-the-effects-of-factors-as-well-as-numeric-variables" class="level2">
<h2 class="anchored" data-anchor-id="step-5-use-linear-models-with-multiple-predictors-to-estimate-the-effects-of-factors-as-well-as-numeric-variables">Step 5: Use linear models with multiple predictors, to estimate the effects of factors as well as numeric variables</h2>
<section id="consolidation-practice-to-strengthen-skills-1" class="level3">
<h3 class="anchored" data-anchor-id="consolidation-practice-to-strengthen-skills-1">Consolidation: practice to strengthen skills</h3>
<p>As we saw in weeks 17 and 18, we can use linear models to predict outcome variables.</p>
<ul>
<li>Linear models can include numeric variables (like <code>FACTOR3</code> or <code>HLVA</code>) as predictors.</li>
<li>Linear models can also include categorical variables or factors (like <code>GENDER</code> or <code>EDUCATION</code>) as predictors.</li>
</ul>
</section>
<section id="task-9-first-fit-a-linear-model-including-just-numeric-variables-as-predictors" class="level3">
<h3 class="anchored" data-anchor-id="task-9-first-fit-a-linear-model-including-just-numeric-variables-as-predictors">Task 9 – First, fit a linear model including just numeric variables as predictors</h3>
<section id="hint-task-9-we-use-the-lm-function-to-fit-a-model-with-mean.acc-as-the-outcome-and-factor3-and-hlva-as-predictors." class="level4">
<h4 class="anchored" data-anchor-id="hint-task-9-we-use-the-lm-function-to-fit-a-model-with-mean.acc-as-the-outcome-and-factor3-and-hlva-as-predictors.">Hint: Task 9 – We use the <code>lm()</code> function to fit a model with <code>mean.acc</code> as the outcome and <code>FACTOR3</code> and <code>HLVA</code> as predictors.</h4>
<p>Note that in this model:</p>
<ul>
<li><code>FACTOR3</code> is a measure of reading strategy – numeric scores correspond to a test of the relative effectiveness of the strategies participants use to read and understand written information;</li>
<li><code>HLVA</code> is a measure of health literacy – numeric scores correspond to a test of knowledge of health-related words.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> FACTOR3 <span class="sc">+</span> HLVA, </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> all.data)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ FACTOR3 + HLVA, data = all.data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.38243 -0.06507  0.01136  0.07686  0.27637 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.4956473  0.0403305  12.290   &lt;2e-16 ***
FACTOR3     0.0023489  0.0007874   2.983    0.003 ** 
HLVA        0.0217126  0.0024504   8.861   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1139 on 475 degrees of freedom
Multiple R-squared:  0.1834,    Adjusted R-squared:   0.18 
F-statistic: 53.35 on 2 and 475 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If you look at the model summary you can answer the following questions.</p>
<ul>
<li><p>Q.13. What is the estimate for the coefficient of the effect of the predictor, <code>FACTOR3</code> (reading strategy)?</p></li>
<li><p>A.13. 0.0023489</p></li>
<li><p>Q.14. Is the effect significant?</p></li>
<li><p>A.14. It is significant. Because <code>Pr(&gt;|t|)</code> equals <code>0.003</code> for the <code>Estimate</code> of the effect of <code>FACTOR3</code> (reading strategy): this means that p &lt; .05, and so the effect is significant.</p></li>
<li><p>Q.15. What are the values for t and p for the significance test for the estimated coefficient of the effect of <code>HLVA</code> (health literacy)?</p></li>
<li><p>A.15. t = 8.861, p = &lt;2e-16</p></li>
</ul>
</section>
<section id="hint-task-9-do-you-know-how-to-intepret-numbers-like-2e-16-if-you-are-unsure-you-can-find-out-about-scientific-notation-here" class="level4">
<h4 class="anchored" data-anchor-id="hint-task-9-do-you-know-how-to-intepret-numbers-like-2e-16-if-you-are-unsure-you-can-find-out-about-scientific-notation-here">Hint: Task 9 – Do you know how to intepret numbers like <code>&lt;2e-16</code>? If you are unsure you can find out about scientific notation here:</h4>
<p><a href="https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php" class="uri">https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php</a></p>
<ul>
<li>Q.16. What do you conclude are the effects of the <code>FACTOR3</code> (reading strategy) and <code>HLVA</code> (health literacy) variables, as predictors of outcome <code>mean.acc</code> (accuracy of understanding of health information)?</li>
<li>A.16. The model slope estimates suggests that both predictors are significant, and that as both <code>FACTOR3</code> (reading strategy) and <code>HLVA</code> (health literacy) increase, so <code>mean.acc</code> scores are predicted to increase also.</li>
</ul>
</section>
</section>
<section id="task-10-second-fit-a-linear-model-including-a-numeric-variable-and-a-factor-as-predictors" class="level3">
<h3 class="anchored" data-anchor-id="task-10-second-fit-a-linear-model-including-a-numeric-variable-and-a-factor-as-predictors">Task 10 – Second, fit a linear model including a numeric variable and a factor as predictors</h3>
<section id="hint-task-10-we-use-the-lm-function-to-fit-a-model-with-mean.acc-as-the-outcome-and-factor3-and-gender-as-predictors." class="level4">
<h4 class="anchored" data-anchor-id="hint-task-10-we-use-the-lm-function-to-fit-a-model-with-mean.acc-as-the-outcome-and-factor3-and-gender-as-predictors.">Hint: Task 10 – We use the <code>lm()</code> function to fit a model with <code>mean.acc</code> as the outcome and <code>FACTOR3</code> and <code>GENDER</code> as predictors.</h4>
<p>Note that in this model:</p>
<ul>
<li><code>FACTOR3</code> is a measure of reading strategy – numeric scores correspond to a test of strategy awareness</li>
<li><code>GENDER</code> is a self-report measure of gender identity</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> FACTOR3 <span class="sc">+</span> GENDER, </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> all.data)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ FACTOR3 + GENDER, data = all.data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.43448 -0.06809  0.02190  0.09104  0.30596 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.6074530  0.0415532  14.619  &lt; 2e-16 ***
FACTOR3      0.0040658  0.0008237   4.936  1.1e-06 ***
GENDERMale  -0.0108184  0.0120051  -0.901    0.368    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1228 on 475 degrees of freedom
Multiple R-squared:  0.05007,   Adjusted R-squared:  0.04607 
F-statistic: 12.52 on 2 and 475 DF,  p-value: 5.036e-06</code></pre>
</div>
</div>
<p>If you look at the model summary you can answer the following questions.</p>
<ul>
<li><p>Q.17. What is the estimate for the coefficient of the effect of the predictor, <code>FACTOR3</code> (strategy)?</p></li>
<li><p>A.17. 0.0040658</p></li>
<li><p>Q.18. Is the effect significant?</p></li>
<li><p>A.18. It is significant. Because <code>Pr(&gt;|t|)</code> equals <code>1.1e-06</code> for the <code>Estimate</code> of the effect of <code>FACTOR3</code> (strategy): this means that p &lt; .05, and so the effect is significant.</p></li>
<li><p>Q.19. What are the values for t and p for the significance test for the estimated coefficient of the effect of <code>GENDER</code> (level, <code>Male</code> compared to <code>Female</code>)?</p></li>
<li><p>A.19. t = -0.901, p = 0.368</p></li>
<li><p>Q.20. Is the effect of <code>GENDER</code> significant?</p></li>
<li><p>A.20. It is not significant. Because <code>Pr(&gt;|t|)</code> equals <code>0.635</code> for the <code>Estimate</code> of the effect of <code>GENDER</code> this means that p &gt; .05, and so the effect is not significant.</p></li>
</ul>
</section>
<section id="hint-task-10-how-do-we-know-how-to-interpret-estimates-for-the-effects-of-factors-we-discussed-how-r-deals-with-factors-in-week-18-and-discuss-factors-and-the-effects-of-factors-in-the-week-19-lecture." class="level4">
<h4 class="anchored" data-anchor-id="hint-task-10-how-do-we-know-how-to-interpret-estimates-for-the-effects-of-factors-we-discussed-how-r-deals-with-factors-in-week-18-and-discuss-factors-and-the-effects-of-factors-in-the-week-19-lecture.">Hint: Task 10 – How do we know how to interpret estimates for the effects of factors? We discussed how R deals with factors in week 18, and discuss factors, and the effects of factors, in the week 19 lecture.</h4>
<ul>
<li><p>Q.21. How should we interpret the coefficient estimate for the effect of <code>GENDER</code>?</p></li>
<li><p>A.21. Though the effect is not significant, we can say that, on average, outcome <code>mean.acc</code> is -0.0108184 (slightly) lower for <code>Male</code> compared to <code>Female</code> coded people.</p></li>
<li><p>Q.22. What do you conclude are the effects of the <code>FACTOR3</code> (strategy) and <code>GENDER</code> (<code>Female</code> compared to <code>Male</code>) variables, as predictors of outcome <code>mean.acc</code> (accuracy of understanding of health information)?</p></li>
<li><p>A.22. The model slope estimates suggest that gender does not have a significant effect but that as <code>FACTOR3</code> (strategy) scores increase, so <code>mean.acc</code> scores are predicted to increase.</p></li>
</ul>
</section>
</section>
</section>
<section id="step-6-use-linear-models-with-multiple-predictors-including-interaction-effects" class="level2">
<h2 class="anchored" data-anchor-id="step-6-use-linear-models-with-multiple-predictors-including-interaction-effects">Step 6: Use linear models with multiple predictors, including interaction effects</h2>
<section id="introduce-make-some-new-moves-1" class="level3">
<h3 class="anchored" data-anchor-id="introduce-make-some-new-moves-1">Introduce: make some new moves</h3>
<p>As we saw through Task 8, it is possible that:</p>
<ul>
<li>the association between two variables (<code>mean.acc</code>, <code>FACTOR3</code>) can be different for different values of a third categorical (factor) variable (<code>GENDER</code>);</li>
<li>the association between two variables (<code>mean.acc</code>, <code>FACTOR3</code>) can be different for different values of a third variable (<code>HLVA</code>)</li>
</ul>
<p>While we can examine these possibilities using visualizations, we often need to conduct statistical analyses to test <em>interaction effects</em>, or the ways in which the association between two variables can be different for different levels of a third variable.</p>
<p>We can extend linear models to include terms that allow us to test or to estimate <em>interaction effects</em>.</p>
</section>
<section id="task-11-center-numeric-variables-before-using-them-as-predictors" class="level3">
<h3 class="anchored" data-anchor-id="task-11-center-numeric-variables-before-using-them-as-predictors">Task 11 – Center numeric variables before using them as predictors</h3>
</section>
<section id="hint-task-11" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-11">Hint: Task 11</h3>
<p>When we include numeric variables (e.g., <code>FACTOR3, HLVA, SHIPLEY</code>) in linear models, it can cause problems of interpretation or of estimation if we include the variables as they first come to us in datasets (as <em>raw</em> variables).</p>
<ul>
<li>It often helps our analyses to <em>center</em> variables on their means.</li>
<li>Centering a variable means calculating its mean, and then subtracting that mean from every value in the variable column.</li>
</ul>
<p>For example, to center values of the <code>HLVA</code> variable, we create a new column <code>data$HLVA_centered</code> by first calculating the mean of the <code>data$HLVA</code> variable, and then subtracting that mean from every row value in <code>data$HLVA</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>all.data<span class="sc">$</span>HLVA_centered <span class="ot">&lt;-</span> all.data<span class="sc">$</span>HLVA <span class="sc">-</span> <span class="fu">mean</span>(all.data<span class="sc">$</span>HLVA, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><p>Q.23. Can you check what is going on when we center variables?</p></li>
<li><p>Hint: You can see what is happening when you run this code by first calculating the mean for <code>HLVA</code></p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(all.data<span class="sc">$</span>HLVA, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8.92887</code></pre>
</div>
</div>
<p>then looking at column values in the new <code>HLVA_centered</code> column, compared to the original <code>HLVA</code> column:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>all.data <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(HLVA_centered, HLVA) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 478 × 2
   HLVA_centered  HLVA
           &lt;dbl&gt; &lt;dbl&gt;
 1       -1.93       7
 2       -0.929      8
 3        2.07      11
 4        4.07      13
 5        0.0711     9
 6       -2.93       6
 7       -1.93       7
 8       -0.929      8
 9        1.07      10
10        4.07      13
11        1.07      10
12        2.07      11
13       -0.929      8
14        1.07      10
15        1.07      10
16        1.07      10
17        3.07      12
18        1.07      10
19       -1.93       7
20       -2.93       6
# ℹ 458 more rows</code></pre>
</div>
</div>
<ul>
<li><p>What is the difference between the <code>HLVA</code> and <code>HLVA_centered</code> columns?</p></li>
<li><p>A.23. You can see that every value in the <code>HLVA_centered</code> column equals the value, on the same row, in the <code>HLVA</code> column, minus the mean for <code>HLVA</code>.</p></li>
<li><p>Q.24. Can you center the variable <code>FACTOR3</code>?</p></li>
<li><p>A.24. You can use the same code to center <code>FACTOR3</code>:</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>all.data<span class="sc">$</span>FACTOR3_centered <span class="ot">&lt;-</span> all.data<span class="sc">$</span>FACTOR3 <span class="sc">-</span> <span class="fu">mean</span>(all.data<span class="sc">$</span>FACTOR3, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Q.25. Can you center the variable <code>SHIPLEY</code>?</li>
<li>A.25. You can use the same code to center <code>SHIPLEY</code>:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>all.data<span class="sc">$</span>SHIPLEY_centered <span class="ot">&lt;-</span> all.data<span class="sc">$</span>SHIPLEY <span class="sc">-</span> <span class="fu">mean</span>(all.data<span class="sc">$</span>SHIPLEY, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="why-are-we-learning-how-to-do-this-1" class="level4">
<h4 class="anchored" data-anchor-id="why-are-we-learning-how-to-do-this-1">Why are we learning how to do this?</h4>
<p>It is common in data analysis to want to transform variables before using them in analyses.</p>
<ul>
<li>Here, we are transforming predictor variables by centering them on their mean values.</li>
</ul>
<p>The practical reason for doing this transformation now is because if we use uncentered (raw) numeric variables as predictors in linear models that involve interactions the model can find it difficult to distinguish between the effects of those predictors and the effect of their interaction.</p>
</section>
</section>
<section id="task-12-specify-models-to-include-interaction-effects-interactions-between-two-numeric-predictor-variables" class="level3">
<h3 class="anchored" data-anchor-id="task-12-specify-models-to-include-interaction-effects-interactions-between-two-numeric-predictor-variables">Task 12 – Specify models to include interaction effects: interactions between two numeric predictor variables</h3>
</section>
<section id="hint-task-12" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-12">Hint: Task 12</h3>
<p>We use <code>lm()</code> to specify models, as we have been doing.</p>
<ul>
<li>What changes is that we now use the <code>*</code> operator in our model code to specify interaction effects.</li>
</ul>
<p>For example, let’s suppose that we want to examine the possibility that the effect of reading strategy (<code>FACTOR3</code>) on accuracy understanding (<code>mean.acc</code>) is different for different values of health literacy (<code>HLVA</code>).</p>
<ul>
<li>Here, we are considering the possibility that the association between reading strategy (<code>FACTOR3</code>) and accuracy of understanding (<code>mean.acc</code>) <em>varies</em>.</li>
<li>We are considering the possibility that the the association between reading strategy (<code>FACTOR3</code>) and accuracy of understanding (<code>mean.acc</code>) is different for different groups of people.</li>
<li>We are considering the possibility that the effect of reading strategy (<code>FACTOR3</code>) on accuracy of understanding (<code>mean.acc</code>) is different for people who differ, also, in health literacy (<code>HLVA</code>).</li>
</ul>
<p>In examining the possibility that the effect of reading strategy (<code>FACTOR3</code>) on accuracy of understanding (<code>mean.acc</code>) is different for different values of health literacy (<code>HLVA</code>), we are examining a possible <em>interaction</em> between the effects of reading strategy (<code>FACTOR3</code>) and health literacy (<code>HLVA</code>).</p>
<p>Let’s go through this step-by-step.</p>
<p>First, consider: if we ignored the possibility of an interaction, we would fit a model with just the predictors: reading strategy (<code>FACTOR3</code>) and health literacy (<code>HLVA</code>).</p>
<p>We can fit the same model that we fit before (for Task 9).</p>
<ul>
<li>We vary the code a little, by using the centered variables we have just created:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> FACTOR3_centered <span class="sc">+</span> HLVA_centered, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> all.data)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ FACTOR3_centered + HLVA_centered, data = all.data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.38243 -0.06507  0.01136  0.07686  0.27637 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      0.8065870  0.0052095 154.830   &lt;2e-16 ***
FACTOR3_centered 0.0023489  0.0007874   2.983    0.003 ** 
HLVA_centered    0.0217126  0.0024504   8.861   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1139 on 475 degrees of freedom
Multiple R-squared:  0.1834,    Adjusted R-squared:   0.18 
F-statistic: 53.35 on 2 and 475 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>Q.26. Can you compare the summary of results for this model with the model, using the same (but not centered) predictors, that you fitted for Task 9 – compare the estimates, what do you see?</p></li>
<li><p>A.26. If we compare the results of the models we can see that the estimates, t-test values and probability values are the same for <code>FACTOR3</code> compared to <code>FACTOR3_centered</code> or for <code>HLVA</code> compared to <code>HLVA_centered</code>.</p></li>
<li><p>This shows that centering predictors only changes the scaling of the predictor variables so that their centers are 0.</p></li>
</ul>
<p>Second, now consider: we aim to test or estimate the interactions between the effects of reading strategy (<code>FACTOR3_centered</code>) and health literacy (<code>HLVA_centered</code>).</p>
<ul>
<li>We vary the code a little, again, this time by separating the predictors by <code>*</code> not by <code>+</code>:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> FACTOR3_centered<span class="sc">*</span>HLVA_centered, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> all.data)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ FACTOR3_centered * HLVA_centered, data = all.data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.36935 -0.06267  0.01487  0.07646  0.32573 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     0.8086743  0.0053507 151.133  &lt; 2e-16 ***
FACTOR3_centered                0.0022694  0.0007874   2.882  0.00413 ** 
HLVA_centered                   0.0213896  0.0024537   8.717  &lt; 2e-16 ***
FACTOR3_centered:HLVA_centered -0.0005713  0.0003452  -1.655  0.09857 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1137 on 474 degrees of freedom
Multiple R-squared:  0.1881,    Adjusted R-squared:  0.183 
F-statistic: 36.61 on 3 and 474 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>Q.27. Can you compare the summary of results for this model with the results for the previous model (which uses the same predictors but without an interaction)?</p></li>
<li><p>What do you see?</p></li>
<li><p>A.27. If we compare the results of the models we can see that now the summary gives us estimates for the effects of:</p></li>
<li><p><code>FACTOR3_centered</code> – this is the effect of <code>SHIPLEY_centered</code> when <code>HLVA_centered</code> is 0</p></li>
<li><p><code>HLVA_centered</code> – this is the effect of <code>HLVA_centered</code> when <code>FACTOR3_centered</code> is 0</p></li>
<li><p><code>FACTOR3_centered*HLVA_centered</code> – this is the interaction, and reflects the change in the effect of <code>FACTOR3_centered</code> on outcome <code>mean.acc</code>, given different values of <code>HLVA_centered</code>.</p></li>
<li><p>Notice that the effect of the interaction is not significant but that the results suggest a very slight tendencey for the effect of reading strategy to be different (smaller) for increasing values of <code>HLVA_centered</code>.</p></li>
</ul>
<section id="what-are-we-learning-here" class="level4">
<h4 class="anchored" data-anchor-id="what-are-we-learning-here">What are we learning here?</h4>
<p>The <code>*</code> symbol (the <code>*</code> operator) is used here to code for a model including the effects of the two variables separated by the symbol, here, as well as the effect of the interaction between these two variables.</p>
</section>
</section>
<section id="task-13-plot-model-predictions-to-help-with-interpretation-of-interaction-effects" class="level3">
<h3 class="anchored" data-anchor-id="task-13-plot-model-predictions-to-help-with-interpretation-of-interaction-effects">Task 13 – Plot model predictions to help with interpretation of interaction effects</h3>
</section>
<section id="hint-task-13" class="level3">
<h3 class="anchored" data-anchor-id="hint-task-13">Hint: Task 13</h3>
<p>How do we interpret interactions?</p>
<ul>
<li>It helps to plot model predictions, given the effects estimates that we derive from our sample using the linear model.</li>
</ul>
<p>We can do this in a two-step sequence, similar to the sequence we trialled through weeks 17 and 18:</p>
<ol type="1">
<li>First fit the model</li>
<li>Second, use the model information to plot the predictions, given the effects</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -- first fit the model</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> FACTOR3_centered<span class="sc">*</span>HLVA_centered, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> all.data)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="co"># -- make plot</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(model, <span class="at">type =</span> <span class="st">"pred"</span>, </span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"FACTOR3_centered"</span>, <span class="st">"HLVA_centered"</span>)) <span class="sc">+</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale for y is already present.
Adding another scale for y, which will replace the existing scale.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Q.28. Can you compare the summary of results for the model with the plot to develop an interpretation of the <code>FACTOR3_centered*HLVA_centered</code> interaction?</p></li>
<li><p>What do you see?</p></li>
<li><p>A.28. We can build an interpretation in steps:</p></li>
<li><p>If we look at the coefficient estimate for the <code>FACTOR3_centered*HLVA_centered</code> interaction, we can see that it is negative (<code>-0.0005713</code>).</p></li>
<li><p>If we look at the plot of the model predictions, we can see that there are three slopes for the <code>FACTOR3_centered</code> effect, one each for different levels of <code>HLVA_centered</code>: for <code>HLVA_centered</code> = -2.19; <code>HLVA_centered</code> = 0; and <code>HLVA_centered</code> = 2.19.</p></li>
<li><p>Notice that the steepness of the slope of the <code>FACTOR3_centered</code> effect decreases (the slope gets less steep) from <code>HLVA_centered</code> = -2.19 to <code>HLVA_centered</code> = 2.19.</p></li>
<li><p>This tells us that the interaction (though not significant) operates so that the effect of reading strategy tends to be smaller for people with higher levels of health literacy.</p></li>
<li><p>Returning to the fact that the coefficient estimate for the <code>FACTOR3_centered*HLVA_centered</code> is negative, we can now understand that it is negative because the interaction operates so that the slope of the <code>FACTOR3_centered</code> gets smaller as scores on <code>HLVA_centered</code> increase.</p></li>
</ul>
</section>
<section id="task-14-specify-models-to-include-interaction-effects-interactions-between-a-numeric-predictor-variable-and-a-factor-predictor-variable" class="level3">
<h3 class="anchored" data-anchor-id="task-14-specify-models-to-include-interaction-effects-interactions-between-a-numeric-predictor-variable-and-a-factor-predictor-variable">Task 14 – Specify models to include interaction effects: interactions between a numeric predictor variable and a factor predictor variable</h3>
</section>
<section id="hint-task-14-we-follow-the-same-approach-that-we-followed-through-task-12." class="level3">
<h3 class="anchored" data-anchor-id="hint-task-14-we-follow-the-same-approach-that-we-followed-through-task-12.">Hint: Task 14 – We follow the same approach that we followed through Task 12.</h3>
<p>Now consider: we aim to test or estimate the interactions between the effects of reading strategy (<code>FACTOR3</code>) and gender (<code>GENDER</code>).</p>
<ul>
<li>We vary the code to change the predictor variables but the structure otherwise stays the same:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> FACTOR3_centered<span class="sc">*</span>GENDER, </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> all.data)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mean.acc ~ FACTOR3_centered * GENDER, data = all.data)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.43542 -0.07087  0.02173  0.09156  0.29573 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  0.8100751  0.0068412 118.412  &lt; 2e-16 ***
FACTOR3_centered             0.0038150  0.0009700   3.933 9.64e-05 ***
GENDERMale                  -0.0109063  0.0120160  -0.908    0.365    
FACTOR3_centered:GENDERMale  0.0009027  0.0018404   0.490    0.624    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1229 on 474 degrees of freedom
Multiple R-squared:  0.05055,   Adjusted R-squared:  0.04454 
F-statistic: 8.412 on 3 and 474 DF,  p-value: 1.86e-05</code></pre>
</div>
</div>
<ul>
<li><p>Q.29. Can you identify what effects are shown in the model summary?</p></li>
<li><p>A.29. We can see that now the summary gives us estimates for the effects of:</p></li>
<li><p><code>FACTOR3_centered</code> – this is the effect of reading strategy (<code>FACTOR3</code>) when <code>GENDER</code> level is <code>Female</code></p></li>
<li><p><code>GENDERMale</code> – this is the effect of <code>GENDER</code> when <code>FACTOR3_centered</code> is 0.</p></li>
</ul>
<p>Note that the effect of <code>GENDER</code> is the estimated difference in outcome when <code>GENDER</code> level is <code>Female</code> (not shown, treated as the baseline) compared to when <code>GENDER</code> level is <code>Male</code>.</p>
<ul>
<li><code>FACTOR3_centered*GENDER</code> – this is the interaction, and reflects the change in the effect of <code>FACTOR3_centered</code> on outcome <code>mean.acc</code>, given different values of <code>GENDER</code>, here, when <code>GENDER</code> is <code>Male</code> instead of <code>Female</code>.</li>
</ul>
<section id="what-are-we-learning-here-1" class="level4">
<h4 class="anchored" data-anchor-id="what-are-we-learning-here-1">What are we learning here?</h4>
<p>Remember from week 18:</p>
<p>Categorical variables or <strong>factors</strong> and reference levels.</p>
<ul>
<li>If you have a categorical variable like <code>GENDER</code> then when you use it in an analysis, R will look at the different categories (called <code>levels) e.g., here,</code>Female, Male` and it will pick one level to be the <em>reference</em> or baseline level.</li>
<li>The <em>reference</em> is the the level against which other levels are compared.</li>
<li>Here, the reference level is <code>Female</code> simply because, unless you tell R otherwise, it picks the level with a category name that begins earlier in the alphabet as the reference level.</li>
</ul>
</section>
<section id="how-do-we-interpret-interactions" class="level4">
<h4 class="anchored" data-anchor-id="how-do-we-interpret-interactions">How do we interpret interactions?</h4>
<ul>
<li>It helps to plot the effects estimates, given the model.</li>
</ul>
<p>We can do this in a two-step sequence, similar to the sequence we trialled through weeks 17 and 18:</p>
<ol type="1">
<li>First fit the model</li>
<li>Second, use the model information to plot the predictions, given the effects</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -- first fit the model</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(mean.acc <span class="sc">~</span> FACTOR3_centered<span class="sc">*</span>GENDER, </span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> all.data)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="co"># -- make plot</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(model, <span class="at">type =</span> <span class="st">"pred"</span>, </span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"FACTOR3_centered"</span>, <span class="st">"GENDER"</span>)) <span class="sc">+</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Scale for y is already present.
Adding another scale for y, which will replace the existing scale.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="PSYC122-w19-workbook-answers_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Q.30. Can you identify how the effects of reading strategy (<code>FACTOR3</code>) and gender (<code>GENDER</code>) interact, given the model results summary and this plot?</p></li>
<li><p>A.30. The plot, and the estimate for the interaction <code>FACTOR3_centered:GENDERMale</code>, together show that the coefficient for the effect of reading strategy (<code>FACTOR3_centered</code>) is slightly larger (the slope is slightly steeper) when <code>GENDER</code> is <code>Male</code> instead of `Female.</p></li>
<li><p>Notice that, for this sample, the interaction is not significant, suggesting that there is no difference between genders in the relative effectiveness of reading strategy.</p></li>
</ul>


</section>
</section>
</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Website developed by Matthew Ivory</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../previous-content/index.html">
<p>Previous Content</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>